### PR TITLE
citra_qt: Settings (configuration) default value fix

### LINKED ISSUE #3531: Configuration Backend <Default> Values
Currently we do not indicate if a setting is a default value or not within the configuration.

We do not automatically upgrade users to new default settings.

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
This is to fix #3531.
Design:
1. When a setting does not has a default value, it is stored in the same way as before. (Simple QSettings  entry)
1. When a setting has a default value, it is separated into two entries: `xxxxx\default` and `xxxxx`. If `xxxxx\default` = true, it means that the setting is using its default value, and when the configuration is loaded, the setting will be automatically replaced with the new default value (if any). The `xxxxx` entry stores the setting value, however it is only used when `xxxxx\default` = false. See the `ReadSetting` and `WriteSetting` functions for more detail.
1. In this way the new config file will be compatible with the old file.
1. I did not make any changes to the core/settings part. It remained as-is.

Advantages:
1. We can tell if a user is using the default setting or not and upgrade them to the new defaults when any is changed.
1. Well, I can't think of more.

Concerns:
1. ~~Do we really want to upgrade users to new default settings silently? What if I intentionally set it to some value, and the value happened to be the default value? But~~ I think for a common user it is good enough to use the default settings most of the time.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3924)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
Hmm. After another thought I think I can make it compatible with the old config file. Let me try.

**Comment by BreadFish64** [comment]
>What if I intentionally set it to some value, and the value happened to be the default value?

I think ideally if the user changes the setting at all then the value should not be updated when there's a new default.

File: src/citra_qt/configuration/config.cpp [hunk 1]
```diff
@@ -10,7 +11,6 @@
 #include "network/network.h"
 
 Config::Config() {
-    // TODO: Don't hardcode the path; let the frontend decide where to put the config files.
```
Comment (wwylele) [inline src/citra_qt/configuration/config.cpp]: Why is this removed?
