### PR TITLE
Remove the broken frame_skip option

### LINKED ISSUE #1960: Frameskip issue
Hello! When frameskip will be fixed? It helps you to speed up the game with 10 , 20 FPS.
Example of emulator with frameskip: Dolphin

### PR DESCRIPTION
**Pull request by linkmauve**
Fixes #1960.

### CODE REVIEW

File: src/core/hw/gpu.cpp [hunk 1]
```diff
@@ -519,20 +515,6 @@ template void Write<u8>(u32 addr, const u8 data);
...
-    // Swap buffers based on the frameskip mode, which is a little bit tricky. When
-    // a frame is being skipped, nothing is being rendered to the internal framebuffer(s).
-    // So, we should only swap frames if the last frame was rendered. The rules are:
-    //  - If frameskip == 0 (disabled), always swap buffers
-    //  - If frameskip == 1, swap buffers every other frame (starting from the first frame)
-    //  - If frameskip > 1, swap buffers every frameskip^n frames (starting from the second frame)
-    if ((((Settings::values.frame_skip != 1) ^ last_skip_frame) &&
-         last_skip_frame != g_skip_frame) ||
-        Settings::values.frame_skip == 0) {
-        VideoCore::g_renderer->SwapBuffers();
```
Comment (wwylele) [inline src/core/hw/gpu.cpp]: This line shouldn't be removed

**Comment by yuriks** [comment]
LGTM
