### PR TITLE
Align attribute components

### LINKED ISSUE #1488: Super Smash Bros. Demo - broken characters (WritePicaReg:467: Invalid VS uniform index 127)
With MAD fix I see more stuff than before [THIS VIDEO](https://www.youtube.com/watch?v=gmriJSYnji4)

Tested with https://github.com/citra-emu/citra/commit/3789de6bd9f54e532f290eb11634af27480ab88d

additional merged commits:
- https://github.com/citra-emu/citra/pull/1479
- https://github.com/citra-emu/citra/pull/1302

smash 1
smash 2
smash 4
smash 5
smash 6

[LOG](http://pastebin.com/wVPP823y)

### PR DESCRIPTION
**Pull request by JayFoxRox**
Fixes #1488 and possible a good chunk of others.

Not tested against real hw, not documented on 3dbrew but very very very likely.
Not sure yet wether each component or just each attribute vec is aligned.

Example (Super Smash Bros Demo Characters) of problematic uploads in current master:

Outline:

```
v0.z [Vertex 206], format 0x2, base 0x18201B00, stride 18, element size: 2: 3192.000000
v1.x [Vertex 206], format 0x0, base 0x18201B06, stride 18, element size: 1: -43.000000
v1.y [Vertex 206], format 0x0, base 0x18201B06, stride 18, element size: 1: -118.000000
v1.z [Vertex 206], format 0x0, base 0x18201B06, stride 18, element size: 1: -6.000000
v2.x [Vertex 206], format 0x1, base 0x18201B09, stride 18, element size: 1: 141.000000
v2.y [Vertex 206], format 0x1, base 0x18201B09, stride 18, element size: 1: 83.000000
v2.z [Vertex 206], format 0x1, base 0x18201B09, stride 18, element size: 1: 46.000000
v2.w [Vertex 206], format 0x1, base 0x18201B09, stride 18, element size: 1: 255.000000
v3.x [Vertex 206], format 0x1, base 0x18201B0D, stride 18, element size: 1: 4.000000
v3.y [Vertex 206], format 0x1, base 0x18201B0D, stride 18, element size: 1: 8.000000
v4.x [Vertex 206], format 0x1, base 0x18201B0F, stride 18, element size: 1: 30.000000
v4.y [Vertex 206], format 0x1, base 0x18201B0F, stride 18, element size: 1: 70.000000
```

(v3 are bone indices, v4 are bone weights (30+70 = 100))

Actual model:

```
v0.z [Vertex 234], format 0x2, base 0x1820CCA0, stride 18, element size: 2: 3192.000000
v1.x [Vertex 234], format 0x0, base 0x1820CCA6, stride 18, element size: 1: 43.000000
v1.y [Vertex 234], format 0x0, base 0x1820CCA6, stride 18, element size: 1: 118.000000
v1.z [Vertex 234], format 0x0, base 0x1820CCA6, stride 18, element size: 1: 6.000000
v2.x [Vertex 234], format 0x2, base 0x1820CCA9, stride 18, element size: 2: 18432.000000 << alignment breaks here
v2.y [Vertex 234], format 0x2, base 0x1820CCA9, stride 18, element size: 2: -19443.000000
v3.x [Vertex 234], format 0x1, base 0x1820CCAD, stride 18, element size: 1: 79.000000
v3.y [Vertex 234], format 0x1, base 0x1820CCAD, stride 18, element size: 1: 4.000000
v4.x [Vertex 234], format 0x1, base 0x1820CCAF, stride 18, element size: 1: 8.000000
v4.y [Vertex 234], format 0x1, base 0x1820CCAF, stride 18, element size: 1: 30.000000
```

(v3 are bone indices: index 79?! WTF.. v4 bone weights: 8+30 = 38 WTF..)

Fixed:

Mario
That yellow pokemon thingy..
That orange dude who is in games which I don't like

### CODE REVIEW

File: src/video_core/command_processor.cpp [hunk 1]
```diff
@@ -210,11 +210,13 @@ static void WritePicaReg(u32 id, u32 value, u32 mask) {
 
                     u32 attribute_index = loader_config.GetComponent(component);
                     if (attribute_index < 12) {
+                        int element_size = attribute_config.GetElementSizeInBytes(attribute_index);
+                        load_address = (load_address + element_size - 1) & -element_size;
```
Comment (Subv) [inline src/video_core/command_processor.cpp]: A comment explaining what this does would be nice :)

Comment (lioncash) [inline src/video_core/command_processor.cpp]: It's essentially just a literal form of:
```cpp
 #define ALIGN(load_address, power_of_two) ((load_address) + (power_of_two) - 1) & ~((power_of_two) - 1);
```

This can probably be extracted into a function that can go in common, like

```cpp
template <typename T>
constexpr T Align(T value, size_t power_of_two) {
    return static_cast<T>((load_address + element_size - 1) & ~(element_size - 1));
}
```

then just call that to make it self documenting.

Comment (JayFoxRox) [inline src/video_core/command_processor.cpp]: Probably should contain info about align up and we can probably just use NPOT too (yay for optimizing compilers..):

```
template <typename T>
constexpr T AlignUp(T value, size_t size) {
    return static_cast<T>(value + (size - value % size) % size);
}
```

**Comment by Romsstar** [comment]
Models and Font still broken in #1129 with this and #1479.
Starting to wonder if it's ever gonna be fixed because the problems seem to be so unique to this game.XD

File: src/video_core/command_processor.cpp [hunk 2]
```diff
@@ -7,6 +7,7 @@
 
 #include "common/microprofile.h"
 #include "common/profiler.h"
+#include "common/alignment.h"
```
Comment (lioncash) [inline src/video_core/command_processor.cpp]: Should be alphabetically sorted

File: src/video_core/command_processor.cpp [hunk 3]
```diff
@@ -210,11 +211,13 @@ static void WritePicaReg(u32 id, u32 value, u32 mask) {
 
                     u32 attribute_index = loader_config.GetComponent(component);
                     if (attribute_index < 12) {
+                        int element_size = attribute_config.GetElementSizeInBytes(attribute_index);
+                        load_address = Common::AlignUp<u32>(load_address, element_size);
```
Comment (lioncash) [inline src/video_core/command_processor.cpp]: `<u32>` doesn't need to be specified. `load_address` is already a u32. The compiler will auto-deduct this.

File: src/common/alignment.h [hunk 4]
```diff
@@ -0,0 +1,22 @@
+// This file is under the public domain.
+
+#pragma once
+
+#include <cstddef>
+#include <type_traits>
+
+namespace Common {
+
```
Comment (lioncash) [inline src/common/alignment.h]: Functions should be one indentation level less.

**Comment by JayFoxRox** [comment]
@Romsstar  unless this PR breaks those games this should not be discussed here.
It's another issue which will be fixed seperately. I might try to find time to look at the Digimon rendering.

@lioncash  Thanks for the review! Fixed all style issues.

**Comment by Romsstar** [comment]
@JayFoxRox : Oh I'm sorry. I thought since it fixes 3D Rendering it would be helpful to mention if it doesn't fix it either. Sorry, I just wanted to help. Since nobody looked into the Digimon issue so far, I really don't know what I'm supposed to look out for, so I test every commit that seems to fix stuff that is similar to the digimon issue. I'd be really grateful if you could look into Digimon. My team and I are planning a full (100%) translation on this game but without the font and UI displaying this is a little hard to do. Sorry again.

File: src/common/alignment.h [hunk 5]
```diff
@@ -0,0 +1,22 @@
+// This file is under the public domain.
```
Comment (bunnei) [inline src/common/alignment.h]: This file needs to be added to https://github.com/citra-emu/citra/blob/master/src/common/CMakeLists.txt

**Comment by JayFoxRox** [comment]
All done. I think this can be merged now.

We should probably open a new issue for https://github.com/citra-emu/citra/issues/1487#issuecomment-195436006 if this is really caused by this.

File: src/common/alignment.h [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+#pragma once
+
+#include <cstddef>
+#include <type_traits>
+
+namespace Common {
+
+template <typename T>
+constexpr T AlignUp(T value, size_t size) {
+    static_assert(std::is_unsigned<T>(), "T must be an unsigned value.");
```
Comment (Subv) [inline src/common/alignment.h]: shouldn't this be std::is_unsigned<T>::value?

Comment (JayFoxRox) [inline src/common/alignment.h]: Good catch! Should work with C++11 now (`std::is_unsigned()` is C++14)

**Comment by JayFoxRox** [comment]
@yuriks was super helpful today and helped me test this on real hw (actually.. he did most of the work). He'll change the docs accordingly soon.

Long story short:

* Attributes are aligned to their element size
* Padding is aligned to 4 byte boundaries

I added a commit for the padding alignment and this should be the final form of this PR :)

**Comment by Subv** [comment]
LGTM

**Comment by yuriks** [comment]
LGTM

**Comment by yuriks** [comment]
Can you squash the commits and add a "PICA: " prefix to the commit message?
