### PR TITLE
HLE/FS: Fixed many corner cases in our file handling

### LINKED ISSUE #875: Final Fantasy Explorers: Deleted Save data
I tried to load the save data that dump from cartridge.
They report a Delete save on first boot, then delete it. 
From then on they report being unable to read save data.
<pre><code>Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:75: unknown / unimplemented function 'GetFormatInfo': port=fs:USER, c
md_buff[1]=4, cmd_buff[2]=1, cmd_buff[3]=1, cmd_buff[4]=16386, cmd_buff[5]=26843
1000</code></pre>
Here's the log: http://pastie.org/10251202
Here's the savedata: http://www.filedropper.com/ffexsave

### LINKED ISSUE #1158: Lego Batman 3: Beyond Gotham - Preparing save data looping
lego batman

LOG:
http://pastebin.com/rmxFKKrf

### LINKED ISSUE #1295: Incomplete or improper file stat
To recreate, using ctrulib:

```c
char *path = "sdmc:/3ds/";
struct stat s;

if( stat(path, &s) == 0 )
{
	if(S_ISDIR(s.st_mode)) {
		printf("it's a directory");
	}
	else if(S_ISREG(s.st_mode)) {
		printf("it's a file");
	}
	else {
		printf("something else");
	}
}
else {
	printf("error");
}
```

Assuming you have a "3ds" directory in sdmc, it says it's a file. All directories and all files seems to be seen as "regular files" (i.e. return true after a S_ISREG).

### PR DESCRIPTION
**Pull request by Subv**
Return the correct error codes for the tested situations, this fixes Mario Kart 7's save bug and possibly many others.
Closes #1295 
Closes #1158 
Closes #875

### CODE REVIEW

File: src/core/file_sys/disk_archive.cpp [hunk 1]
```diff
@@ -89,38 +104,57 @@ DiskFile::DiskFile(const DiskArchive& archive, const Path& path, const Mode mode
...
+    if (mode.create_flag && !mode.read_flag && !mode.write_flag) {
+        return ResultCode(ErrorDescription::FS_InvalidOpenFlags, ErrorModule::FS, ErrorSummary::Canceled, ErrorLevel::Status);
+    }
+
+    if (!FileUtil::Exists(path)) {
+        if (!mode.create_flag) {
+            LOG_ERROR(Service_FS, "Non-existing file %s can't be open without mode create.", path.c_str());
+            return ResultCode(ErrorDescription::FS_NotFound, ErrorModule::FS, ErrorSummary::NotFound, ErrorLevel::Status);
+        } else {
+            // Create the file
```
Comment (lioncash) [inline src/core/file_sys/disk_archive.cpp]: This is sorta self-explanatory

**Comment by Subv** [comment]
Updated the PR with an implementation of GetFormatInfo

**Comment by mailwl** [comment]
@Subv, any idea about http://3dbrew.org/wiki/FS:ControlArchive ?
i saw some games which uses it

**Comment by Subv** [comment]
Most games don't use that in any relevant way

**Comment by popalous** [comment]
Do a lot of games use something called CROs?
I have read that Smash Bros, Pokemon, and other use games use them.
What are they, exactly?

**Comment by mailwl** [comment]
CRO offtop here

**Comment by Subv** [comment]
@mailwl We are the ones writing the SD, we don't implement any sort of cache

**Comment by Subv** [comment]
I'm a little hesitant about the GetFormatInfo implementation, i'd like to get some feedback on that

**Comment by RavenHome1** [comment]
@Subv any chance this is related https://github.com/citra-emu/citra/issues/1044

**Comment by Subv** [comment]
Maybe

**Comment by shinyquagsire23** [comment]
Gave it a go with VVVVVV's save bug, didn't fix it. Although in this case it complains about the SD Card not having enough space for the save data, so could be something completely different. Most significant part of the log is probably this:

```
[   0.647401] Common.Filesystem <Warning> common/file_util.cpp:IsDirectory:112: stat failed on /home/maxamillion/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00096100/data/00000001//qsave.vvv: 
[   0.647434] Service.FS <Error> core/file_sys/disk_archive.cpp:Open:118: Non-existing file /home/maxamillion/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00096100/data/00000001//qsave.vvv can't be open without mode create.
[   0.647458] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:75: failed to get a handle for file [Wchar: /qsave.vvv]
[   0.648165] Common.Filesystem <Warning> common/file_util.cpp:IsDirectory:112: stat failed on /home/maxamillion/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00096100/data/00000001//tsave.vvv: 
[   0.648192] Service.FS <Error> core/file_sys/disk_archive.cpp:Open:118: Non-existing file /home/maxamillion/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00096100/data/00000001//tsave.vvv can't be open without mode create.
[   0.648213] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:75: failed to get a handle for file [Wchar: /tsave.vvv]
[   1.406990] Common.Filesystem <Warning> common/file_util.cpp:IsDirectory:112: stat failed on /home/maxamillion/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00096100/data/00000001//unlock.vvv: 
[   1.407037] Service.FS <Error> core/file_sys/disk_archive.cpp:Open:118: Non-existing file /home/maxamillion/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/00096100/data/00000001//unlock.vvv can't be open without mode create.
[   1.407060] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenFile:75: failed to get a handle for file [Wchar: /unlock.vvv]
[   1.449824] Service <Error> core/hle/service/service.cpp:SyncRequest:68: unknown / unimplemented function 'GetArchiveResource': port=fs:USER, cmd_buff[1]=0xC8804402
```
Could be irrelevant though, but the PR fixes corner cases so might be worth looking into?

File: src/core/file_sys/archive_backend.h [hunk 2]
```diff
@@ -159,9 +167,17 @@ class ArchiveFactory : NonCopyable {
     /**
      * Deletes the archive contents and then re-creates the base folder
      * @param path Path to the archive
+     * @param format_info Format information for the new archive
      * @return ResultCode of the operation, 0 on success
      */
-    virtual ResultCode Format(const Path& path) = 0;
+    virtual ResultCode Format(const Path& path, const FileSys::ArchiveFormatInfo& format_info) = 0;
+
+    /*
```
Comment (bunnei) [inline src/core/file_sys/archive_backend.h]: Missing an asterisk

File: src/core/file_sys/archive_extsavedata.cpp [hunk 3]
```diff
@@ -82,13 +82,45 @@ ResultVal<std::unique_ptr<ArchiveBackend>> ArchiveFactory_ExtSaveData::Open(cons
...
+ResultCode ArchiveFactory_ExtSaveData::Format(const Path& path, const FileSys::ArchiveFormatInfo& format_info) {
     // These folders are always created with the ExtSaveData
     std::string user_path = GetExtSaveDataPath(mount_point, path) + "user/";
     std::string boss_path = GetExtSaveDataPath(mount_point, path) + "boss/";
     FileUtil::CreateFullPath(user_path);
     FileUtil::CreateFullPath(boss_path);
-    return RESULT_SUCCESS;
+
+    // Write the format metadata
+    std::string metadata_path = GetExtSaveDataPath(mount_point, path) + "metadata";
```
Comment (bunnei) [inline src/core/file_sys/archive_extsavedata.cpp]: Should this have a `/` at the end to be consistent with the above?

File: src/core/file_sys/archive_extsavedata.cpp [hunk 4]
```diff
@@ -82,13 +82,45 @@ ResultVal<std::unique_ptr<ArchiveBackend>> ArchiveFactory_ExtSaveData::Open(cons
...
+        file.WriteBytes(&format_info, sizeof(format_info));
+        return RESULT_SUCCESS;
+    }
+
+    // TODO(Subv): Find the correct error code
+    return ResultCode(-1);
+}
+
+ResultVal<ArchiveFormatInfo> ArchiveFactory_ExtSaveData::GetFormatInfo(const Path& path) const {
+    std::string metadata_path = GetExtSaveDataPath(mount_point, path) + "metadata";
```
Comment (bunnei) [inline src/core/file_sys/archive_extsavedata.cpp]: Ditto with the above

File: src/core/file_sys/archive_extsavedata.h [hunk 5]
```diff
@@ -31,10 +31,19 @@ class ArchiveFactory_ExtSaveData final : public ArchiveFactory {
     std::string GetName() const override { return "ExtSaveData"; }
 
     ResultVal<std::unique_ptr<ArchiveBackend>> Open(const Path& path) override;
-    ResultCode Format(const Path& path) override;
+    ResultCode Format(const Path& path, const FileSys::ArchiveFormatInfo& format_info) override;
+    ResultVal<ArchiveFormatInfo> GetFormatInfo(const Path& path) const override;
 
     const std::string& GetMountPoint() const { return mount_point; }
 
+    /*
```
Comment (bunnei) [inline src/core/file_sys/archive_extsavedata.h]: Missing an asterisk

File: src/core/file_sys/archive_extsavedata.cpp [hunk 6]
```diff
@@ -82,13 +82,45 @@ ResultVal<std::unique_ptr<ArchiveBackend>> ArchiveFactory_ExtSaveData::Open(cons
...
+        file.ReadBytes(&info, sizeof(info));
+        return MakeResult<ArchiveFormatInfo>(info);
+    }
+
+    LOG_ERROR(Service_FS, "Could not open metadata information for archive");
+    // TODO(Subv): Verify error code
+    return ResultCode(ErrorDescription::FS_NotFormatted, ErrorModule::FS, ErrorSummary::InvalidState, ErrorLevel::Status);
+}
+
+void ArchiveFactory_ExtSaveData::WriteIcon(const Path& path, u8* icon_data, u32 icon_size) {
```
Comment (bunnei) [inline src/core/file_sys/archive_extsavedata.cpp]: Should be `const u8* icon_data`

File: src/core/file_sys/archive_extsavedata.cpp (hunk 3 above)
Comment (Subv) [inline src/core/file_sys/archive_extsavedata.cpp]: This is a file, not a folder

File: src/core/file_sys/archive_savedata.cpp [hunk 7]
```diff
@@ -31,6 +31,12 @@ static std::string GetSaveDataPath(const std::string& mount_location, u64 progra
     return Common::StringFromFormat("%s%08x/%08x/data/00000001/", mount_location.c_str(), high, low);
 }
 
+static std::string GetSaveDataMetadataPath(const std::string& mount_location, u64 program_id) {
+    u32 high = program_id >> 32;
+    u32 low = program_id & 0xFFFFFFFF;
```
Comment (bunnei) [inline src/core/file_sys/archive_savedata.cpp]: Missing casts

File: src/core/file_sys/archive_extsavedata.cpp (hunk 4 above)
Comment (Subv) [inline src/core/file_sys/archive_extsavedata.cpp]: This is a file, not a folder

File: src/core/hle/service/fs/archive.h [hunk 8]
```diff
@@ -177,10 +177,20 @@ ResultVal<u64> GetFreeBytesInArchive(ArchiveHandle archive_handle);
...
  * identified by the specified id code and path
  * @param id_code The id of the archive to format
+ * @param format_info Format information about the new archive
  * @param path The path to the archive, if relevant.
  * @return ResultCode 0 on success or the corresponding code on error
  */
-ResultCode FormatArchive(ArchiveIdCode id_code, const FileSys::Path& path = FileSys::Path());
+ResultCode FormatArchive(ArchiveIdCode id_code, const FileSys::ArchiveFormatInfo& format_info, const FileSys::Path& path = FileSys::Path());
+
+/*
```
Comment (bunnei) [inline src/core/hle/service/fs/archive.h]: Missing asterisk

File: src/core/hle/service/fs/archive.cpp [hunk 9]
```diff
@@ -294,13 +307,14 @@ ResultVal<Kernel::SharedPtr<File>> OpenFileFromArchive(ArchiveHandle archive_han
     if (archive == nullptr)
         return ERR_INVALID_HANDLE;
 
-    std::unique_ptr<FileSys::FileBackend> backend = archive->OpenFile(path, mode);
-    if (backend == nullptr) {
+    auto backend = archive->OpenFile(path, mode);
+    if (backend.Failed()) {
+        return backend.Code();
         return ResultCode(ErrorDescription::FS_NotFound, ErrorModule::FS,
```
Comment (bunnei) [inline src/core/hle/service/fs/archive.cpp]: Merge mistake here?

File: src/core/hle/service/cfg/cfg.cpp [hunk 10]
```diff
@@ -308,7 +308,7 @@ ResultCode UpdateConfigNANDSavegame() {
 
 ResultCode FormatConfig() {
     ResultCode res = DeleteConfigNANDSaveFile();
-    if (!res.IsSuccess())
+    if (!res.IsSuccess() && res.description != ErrorDescription::FS_NotFound)
```
Comment (bunnei) [inline src/core/hle/service/cfg/cfg.cpp]: Could use a comment explaining why you are doing this additional check here.

File: src/core/file_sys/disk_archive.cpp [hunk 11]
```diff
@@ -89,38 +104,57 @@ DiskFile::DiskFile(const DiskArchive& archive, const Path& path, const Mode mode
     this->mode.hex = mode.hex;
 }
 
-bool DiskFile::Open() {
-    if (!mode.create_flag && !FileUtil::Exists(path)) {
-        LOG_ERROR(Service_FS, "Non-existing file %s can't be open without mode create.", path.c_str());
-        return false;
+ResultCode DiskFile::Open() {
+    if (FileUtil::IsDirectory(path))
+        return ResultCode(ErrorDescription::FS_NotAFile, ErrorModule::FS, ErrorSummary::Canceled, ErrorLevel::Status);
```
Comment (bunnei) [inline src/core/file_sys/disk_archive.cpp]: Is it safe to assume that all of the errors within this patch have been verified on HW unless otherwise noted with a TODO comment?

File: src/core/hle/service/fs/archive.cpp (hunk 9 above)
Comment (Subv) [inline src/core/hle/service/fs/archive.cpp]: Indeed, good catch!

File: src/core/file_sys/disk_archive.cpp (hunk 11 above)
Comment (Subv) [inline src/core/file_sys/disk_archive.cpp]: Yes

**Comment by RavenHome1** [comment]
@Subv is this code function is to allow games to run without having to dump and use a save file from the 3ds to bypass the game hanging?

**Comment by Subv** [comment]
Ideally you should be able to create a save file in the game itself while running it in citra, so yes, i guess?

**Comment by RavenHome1** [comment]
yeah that is the answer to my question

**Comment by bunnei** [comment]
@Subv I'd like to get this merged. Can you address the above comments and rebase with latest master?

Also, formal request for additional code reviews. I plan on having this one merged by the end of the week (assuming the above comments are addressed) if I do not hear from anyone else.

File: src/core/file_sys/archive_savedata.cpp (hunk 7 above)
Comment (Subv) [inline src/core/file_sys/archive_savedata.cpp]: Are casts needed here?

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-01-16T22:04:43Z: https://github.com/citra-emu/citra/compare/7b2d03476985ca3747350d195c32654a371ee85b...Subv:d0612b21d25e428e1cba170085c56c0b76f7ee50

**Comment by Subv** [comment]
Updated and rebased.

File: src/core/file_sys/archive_savedata.cpp (hunk 7 above)
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: They prevent warnings in MSVC (narrowing implicit conversion).

**Comment by yuriks** [comment]
This breaks Fire Emblem, which now loops on these two dialogs forever:

clipboard01
clipboard02

Previously it attempted once (on every boot) and then said it couldn't detect the SD card before continuing.

On the other hand, it fixes save creation in Bravely Default, which means you can now bypass the AR intro movie by starting the game until it freezes on cam:U, then restarting and loading the save.

File: src/core/hle/service/fs/fs_user.cpp [hunk 12]
```diff
@@ -245,12 +245,12 @@ static void CreateFile(Service::Interface* self) {
...
     auto filename_type    = static_cast<FileSys::LowPathType>(cmd_buff[4]);
     u32 filename_size     = cmd_buff[5];
-    u32 file_size         = cmd_buff[7];
+    u64 file_size         = ((u64)cmd_buff[8] << 32) | cmd_buff[7];
     u32 filename_ptr      = cmd_buff[10];
 
     FileSys::Path file_path(filename_type, filename_size, filename_ptr);
 
-    LOG_DEBUG(Service_FS, "type=%d size=%d data=%s", filename_type, filename_size, file_path.DebugStr().c_str());
+    LOG_DEBUG(Service_FS, "type=%d size=%lld data=%s", filename_type, filename_size, file_path.DebugStr().c_str());
```
Comment (lioncash) [inline src/core/hle/service/fs/fs_user.cpp]: should be an unsigned formatting specifier.

**Comment by Subv** [comment]
Huh, @yuriks I'm unable to reproduce, i can't even get it to show that screen, it just says "The game must be initialized before you can continue" and then it hangs on a DSP::IsDataReady/RecvData loop

**Comment by Subv** [comment]
Updated

**Comment by internetakias** [comment]
Doesn't seem to work with the european version of MK7

**Comment by mailwl** [comment]
@yuriks , can you test Fire Emblem with this code?
https://github.com/mailwl/citra/blob/ctrl_archive/src/core/hle/service/fs/fs_user.cpp#L393-L444
https://github.com/mailwl/citra/blob/ctrl_archive/src/core/hle/service/fs/fs_user.cpp#L778
(It's incompleted stub for ControlArchive, which helps me with LEGO save broken loop. )

**Comment by Subv** [comment]
Nevermind my previous message, i can reproduce it, however only in Release mode

**Comment by Subv** [comment]
After some reversing, turns out Fire Emblem is expecting an ErrorDescription between 100 and 179 exclusive in the OpenArchive call when opening the ExtSaveData, I wonder what those values mean. (We're currently returning 340)

**Comment by JohnGodgames** [comment]
@Subv after some of your reversing all of LEGO games and Spyhunter not work again :(

**Comment by Subv** [comment]
What, I have made no changes to this PR yet.

**Comment by JohnGodgames** [comment]
What about https://github.com/Subv/citra/commit/3c6fc27661c104de29f3d769669878a07ff8a54a ?

**Comment by Subv** [comment]
There's no way that's the cause.

**Comment by JohnGodgames** [comment]
Ahh sorry,  I was trying it with build without save fix merged...my fault it works now

**Comment by yuriks** [comment]
The 100-179 range corresponds to "not found" according to https://www.3dbrew.org/wiki/Error_codes

**Comment by Subv** [comment]
Updated, the Fire Emblem problem is fixed now.

**Comment by internetakias** [comment]
Latest commit seems to break Animal Crossing New Leaf and spams http://i.imgur.com/kxJVhdD.png into the error log

**Comment by Subv** [comment]
Updated again

**Comment by yuriks** [comment]
Does fix:
 - Fire Emblem: A and Bravely Default completely
 - Spurious errors creating save in Project Mirai DX, 
Does not fix: (Not confirmed either way if these are related to FS bugs.)
 - Starting Project Mirai DX with an existing save still causes an infinite loading loop.
 - Can't start a new save in ALBW.

File: src/core/file_sys/archive_backend.h [hunk 13]
```diff
@@ -62,6 +62,14 @@ class Path {
     std::u16string u16str;
 };
 
+struct ArchiveFormatInfo {
+    u32 total_size; ///< The pre-defined size of the archive, as specified in the Create or Format call
+    u32 number_directories; ///< The pre-defined number of directories in the archive, as specified in the Create or Format call
+    u32 number_files; ///< The pre-defined number of files in the archive, as specified in the Create or Format call
```
Comment (yuriks) [inline src/core/file_sys/archive_backend.h]: These should have an explicit endianess since they're serialized to disk.

File: src/core/file_sys/archive_extsavedata.cpp [hunk 14]
```diff
@@ -74,21 +74,59 @@ bool ArchiveFactory_ExtSaveData::Initialize() {
...
     std::string boss_path = GetExtSaveDataPath(mount_point, path) + "boss/";
     FileUtil::CreateFullPath(user_path);
     FileUtil::CreateFullPath(boss_path);
-    return RESULT_SUCCESS;
+
+    // Write the format metadata
+    std::string metadata_path = GetExtSaveDataPath(mount_point, path) + "metadata";
+    FileUtil::IOFile file(metadata_path, "wb");
+
+    if (file.IsOpen()) {
```
Comment (yuriks) [inline src/core/file_sys/archive_extsavedata.cpp]: IMO you should invert this condition so that the error return is inside the if. It's more straightforward to read that way.

File: src/core/file_sys/archive_extsavedata.cpp [hunk 15]
```diff
@@ -74,21 +74,59 @@ bool ArchiveFactory_ExtSaveData::Initialize() {
...
+    // TODO(Subv): Find the correct error code
+    return ResultCode(-1);
+}
+
+ResultVal<ArchiveFormatInfo> ArchiveFactory_ExtSaveData::GetFormatInfo(const Path& path) const {
+    std::string metadata_path = GetExtSaveDataPath(mount_point, path) + "metadata";
+    FileUtil::IOFile file(metadata_path, "rb");
+
+    if (file.IsOpen()) {
+        ArchiveFormatInfo info;
```
Comment (yuriks) [inline src/core/file_sys/archive_extsavedata.cpp]: You should initialized this to zero or with known-good default values: In case we expand the struct later on, this will be necessary to stay compatible with previous versions of the format.

File: src/core/file_sys/archive_extsavedata.cpp [hunk 16]
```diff
@@ -74,21 +74,59 @@ bool ArchiveFactory_ExtSaveData::Initialize() {
...
+
+    // TODO(Subv): Find the correct error code
+    return ResultCode(-1);
+}
+
+ResultVal<ArchiveFormatInfo> ArchiveFactory_ExtSaveData::GetFormatInfo(const Path& path) const {
+    std::string metadata_path = GetExtSaveDataPath(mount_point, path) + "metadata";
+    FileUtil::IOFile file(metadata_path, "rb");
+
+    if (file.IsOpen()) {
```
Comment (yuriks) [inline src/core/file_sys/archive_extsavedata.cpp]: Same re. inverting the condition

File: src/core/file_sys/archive_extsavedata.cpp [hunk 17]
```diff
@@ -74,21 +74,59 @@ bool ArchiveFactory_ExtSaveData::Initialize() {
...
+    }
+
+    LOG_ERROR(Service_FS, "Could not open metadata information for archive");
+    // TODO(Subv): Verify error code
+    return ResultCode(ErrorDescription::FS_NotFormatted, ErrorModule::FS, ErrorSummary::InvalidState, ErrorLevel::Status);
+}
+
+void ArchiveFactory_ExtSaveData::WriteIcon(const Path& path, const u8* icon_data, u32 icon_size) {
+    std::string game_path = FileSys::GetExtSaveDataPath(GetMountPoint(), path);
+    FileUtil::IOFile icon_file(game_path + "icon", "wb+");
```
Comment (yuriks) [inline src/core/file_sys/archive_extsavedata.cpp]: If this is always a SMDH, would be good to add it as the file extension.

Comment (yuriks) [inline src/core/file_sys/archive_extsavedata.cpp]: Also, why are you opening it with mode `+`?

File: src/core/file_sys/archive_extsavedata.h [hunk 18]
```diff
@@ -31,10 +31,19 @@ class ArchiveFactory_ExtSaveData final : public ArchiveFactory {
...
 
     const std::string& GetMountPoint() const { return mount_point; }
 
+    /**
+     * Writes the SMDH icon of the ExtSaveData to file
+     * @param path Path of this ExtSaveData
+     * @param icon_data Binary data of the icon
+     * @param icon_size Size of the icon data
+     */
+    void WriteIcon(const Path& path, const u8* icon_data, u32 icon_size);
```
Comment (yuriks) [inline src/core/file_sys/archive_extsavedata.h]: Any reason for `icon_size` not to be `size_t`?

File: src/core/file_sys/archive_savedata.cpp [hunk 19]
```diff
@@ -26,11 +26,17 @@ static std::string GetSaveDataContainerPath(const std::string& sdmc_directory) {
 }
 
 static std::string GetSaveDataPath(const std::string& mount_location, u64 program_id) {
-    u32 high = program_id >> 32;
-    u32 low = program_id & 0xFFFFFFFF;
+    u32 high = (u32)(program_id >> 32);
+    u32 low = (u32)(program_id & 0xFFFFFFFF);
```
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Is this just a stylistic change or does it fix some subtle bug?

Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Also, I think that if you're explicitly casting, the and mask isn't necessary.

File: src/core/file_sys/archive_savedata.cpp [hunk 20]
```diff
@@ -26,11 +26,17 @@ static std::string GetSaveDataContainerPath(const std::string& sdmc_directory) {
...
     return Common::StringFromFormat("%s%08x/%08x/data/00000001/", mount_location.c_str(), high, low);
 }
 
+static std::string GetSaveDataMetadataPath(const std::string& mount_location, u64 program_id) {
+    u32 high = (u32)(program_id >> 32);
+    u32 low = (u32)(program_id & 0xFFFFFFFF);
```
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Same.

File: src/core/file_sys/archive_savedata.cpp [hunk 21]
```diff
@@ -26,11 +26,17 @@ static std::string GetSaveDataContainerPath(const std::string& sdmc_directory) {
...
 
 static std::string GetSaveDataPath(const std::string& mount_location, u64 program_id) {
-    u32 high = program_id >> 32;
-    u32 low = program_id & 0xFFFFFFFF;
+    u32 high = (u32)(program_id >> 32);
+    u32 low = (u32)(program_id & 0xFFFFFFFF);
     return Common::StringFromFormat("%s%08x/%08x/data/00000001/", mount_location.c_str(), high, low);
 }
 
+static std::string GetSaveDataMetadataPath(const std::string& mount_location, u64 program_id) {
```
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: IMO you should merge these two (almost identical) functions and just add the appropriate suffix in the call sites.

File: src/core/file_sys/archive_savedata.cpp [hunk 22]
```diff
@@ -51,11 +57,35 @@ ResultVal<std::unique_ptr<ArchiveBackend>> ArchiveFactory_SaveData::Open(const P
...
+    }
     return RESULT_SUCCESS;
 }
 
+ResultVal<ArchiveFormatInfo> ArchiveFactory_SaveData::GetFormatInfo(const Path& path) const {
+    std::string metadata_path = GetSaveDataMetadataPath(mount_point, Kernel::g_current_process->codeset->program_id);
+    FileUtil::IOFile file(metadata_path, "rb");
+
+    if (file.IsOpen()) {
+        ArchiveFormatInfo info;
```
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Same comment re. initializing struct with default values.

File: src/core/hle/result.h [hunk 23]
```diff
@@ -19,8 +19,12 @@
 enum class ErrorDescription : u32 {
     Success = 0,
     WrongAddress = 53,
-    FS_NotFound = 100,
+    FS_NotFound = 120,
+    FS_AlreadyExists = 190,
+    FS_InvalidOpenFlags = 230,
+    FS_NotAFile = 250,
     FS_NotFormatted = 340, ///< This is used by the FS service when creating a SaveData archive
```
Comment (yuriks) [inline src/core/hle/result.h]: Is this comment still accurate/relevant?

File: src/core/hle/service/fs/archive.cpp [hunk 24]
```diff
@@ -103,7 +103,14 @@ ResultVal<bool> File::SyncRequest() {
             u32 address = cmd_buff[5];
             LOG_TRACE(Service_FS, "Read %s %s: offset=0x%llx length=%d address=0x%x",
                       GetTypeName().c_str(), GetName().c_str(), offset, length, address);
-            cmd_buff[2] = static_cast<u32>(backend->Read(offset, length, Memory::GetPointer(address)));
+            if (offset + length > backend->GetSize())
+                LOG_ERROR(Service_FS, "Reading from out of bounds offset=0x%llX length=0x%08X file_size=0x%llX", offset, length, backend->GetSize());
```
Comment (yuriks) [inline src/core/hle/service/fs/archive.cpp]: Long line. I'd add braces to this to improve readability.

File: src/core/hle/service/fs/archive.cpp [hunk 25]
```diff
@@ -116,7 +123,13 @@ ResultVal<bool> File::SyncRequest() {
...
             LOG_TRACE(Service_FS, "Write %s %s: offset=0x%llx length=%d address=0x%x, flush=0x%x",
                       GetTypeName().c_str(), GetName().c_str(), offset, length, address, flush);
-            cmd_buff[2] = static_cast<u32>(backend->Write(offset, length, flush != 0, Memory::GetPointer(address)));
+
+            ResultVal<size_t> written = backend->Write(offset, length, flush != 0, Memory::GetPointer(address));
+            if (written.Failed()) {
+                cmd_buff[1] = written.Code().raw;
+                return written.Code();
+            }
+            cmd_buff[2] = static_cast<u32>(written.MoveFrom());
```
Comment (yuriks) [inline src/core/hle/service/fs/archive.cpp]: Using MoveFrom isn't really necessary here since you already checked for a failure earlier and it's just a u32. Just use `*written`.

File: src/core/hle/service/fs/archive.cpp [hunk 26]
```diff
@@ -103,7 +103,14 @@ ResultVal<bool> File::SyncRequest() {
...
                       GetTypeName().c_str(), GetName().c_str(), offset, length, address);
-            cmd_buff[2] = static_cast<u32>(backend->Read(offset, length, Memory::GetPointer(address)));
+            if (offset + length > backend->GetSize())
+                LOG_ERROR(Service_FS, "Reading from out of bounds offset=0x%llX length=0x%08X file_size=0x%llX", offset, length, backend->GetSize());
+            ResultVal<size_t> read = backend->Read(offset, length, Memory::GetPointer(address));
+            if (read.Failed()) {
+                cmd_buff[1] = read.Code().raw;
+                return read.Code();
+            }
+            cmd_buff[2] = static_cast<u32>(read.MoveFrom());
```
Comment (yuriks) [inline src/core/hle/service/fs/archive.cpp]: Same re. `MoveFrom`

**Comment by yuriks** [comment]
Bunch of minor comments, otherwise looks ok.

File: src/core/file_sys/archive_extsavedata.cpp (hunk 17 above)
Comment (Subv) [inline src/core/file_sys/archive_extsavedata.cpp]: This file may be accessible from userland and its supposed to be called that in the console

File: src/core/file_sys/archive_savedata.cpp (hunk 19 above)
Comment (Subv) [inline src/core/file_sys/archive_savedata.cpp]: Refer to https://github.com/citra-emu/citra/pull/1302#discussion-diff-48613669

File: src/core/file_sys/archive_savedata.cpp (hunk 20 above)
Comment (Subv) [inline src/core/file_sys/archive_savedata.cpp]: https://github.com/citra-emu/citra/pull/1302#discussion-diff-48613669

File: src/core/file_sys/archive_savedata.cpp (hunk 21 above)
Comment (Subv) [inline src/core/file_sys/archive_savedata.cpp]: I disagree, the semantics are different, one is supposed to return a directory (along with the / at the end), and the other is supposed to return a file.

File: src/core/hle/result.h (hunk 23 above)
Comment (Subv) [inline src/core/hle/result.h]: Yes

**Comment by Subv** [comment]
Updated.
I'm now initializing the ArchiveFormatInfos with zeros because it's unlikely that we'll ever use those values ourselves and the games seem to require the specific values they themselves pass upon creation.

File: src/core/file_sys/archive_savedata.cpp (hunk 19 above)
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: You've seen nothing. Anyway, comment about the mask still stands.

File: src/core/file_sys/archive_savedata.cpp (hunk 21 above)
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Well, yes, but the code is the same. Make it a "GetSaveDataPathPrefix" or something.

File: src/core/file_sys/archive_savedata.cpp (hunk 20 above)
Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Same, mask.

File: src/core/file_sys/archive_savedata.cpp (hunk 19 above)
Comment (mailwl) [inline src/core/file_sys/archive_savedata.cpp]: JetBrains R# for C++ will warn about c-style cast

Comment (yuriks) [inline src/core/file_sys/archive_savedata.cpp]: Well, it's allowed by our style for numeric casts.

**Comment by pippo2931** [comment]
I implemented GetArchiveResource
with some hacky values and Fire Emblem Fate
goes through the character selection.

static void GetArchiveResource(Service::Interface* self) {
    u32* cmd_buff = Kernel::GetCommandBuffer();
    cmd_buff[1] = RESULT_SUCCESS.raw;
    cmd_buff[2] = 512;
    cmd_buff[3] = 16384;
    cmd_buff[4] = 0xFFFFFFFF;
    cmd_buff[5] = 0xFFFFFFFF;
}

shinyquagsire23 commented on Dec 30, 2015
Gave it a go with VVVVVV's save bug, didn't fix it. Although in this case it complains about the SD Card not having enough space for the save data, so could be something completely different. Most significant part of the log is probably this:
[   1.449824] Service <Error> core/hle/service/service.cpp:SyncRequest:68: unknown / unimplemented function 'GetArchiveResource': port=fs:USER, cmd_buff[1]=0xC8804402

**Comment by JayFoxRox** [comment]
@pippo2931 https://www.3dbrew.org/wiki/Filesystem_services#ArchiveResource
You should probably use:

```
cmd_buff[4] = 0x80000; // 8GiB capacity
cmd_buff[5] = 0x80000; // 8GiB free
```

Your current values might overflow.

How exactly this will be managed in an actual patch is probably up for discussion. You'd probably want to emulate a fixed device size (say.. 16 GiB) and then slowly accumulate a counter whenever data is returned or do it once on startup and then update it on writes.
I don't think we can use host fs information as it probably wouldn't handle storage sizes of multiple TB.

**Comment by Xcedf** [comment]
Just some little bug report:
In Super Mario 3d Land i use the save form original console to get ingame but
after https://github.com/Subv/citra/commit/296f5a3a3d692ca1b3cabfc16fb87f85af83f354
emulator can't see it, like there is no save, please take a look

**Comment by Subv** [comment]
@Xcedf Just create a metadata file where citra expects it and it should work again. The problem happens because Citra can't find the file and therefore thinks that the savedata doesn't exist

**Comment by Xcedf** [comment]
**@Subv** Thanks a lot, save file works again

**Comment by bunnei** [comment]
@Subv squash out the fixups please, seems like this is good to go!
@pippo2931's (possible) addition can be reserved for a future patch.

**Comment by bunnei** [comment]
LGTM
