### PR TITLE
service/nwm_uds: Add NetworkStatusChangeReason

### LINKED ISSUE #3975: Pokémon Mystery Dungeon: Gates to Infinity fails to start Wireless Mode
Please bear with me as this is my first time opening an issue.

Wireless Mode allows players to beat challenge missions/explore together, and this is how it is supposed to work on a real 3DS:
https://www.youtube.com/watch?v=M_a9kXpbMJA

Citra doesn't even boot Wireless Mode, as an error message appears before the screen changes to the Wireless Mode screen:
https://www.youtube.com/watch?v=eVYV5PNEpHw

**Version used**: Citra Canary #653, Citra Nightly #812
**Log**: https://pastebin.com/QvFRZ68G for Canary, https://pastebin.com/NkQHj8pP for Nightly

Observations:
- " **[  32.877074] Service <Error> core/hle/service/service.cpp:ReportUnimplementedFunction:161: unknown / unimplemented function 'SetProbeResponseParam': port='nwm::UDS' cmd_buf={[0]=0x210080, [1]=0x321f00, [2]=0x0}** " 
shows up at the log right before the error message is displayed

- If you try to find a room right after the host presses the "Call a friend" button, you can actually see the room for a few seconds, with gibberish text instead of the actual Paradise name (check the blue text). Attemping to join said room causes a softlock: https://media.discordapp.net/attachments/376495482819706891/470605308151070730/unknown.png

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
This is a guess based on HW tests performed on real 3DSes. No reverse engineering was done because I was not really sure how to.

Supersedes part of #5331

---

The following is a summary of the test results, for future reference:

This value is 0x0 initially.
After creating/connecting to a network, this value changes to 0x1. Afterwards, sending/receiving data does not change the value. Clients connecting or disconnecting does not change the value.
Failed attempts to connect do not change the value (0x0).

When the application destroys/disconnects from the network actively, this value does not change (0x1), and nor does the status value (this is pretty strange).
When the connection was lost due to the host closing the network or ejecting the client, this value changes to 0x4. However, on Citra, apparently these types of 'unexpected connection loss' are not handled yet.

On my 3DS, UDS won't let me recreate or reconnect unless I shutdown UDS. (Not sure if something is wrong with this.) When UDS is reinitialized, this value is set back to 0x0.

---

This should fix multiplayer for a few games, including Pokemon Mystery Dungeon: Gates to Infinity (i.e. fixes #3975) and likely more.

Warioware Gold is not fully fixed but seems to progress a bit further?

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5377)

### CODE REVIEW

**Comment by zhaowenlan1779** [comment]
Marked as WIP as more tests need to be done regarding the `Connecting` status

**Comment by MojoJojoDojo** [comment]
Gates To Infinity got fixed without this PR (placebo?) : 
https://github.com/citra-emu/citra/issues/3975

File: src/core/hle/service/nwm/nwm_uds.h [hunk 1]
```diff
@@ -73,9 +73,15 @@ enum class NetworkStatus {
     ConnectedAsSpectator = 10,
 };
 
+enum class NetworkStatusChangeReason {
```
Comment (BreadFish64) [inline src/core/hle/service/nwm/nwm_uds.h:76]:
```suggestion
enum class NetworkStatusChangeReason : u32 {
```

File: src/core/hle/service/nwm/nwm_uds.h [hunk 2]
```diff
@@ -73,9 +73,15 @@ enum class NetworkStatus {
...
+    None = 0,
+    ConnectionEstablished = 1,
+    ConnectionLost = 4,
+};
+
 struct ConnectionStatus {
     u32_le status;
-    INSERT_PADDING_WORDS(1);
+    u32_le status_change_reason;
```
Comment (BreadFish64) [inline src/core/hle/service/nwm/nwm_uds.h:84]:
```suggestion
    enum_le<NetworkStatusChangeReason> status_change_reason;
```
Would it be reasonable to store this as the enum instead of an integer?

**Review by FearlessTobi — APPROVED** [review]
