### PR TITLE
PICA: Properly emulate 1-stage delay in the combiner buffer

### LINKED ISSUE #1140: TEV buffer implementation is incorrect
@fincs pointed out that the Citra implementation of TEV buffers is incorrect. (Each stage should access the previous buffer instead of the current.)

I plan on at some point writing hwtests and fixing this.

### PR DESCRIPTION
**Pull request by yuriks**
This was discovered and verified by @fincs. The tev combiner buffer
actually lags behind by one stage, meaning stage 1 reads the initial
color, stage 2 reads stage 0's output, and so on.

Fixes character portraits in Fire Emblem: Awakening and world textures
in Zelda: ALBW.

Fixes #1140

### CODE REVIEW

File: src/video_core/rasterizer.cpp [hunk 1]
```diff
@@ -498,7 +498,8 @@ static void ProcessTriangleInternal(const Shader::OutputVertex& v0,
             // with some basic arithmetic. Alpha combiners can be configured separately but work
             // analogously.
             Math::Vec4<u8> combiner_output;
-            Math::Vec4<u8> combiner_buffer = {
+            Math::Vec4<u8> combiner_buffer = {0, 0, 0, 0};
```
Comment (bunnei) [inline src/video_core/rasterizer.cpp]: Can't this just be `{}`?

**Comment by bunnei** [comment]
LGTM

File: src/video_core/rasterizer.cpp (hunk 1 above)
Comment (yuriks) [inline src/video_core/rasterizer.cpp]: No: https://github.com/citra-emu/citra/blob/master/src/common/vector_math.h#L358

Comment (bunnei) [inline src/video_core/rasterizer.cpp]: Ah right.. I recall now we had some previous bugs in the SW rasterizer due to the above assumption.

**Comment by bunnei** [comment]
Tested, works well!
