### PR TITLE
citra_qt: fix the stuck in fullscreen mode and hotkey bugs

### LINKED ISSUE #4876: "Stop emulation" does not work while playing in fullscreen
Unable to **stop** emulation (exit to games list) while playing in fullscreen mode.
So to stop emulation you need first to quit fullscreen mode, and then you can stop it and get back to games list.
This occurs in windows 7 in both latest canary and nightly builds.

_What should Normally happen:_  The emulation should stop even in fullscreen, and user should go back to games list

### PR DESCRIPTION
**Pull request by vvanelslande**
The stuck in fullscreen mode bug happens if the emulated program exits, is fixed by adding [this](https://github.com/citra-emu/citra/compare/master...vvanelslande:hotkey-and-fullscreen-fixes?expand=1#diff-5e8bf22f5c3b3579c402308dd96b7563R888-R894), steps to reproduce:
- Start [FBI](https://github.com/Steveice10/FBI)
- Press START

The fixed hotkeys (I changed them to use [connect](https://doc.qt.io/qt-5/qobject.html#connect) instead of [setShortcut](https://doc.qt.io/qt-5/qaction.html#shortcut-prop) + [setShortcutContext](https://doc.qt.io/qt-5/qaction.html#shortcutContext-prop)) are:
- Load File (was not working in windowed mode), fixed by removing the [setShortcut](https://doc.qt.io/qt-5/qaction.html#shortcut-prop) + [setShortcutContext](https://doc.qt.io/qt-5/qaction.html#shortcutContext-prop) calls (there was already a [connect](https://doc.qt.io/qt-5/qobject.html#connect) call)
- Stop Emulation (was not working in fullscreen mode), fixed with the [connect](https://doc.qt.io/qt-5/qobject.html#connect) change and [this](https://github.com/citra-emu/citra/compare/master...vvanelslande:hotkey-and-fullscreen-fixes?expand=1#diff-5e8bf22f5c3b3579c402308dd96b7563R888-R894) change
- Exit Citra (was not working in fullscreen mode), fixed with the [connect](https://doc.qt.io/qt-5/qobject.html#connect) change

Fixes #4876

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4906)

### CODE REVIEW

File: src/citra_qt/main.cpp [hunk 1]
```diff
@@ -376,7 +364,13 @@ void GMainWindow::InitializeHotkeys() {
         hotkey_registry.GetShortcutContext("Main Window", "Toggle Status Bar"));
 
     connect(hotkey_registry.GetHotkey("Main Window", "Load File", this), &QShortcut::activated,
-            this, &GMainWindow::OnMenuLoadFile);
+            ui.action_Load_File, &QAction::trigger);
```
Comment (zhaowenlan1779) [inline src/citra_qt/main.cpp]: This will likely open the load files dialog, even when emulation is running.

Comment (vvanelslande) [reply src/citra_qt/main.cpp]: the user can do this in nightly and canary

Comment (zhaowenlan1779) [reply src/citra_qt/main.cpp]: Ah, this seems correct. My bad
