### PR TITLE
HLE/SVC: Implement UnmapMemoryBlock.

### LINKED ISSUE #1324: Hello Kitty to Issho! Block Crash Z - GSPSharedMem: already mapped at 0x10000000!
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

LOG: http://pastie.org/10662697

### PR DESCRIPTION
**Pull request by Subv**
This implementation will need to be (almost completely) changed when we implement multiprocess support.

The error codes have been verified in hardware

Closes #1324

### CODE REVIEW

File: src/core/hle/kernel/shared_memory.h [hunk 1]
```diff
@@ -44,6 +44,9 @@ class SharedMemory final : public Object {
     static const HandleType HANDLE_TYPE = HandleType::SharedMemory;
     HandleType GetHandleType() const override { return HANDLE_TYPE; }
 
+    /// Required alignment for addresses and sizes when creating Shared Memory objects
+    static const u32 RequiredAlignment = 0x1000;
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.h]: This is just PAGE_SIZE

**Comment by Subv** [comment]
Updated

File: src/core/hle/kernel/shared_memory.h [hunk 2]
```diff
@@ -53,6 +53,13 @@ class SharedMemory final : public Object {
     ResultCode Map(VAddr address, MemoryPermission permissions, MemoryPermission other_permissions);
 
     /**
+     * Unmaps a shared memory block from the specified adress in system memory
```
Comment (bunnei) [inline src/core/hle/kernel/shared_memory.h]: Typo, *address

File: src/core/hle/svc.cpp [hunk 3]
```diff
@@ -175,13 +177,28 @@ static ResultCode MapMemoryBlock(Handle handle, u32 addr, u32 permissions, u32 o
     case MemoryPermission::WriteExecute:
     case MemoryPermission::ReadWriteExecute:
     case MemoryPermission::DontCare:
-        shared_memory->Map(addr, permissions_type,
+        return shared_memory->Map(addr, permissions_type,
                 static_cast<MemoryPermission>(other_permissions));
         break;
```
Comment (bunnei) [inline src/core/hle/svc.cpp]: The `break` is now unnecessary

File: src/core/hle/svc.cpp [hunk 4]
```diff
@@ -765,7 +782,15 @@ static s64 GetSystemTick() {
 static ResultCode CreateMemoryBlock(Handle* out_handle, u32 addr, u32 size, u32 my_permission,
         u32 other_permission) {
     using Kernel::SharedMemory;
-    // TODO(Subv): Implement this function
+
+    if (size % Memory::PAGE_SIZE != 0)
+        return ResultCode(ErrorDescription::MisalignedSize, ErrorModule::OS, ErrorSummary::InvalidArgument, ErrorLevel::Usage);
+
+    // Return E0A01BF5 if the address is not in the application's heap
+    // return ResultCode(ErrorDescription::InvalidAddress, ErrorModule::OS, ErrorSummary::InvalidState, ErrorLevel::Usage);
```
Comment (bunnei) [inline src/core/hle/svc.cpp]: ?

**Comment by bunnei** [comment]
Formal request for additional code reviews. I plan on having this one merged by the end of the week if I do not hear from anyone else.

**Comment by neobrain** [comment]
Hi, this is neobot, using neobrain's account. I'm keeping an archive of versions of this PR:

2016-01-14T16:29:50Z: https://github.com/citra-emu/citra/compare/6a261e825c0c60e60038c8093f2da53845b70bf7...Subv:d90d5a0ee6b9c08baacd56cb88159d20bbfdb2f0

**Comment by Subv** [comment]
Updated

**Comment by bunnei** [comment]
LGTM
