### PR TITLE
bootmanager: fix memory leaks when loading save states

### LINKED ISSUE #5523: Memory Leak with Savestate Loading
TL;DR: The binary_iarchive doesn't seem to be fully emptying its buffer on load. I've compiled Citra myself and tried a few things but couldn't get it to fully empty.

Here's my citra about for versioning:
citra
I checked if there were any changes in savestates with the recent canary build, and there wasn't so I didn't bother with that.

Seeing that there was savestate functionality newly added, I was excited to be able to do RNG manipulation for SMT: Strange Journey Redux speedrun routing. Unfortunately, state loading will move the memory address of the RNG values I had found. When I tried to search for it again with a constant value next to the RNG, I came up with increasingly more signatures for each load.
No savestate loads:
no load
One savestate load:
one load
Five savestate loads:
five load
After enough loads, Citra starts to slow down and eventually crashes.
Interestingly enough, that signature is the exact point where the leak starts. If it matters, that location starts at 0x003a513c in 3DS memory (verified on console hardware).

I then built and compiled Citra myself to see if I could solve the issue myself. I took memory snapshots before and after a savestate load in Visual Studio:
memory diff
and inspecting that extra 50MB I found the structure that's using it inside of the System::LoadState() function:
memory diff 2
Unfortunately I have no experience with C++ Boost libraries so I have no idea how I could empty the buffer of the stream / archive, even if that is the problem. I tried emptying the stringstream with sstream.str("");, but that did nothing. Everything else I tried either did nothing or crashed.
What might have to happen is to have serialization done using a different library, but who knows if that would even fix it.

### PR DESCRIPTION
**Pull request by liushuyu**
This Pull Request should fix #5523.

After analyzing the memory leaks report generated by the address sanitizer, it seems like the memory leaks were originated from https://github.com/citra-emu/citra/blob/3f13e1cc2419fac837952c44d7be9db78b054a2f/src/citra_qt/bootmanager.cpp#L449-L451.

The fix is simply to add a destructor to the `GLContext` in the `bootmanager`.

After the fix, the memory leaks report no longer shows this particular memory leak anymore.

Note that, during testing, the `citra-qt` crashed once for reasons unknown. I wasn't able to reproduce this crash despite ~20 more attempts. I suggest when testing this change, try to abuse the save state system as much as possible to see if you can reproduce the crash.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5644)

### CODE REVIEW

File: src/citra_qt/bootmanager.cpp [hunk 1]
```diff
@@ -469,3 +471,8 @@ void GLContext::MakeCurrent() {
 void GLContext::DoneCurrent() {
     context->doneCurrent();
 }
+
+GLContext::~GLContext() {
+    delete surface;
```
Comment (lioncash) [inline src/citra_qt/bootmanager.cpp:476]: Maybe just use a unique_ptr for both `context` and `surface` so this is done automatically

Comment (liushuyu) [reply src/citra_qt/bootmanager.cpp:476]: Good idea! I will try that.

Comment (liushuyu) [reply src/citra_qt/bootmanager.cpp]: Now using smart pointers.

File: src/citra_qt/bootmanager.h [hunk 2]
```diff
@@ -36,8 +36,8 @@ class GLContext : public Frontend::GraphicsContext {
     void DoneCurrent() override;
 
 private:
-    QOpenGLContext* context;
-    QOffscreenSurface* surface;
+    std::unique_ptr<QOpenGLContext> context;
```
Comment (zhaowenlan1779) [inline src/citra_qt/bootmanager.h:39]: `<memory>` should be included.

**Review by zhaowenlan1779 — APPROVED** [review]

File: src/citra_qt/bootmanager.h (hunk 2 above)
Comment (liushuyu) [reply src/citra_qt/bootmanager.h:40]: Addressed. Since the changes are too small, I just included them in the previous commit.
