### PR TITLE
Handle touch input

### LINKED ISSUE #1437: Touch screen doesn't work on touch screen devices.
This issue arises in Qt and GLFW (and the new SDL2 frontend).

On my Windows 10 tablet, a tap is registered as a click and release of the mouse that happens so quickly `EmuWindow::TouchPressed` then `EmuWindow::TouchReleased` are called in quick succession by `EmuWindow::PollEvents` before `Service::HID::Update` runs.

A suggested fix is for `EmuWindow::GetTouchState` to return a vector of changes since last being called. `Service::HID::Update` can then add multiple `TouchDataEntry`s to the ring buffer.

### PR DESCRIPTION
**Pull request by NeatNit**
Fixes #1437.

In both SDL and Qt, this will fix how Citra behaves when it's interacted with using a touchscreen.

In Qt only, using multiple fingers (multi-touch) will make the average position of them be sent to the emulation, making it behave exactly like a real 3DS. In SDL, this is trickier to implement, so what happens instead is that the last finger to move is detected. This doesn't really matter, because users shouldn't be using multi-touch in the first place.

In the process, it improves some mouse input code (DRY), and fixes a minor bug where dragging the mouse from the touchscreen to the left of the emulator window or above it would make the touch be registered at the right or bottom of the touchscreen.

I've tested on a Windows 10 laptop with a built-in touchscreen.

This is my first time using C++ so I'm all ears for what can be done better!

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/4310)

### CODE REVIEW

File: src/citra_qt/bootmanager.h [hunk 1]
```diff
@@ -130,6 +131,12 @@ class GRenderWindow : public QWidget, public EmuWindow {
     void mouseMoveEvent(QMouseEvent* event) override;
     void mouseReleaseEvent(QMouseEvent* event) override;
 
+    void touchBeginEvent(QTouchEvent* event);
```
Comment (jroweboy) [inline src/citra_qt/bootmanager.h]: Style: capitalize the first letter of methods that you add that aren't overriding a base class

File: src/citra/emu_window/emu_window_sdl2.cpp [hunk 2]
```diff
@@ -41,6 +41,39 @@ void EmuWindow_SDL2::OnMouseButton(u32 button, u8 state, s32 x, s32 y) {
...
+
+void EmuWindow_SDL2::OnFingerDown(SDL_FingerID finger, float x, float y) {
+    // To do: keep track of multitouch using the fingerID and a dictionary of some kind
+    // This isn't critical because the best we can do when we have that is to average them, like the
+    // 3DS does
+
+    int px, py;
+    TouchToPixelPos(x, y, &px, &py);
+
+    TouchPressed((unsigned)std::max(px, 0), (unsigned)std::max(py, 0));
```
[the remark this answers is not in the document]
Comment (NeatNit) [reply src/citra/emu_window/emu_window_sdl2.cpp]: Are you sure? https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md#general-rules

> Avoid the use of C-style casts and instead prefer C++-style `static_cast` and `reinterpret_cast`. Try to avoid using `dynamic_cast`. Never use `const_cast`. ***The only exception to this rule is for casting between two numeric types, where C-style casts are encouraged for brevity and readability.***

[the remark this answers is not in the document]
Comment (FearlessTobi) [reply src/citra/emu_window/emu_window_sdl2.cpp]: We should change the document :P We always use static_cast in such a case.

File: src/citra/emu_window/emu_window_sdl2.cpp [hunk 3]
```diff
@@ -178,11 +211,25 @@ void EmuWindow_SDL2::PollEvents() {
...
-            OnMouseMotion(event.motion.x, event.motion.y);
+            // ignore if it came from touch
+            if (event.button.which != SDL_TOUCH_MOUSEID)
+                OnMouseMotion(event.motion.x, event.motion.y);
             break;
         case SDL_MOUSEBUTTONDOWN:
         case SDL_MOUSEBUTTONUP:
-            OnMouseButton(event.button.button, event.button.state, event.button.x, event.button.y);
+            // ignore if it came from touch
+            if (event.button.which != SDL_TOUCH_MOUSEID)
```
[the remark this answers is not in the document]
Comment (NeatNit) [reply src/citra/emu_window/emu_window_sdl2.cpp]: Does it? It's just a function call to `OnMouseMotion`.

File: src/citra_qt/bootmanager.cpp [hunk 4]
```diff
@@ -229,12 +236,71 @@ void GRenderWindow::mouseMoveEvent(QMouseEvent* event) {
...
+            x += tp.pos().x();
+            y += tp.pos().y();
+        }
+    }
+
+    x /= activePoints;
+    y /= activePoints;
+
+    // Copied from mouseMoveEvent:
+    qreal pixelRatio = windowPixelRatio();
```
[the remark this answers is not in the document]
Comment (NeatNit) [reply src/citra_qt/bootmanager.cpp]: this was from the mouse events, should I fix it there as well? or should I actually split it off into a separate function, since it's used like 4 times?

File: src/citra_qt/bootmanager.cpp [hunk 5]
```diff
@@ -229,12 +236,71 @@ void GRenderWindow::mouseMoveEvent(QMouseEvent* event) {
...
     else if (event->button() == Qt::RightButton)
         InputCommon::GetMotionEmu()->EndTilt();
 }
 
+void GRenderWindow::touchBeginEvent(QTouchEvent* event) {
+    auto points = event->touchPoints();
+    auto tp = points.first(); // there should only be 1 point in TouchBegin
+    auto pos = tp.pos();
+
+    // Copied from mousePressEvent:
```
[the remark this answers is not in the document]
Comment (NeatNit) [reply src/citra_qt/bootmanager.cpp]: oh. yes.

issue is it's used in mouse events as well, and what's more, touch produces float `QPointF` while mouse produces int `QPoint`.

File: src/citra_qt/bootmanager.cpp [hunk 6]
```diff
@@ -229,12 +236,70 @@ void GRenderWindow::mouseMoveEvent(QMouseEvent* event) {
...
+    qreal pixelRatio = windowPixelRatio();
+    this->TouchPressed(static_cast<unsigned>(pos.x() * pixelRatio),
+                       static_cast<unsigned>(pos.y() * pixelRatio));
+}
+
+void GRenderWindow::TouchUpdateEvent(QTouchEvent* const event) {
```
Comment (lioncash) [inline src/citra_qt/bootmanager.cpp]: By const pointer, I had meant `const QTouchEvent*`. I guess I should have been more clear with `pointer-to-const` instead.

File: src/citra_qt/bootmanager.cpp [hunk 7]
```diff
@@ -229,12 +236,70 @@ void GRenderWindow::mouseMoveEvent(QMouseEvent* event) {
...
+    if (event->source() == Qt::MouseEventSynthesizedBySystem)
+        return; // touch input is handled in TouchEndEvent
+
     if (event->button() == Qt::LeftButton)
         this->TouchReleased();
     else if (event->button() == Qt::RightButton)
         InputCommon::GetMotionEmu()->EndTilt();
 }
 
+void GRenderWindow::TouchBeginEvent(QTouchEvent* const event) {
```
Comment (lioncash) [inline src/citra_qt/bootmanager.cpp]: Ditto with regards to pointer-to-const.

File: src/citra_qt/bootmanager.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (lioncash) [reply src/citra_qt/bootmanager.cpp]: This is trivially resolvable with something along the lines of:

```cpp
template <typename T>
void ScaledTouch(const T& point) {
    static_assert(std::is_same_v<T, QTouchEvent::TouchPoint> ||
                  std::is_same_v<T, QMouseEvent>);

    const qreal pixel_ratio = windowPixelRatio();
    const auto pos = point.pos();

    TouchPressed(static_cast<u32>(pos.x() * pixel_ratio),
                 static_cast<u32>(pos.y() * pixel_ratio));
}
```

Where auto will deduce the type automatically, depending on the `T` given.

File: src/citra_qt/bootmanager.cpp [hunk 8]
```diff
@@ -229,12 +236,70 @@ void GRenderWindow::mouseMoveEvent(QMouseEvent* event) {
...
+    x /= active_points;
+    y /= active_points;
+
+    // Copied from mouseMoveEvent:
+    qreal pixelRatio = windowPixelRatio();
+    this->TouchMoved(std::max(static_cast<unsigned>(x * pixelRatio), 0u),
+                     std::max(static_cast<unsigned>(y * pixelRatio), 0u));
+}
+
+void GRenderWindow::TouchEndEvent(QTouchEvent* const event) {
```
Comment (lioncash) [inline src/citra_qt/bootmanager.cpp]: Replying to:

> I feel better leaving it in to keep in line with the rest of the events.

Please don't. If it's not currently used, it should be removed; it's unnecessary. If it were a virtual function that required the parameter whether or not it was used, it would be a different story.

File: src/citra/emu_window/emu_window_sdl2.cpp [hunk 9]
```diff
@@ -41,6 +41,35 @@ void EmuWindow_SDL2::OnMouseButton(u32 button, u8 state, s32 x, s32 y) {
...
+
+    touch_x *= w;
+    touch_y *= h;
+
+    // add 0.5 to have .99992 round up instead of down. These will always be near-integers.
+    return {static_cast<int>(touch_x + 0.5), static_cast<int>(touch_y + 0.5)};
+}
+
+void EmuWindow_SDL2::OnFingerDown(float x, float y) {
+    // To do: keep track of multitouch using the fingerID and a dictionary of some kind
```
Comment (FearlessTobi) [inline src/citra/emu_window/emu_window_sdl2.cpp]: `TODO(yournamehere):`

Comment (NeatNit) [reply src/citra/emu_window/emu_window_sdl2.cpp]: Done.

**Comment by NeatNit** [comment]
Sorry for the giant mess this was. I'm pretty sure it's all good now.

**Comment by jroweboy** [comment]
did you test that this works in and not in single window mode?

**Comment by NeatNit** [comment]
> did you test that this works in and not in single window mode?

I did now! 😅 It works perfectly in both cases.

File: src/citra/emu_window/emu_window_sdl2.cpp [hunk 10]
```diff
@@ -41,6 +41,35 @@ void EmuWindow_SDL2::OnMouseButton(u32 button, u8 state, s32 x, s32 y) {
...
 }
 
+std::pair<unsigned, unsigned> EmuWindow_SDL2::TouchToPixelPos(float touch_x, float touch_y) const {
+    int w, h;
+    SDL_GetWindowSize(render_window, &w, &h);
+
+    touch_x *= w;
+    touch_y *= h;
+
+    return {static_cast<unsigned>(std::max(std::round(touch_x), 0.0f)),
```
Comment (B3n30) [inline src/citra/emu_window/emu_window_sdl2.cpp]: I'm not sure, but wouldn't it be better to `std::max(static_cast<unsigned>(std::round(touch_x)), 0)` ?

Comment (NeatNit) [reply src/citra/emu_window/emu_window_sdl2.cpp]: No. This was the bug I mentioned in my edited description:

> ... fixes a minor bug where dragging the mouse from the touchscreen to the left of the emulator window or above it would make the touch be registered at the right or bottom of the touchscreen.

`touch_x` can be negative - which is the whole reason the `std::max` is there - but if we cast it to `unsigned` it will become a very large positive.

**Comment by zhaowenlan1779** [comment]
For the record, this PR is pushed to master at 4ee914c7a8c405775a4e2e3d48a398bd7aa5113e
