### PR TITLE
Threading: Reworked the way our scheduler works.

### LINKED ISSUE #2026: Pokemon Alpha Sapphire-Black screen depending on the save file language
So as i downloaded the latest nightly that has CRO implemented i put a save file for Pokemon Alpha Sapphire in the right folder and started the game.The game starts to the main menu(where i see my save) and when i click to load my game save screen goes black.So i found the fix to change save file language to German and i did.And the crash is fixed i can now play the game.My question is what is the difference between English and German version,i mean that's just the translation,right?And the Log is a little different for both German and English.

German log: http://pastebin.com/0byUsgYC
English log: http://pastebin.com/8PgqhJYG

My specs are:
i5 4200U
4Gb DDr3
GT740M
Windows 10 64-bit

Maybe there is an issue in shared_font.bin or something like that.What do you guys think what is the issue?
P.S. The issue doesn't appear on the Pokemon ROM hacks like star saphhire only on the original game.

[0011c500(eng).zip](https://github.com/citra-emu/citra/files/442277/0011c500.eng.zip)
[0011c500(german).zip](https://github.com/citra-emu/citra/files/442278/0011c500.german.zip)

### LINKED ISSUE #2028: Pokemon alpha sapphire pokecenter freeze
i have been having this problem with the unofficial build and now that it is official i am posting it here. as i have only experience this freeze at the pokemon center, it may be related to other freezes found this game and omega ruby.
thee freeze occurs anything you try to enter a pokecenter with a female character, ie when playing as May.screen shots here

screenshot 11

for console log 
http://pastebin.com/MUQUUtxN

i am using master build , git commit 3f515c0 

for steps ;
create or load a save with the female trainers.
go to the nearest pokecenter 
try entering.
it would freeze during the blacking out sequence, when the pokeball inner circle almost touches the head of your trainer.
PC specs
Intel core i5 4210u @ 2.4ghz ~ 2.7ghz
nvidia geforce 840m 2gb
6 gb ddr3 ram

i dont know how i can get more info for the issue report, it does not crash so no backtrace.

### LINKED ISSUE #2041: Pokemon Omega Ruby & Alpha Sapphire Issues
Hey guys, now that CRO has been merged, Pokemon is now officially supported by Citra (_hears sighs of developers_).

Seriously though, there are a couple of issues with Pokemon:

1) Frequently in the game, there are a lot of black lines that appear and possibly, some depth issues?

2) The game crashes frequently. Is this still missing areas within CRO implementation? Or is this a separate issue within Citra? Also, the crashes don't appear to happen at consistent points in the game. ie sometimes it will crash in the beginning. Once replayed, it will continue passed that point and might crash at another random point in the game. The crashing appears to be completely random.

To replicate, open Pokemon OR or AS and play the first 5 minutes of the game. You will see what I'm talking about.

Specs: 
Windows 7
i7 (3.4ghz)
8gb RAM
Nvidia

Note: This is different to #2026 and #2028 as those crashes occur at specific points in the game. Mine are random it seems.
pokemon issue 1

Enjoy :)

### LINKED ISSUE #2091: Zelda: ALBW - Savegame doesn't load properly on interpreter
(Reported by PPLToast on IRC, verified by myself.)
Version tested: 8bf09b5302dc7717477f6c3b5c1f0ea8f2c80717

This save game [000ec400.zip](https://github.com/citra-emu/citra/files/479228/000ec400.zip) loads normally when using the CPU JIT. When using the interpreter, it loads as if you had 999 rupees, all inventory items and no discovered weather vanes or map markers. Even more strangely, ~~if you save the game none of the changes will be made permanent~~ (EDIT: It wasn't actually saving, see comment below.), if you reload using the JIT, you'll be back to your old items and story position.

PPLToast speculates that this might be a debug feature being activated somehow.

### LINKED ISSUE #2119: Digimon World Re:Digitize Decode - Moflex Video Loading Black screen
This bug seems to be rather a regression but I was unable to pinpoint it exactly since I can't seem to find the build where it used to work:

With the current build of Citra, no additional merges, the game will freeze to a black screen when trying to play the intro of the game or when starting a new game. 

This happens in both cases because a .moflex video is about to be loaded. 

In past builds (I really can't tell which one, it's been months)) it was at least possible to skip the intros by pressing start, in spite of the black screen. But now, pressing start would do nothing and the game would simply freeze on starting a new game or starting the game without having a savegame present (Since having a savegame present will skip the first moflex video).

Now I'm not sure what caused that, or whether that is relevant at all, but I wanted to report it.

Unfortunately the log contains no useful information at all, literally nothing, so there's hardly any point pasting it or the black screen. 

Perhaps someone with a deeper understanding of the root of this problem might look into this.
I guess simplied the problem could be summarized to: Moflex Video Loading is freezing the game/emulator to a black screen.

### LINKED ISSUE #2125: Asynchronous file reading softlocks Brunswick Pro Bowling
# Observation

After making two small modifications (see below) to the Citra source that _technically_ should improve Citra's emulation accuracy of the CTROS scheduler, Brunswick Pro Bowling softlocks upon startup in a function called FileRead. This is surprising, since an asynchronous file reading operation seems like a very elementary operation, and it's one of the first things the game is doing to load its resources.
# Analysis

The following outlines the behavior of my (modified) Citra build, which reflects our current understanding of the CTR scheduler:
- The game ships with an `.axf` file in its RomFS that includes full symbol information (function names and parameter list, type information), making analysis of this issue very easy
- FileRead requests a worker thread to read data from a RomFS file by appending a work item to a task queue. The addition of the new item is signaled using a LightEvent (implemented via svcArbitrateAddress), which causes a deschedule of the main thread.
- The worker thread gets scheduled in and finds a new item appended to the task queue, and hence eventually calls FS::File::Read (using svcSendSyncRequest) on a RomFS FS file handle. In (modified) Citra, this causes a deschedule of the worker thread (see the list of modifications to see why; for reference, the file reading operation is executed before the deschedule).
- The main thread is scheduled back in and enters a stationary loop (presumably waiting for the asynchronous file reading operation to complete) without ever calling a system call. It hence never gets scheduled out and hence indefinitely blocks the AppCore, preventing the worker thread from ever getting scheduled back in.
- Note that the worker thread technically has higher priority than the main thread, but this is useless since on the real system the svcSendSyncRequest wouldn't return immediately (since file reading takes some time) but rather block the current thread until the service process replies.

As far as I can tell, this behavior is perfectly in line with what's publicly documented about the cooperative CTROS scheduler, which suggests we are missing a piece of the bigger picture.
# Theories

I considered the following theories to resolve the issue. Unfortunately, most of these seem to have already been proven wrong, and the rest are plain guesses.
- Maybe BPB runs threads on the SysCore? If the worker thread were allowed to run on the SysCore, it could be scheduled in even when the AppCore is blocked. However, the game's exheader suggests it's using the AppCore for the main thread, and the parameters to svcCreateThread suggest it doesn't use SysCore on the helper threads either.
- Maybe BPB uses SysCore slices? It was suggested applications may use [APT:SetApplicationCpuTimeLimit](https://3dbrew.org/wiki/APT:SetApplicationCpuTimeLimit) to use small time slices of the SysCore. This service command doesn't seem to be used in BPB, though.
- Maybe svcSendSyncRequest blocks the entire process from being scheduled in until the request is complete? If this were the case, instead of scheduling in the main thread after the worker thread calls svcSendSyncRequest, the OS would just put all process threads to sleep and schedule in the highest-prioritized process thread (i.e. the worker thread) once the request reply is received. However, testing has indicated that svcSendSyncRequest indeed only puts one process thread to sleep.
- Perhaps the game assumes the svcSyncRequest call is processed early enough by the FS module such that the next thread scheduled in on the AppCore will in fact be the worker thread? Since the FS module runs on the SysCore, it seems unlikely that the sync request is processed quicker than the AppCore reschedule.
# Modifications to the Citra Source

Granted, it's not common to report issues against a modified source tree. In this case, the issue is masked in the official Citra tree by two hacks:
- VBlankCallback calls [Service::HID::Update](https://github.com/citra-emu/citra/blob/58ae94af4c5c7777cab40ebb4f2bc517dd0f9f2c/src/core/hw/gpu.cpp#L546) along the way, which is obviously nonsense. The crucial downside of this hack is that it causes a thread reschedule even when the active application thread has not invoked any system calls.
- svcSendSyncRequest does not cause a thread reschedule in Citra. On the actual 3DS, sync requests take a while to be processed (especially file IO, which may last an eternity in terms of CPU time) and as such (always?) cause the current thread to be unscheduled. In Citra, sync requests are HLEed and finish instantly, and hence the reschedule is omitted. I think triggering the reschedule should be considered a functional property of the system that should hence be emulated, however.

A branch of Citra is available publicly on my fork, see https://github.com/neobrain/citra/tree/issue_2125.
# Relevance
- The underlying issue might be manifesting in other games even without the local changes I made to the Citra tree
- My local changes certainly are steps towards a more faithful scheduler implementation: Issues like this block Citra from becoming a more accurate emulator
- One of the changes I made essentially blocks LLEing system modules, since a sync request cannot be processed by an LLEed system module without a reschedule of the main thread.

### PR DESCRIPTION
**Pull request by Subv**
Threads will now be awakened when the objects they're waiting on are signaled, instead of repeating the WaitSynchronization call every now and then.

The scheduler is now called once after every SVC call, and once after a thread is awakened from sleep by its timeout callback.

This new implementation is based off reverse-engineering of the real kernel.

See [here](https://gist.github.com/Subv/02f29bd9f1e5deb7aceea1e8f019c8f4) for a more detailed description of how the real kernel handles rescheduling.

Fixes #2125 even with @neobrain's changes.
Fixes #2091
Fixes #2119 
Fixes #2028 
Fixes #2026
Fixes #2041

These changes provide a more stable framework for implementing #1904. I actually have an implementation in mind already, following what the real kernel does.

This PR will make it much easier to implement svcReplyAndReceive after #2249 is merged.

### CODE REVIEW

File: src/core/hle/svc.cpp [hunk 1]
```diff
@@ -300,90 +301,113 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-            auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
-            object->AddWaitingThread(Kernel::GetCurrentThread());
-            wait_objects.push_back(object);
+        // Add the thread to each of the objects' waiting threads.
+        for (int i = 0; i < objects.size(); ++i) {
+            ObjectPtr object = objects[i];
+            // Set the index of this object in the mapping of Objects -> index for this thread.
+            thread->wait_objects_index[object->GetObjectId()] = i;
+            object->AddWaitingThread(thread);
+            // TODO(Subv): Perform things like update the mutex lock owner's priority to prevent priority inversion.
```
Comment (Subv) [inline src/core/hle/svc.cpp]: Currently this is done in Kernel::Mutex::ShouldWait, but we might want to move it to a dedicated function that is called from here.

**Comment by Subv** [comment]
I've tested this on a few games (Quell Reflect, Pokemon X, Brunswick Pro Bowling, Xevious, Zelda: A Link Between Worlds) and haven't found any regressions or freezes.

Zelda: Majora's Mask still doesn't let you go past the CirclePadPro screen, but I guess that's related to the IR:USER service instead of a thread scheduling error.

File: src/core/hle/kernel/kernel.cpp [hunk 2]
```diff
@@ -31,13 +31,62 @@ void WaitObject::RemoveWaitingThread(Thread* thread) {
...
+    if (waiting_threads.empty())
+        return nullptr;
 
-    waiting_threads.clear();
+    auto candidate_threads = waiting_threads;
 
-    HLE::Reschedule(__func__);
+    // Eliminate all threads that are waiting on more than one object, and not all of them are ready
+    candidate_threads.erase(std::remove_if(candidate_threads.begin(), candidate_threads.end(), [](SharedPtr<Thread> thread) -> bool {
+        for (auto object : thread->wait_objects)
```
Comment (lioncash) [inline src/core/hle/kernel/kernel.cpp]: You can just `return std::any_of(...` here

File: src/core/hle/kernel/thread.h [hunk 3]
```diff
@@ -125,6 +126,16 @@ class Thread final : public WaitObject {
     void SetWaitSynchronizationOutput(s32 output);
 
     /**
+     * Retrieves the index that this particular object occupies in the list of objects
+     * that the thread passed to WaitSynchronizationN.
+     * It is used to set the output value of WaitSynchronizationN when the thread is awakened.
+     * @param object Object to query the index of.
+     */
+    s32 GetWaitObjectIndex(WaitObject* object) {
```
Comment (lioncash) [inline src/core/hle/kernel/thread.h]: `object` and the function itself can be const-qualified.

File: src/core/hle/svc.cpp [hunk 4]
```diff
@@ -300,90 +301,113 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
+        auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
+        if (object == nullptr)
+            return ERR_INVALID_HANDLE;
+        objects[i] = object;
     }
 
-    SCOPE_EXIT({
-        HLE::Reschedule("WaitSynchronizationN");
-    }); // Reschedule after putting the threads to sleep.
+    // Clear the mapping of wait object indices
```
Comment (lioncash) [inline src/core/hle/svc.cpp]: This doesn't really elaborate on anything that wouldn't be obvious with the line below this.

File: src/core/hle/svc.cpp [hunk 5]
```diff
@@ -300,90 +301,113 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
+    thread->wait_objects_index.clear();
+
+    if (!wait_all) {
+        // Find the first object that is acquireable in the provided list of objects
+        auto itr = std::find_if(objects.begin(), objects.end(), [](const ObjectPtr& object) {
```
Comment (lioncash) [inline src/core/hle/svc.cpp]: This and the below if statement can probably be its own function.

File: src/core/hle/svc.cpp [hunk 6]
```diff
@@ -300,90 +301,113 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-        wait_objects.reserve(handle_count);
+        // Clear the thread's waitlist, we won't use it for wait_all = false
+        thread->wait_objects.clear();
 
-        for (int i = 0; i < handle_count; ++i) {
-            auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
-            object->AddWaitingThread(Kernel::GetCurrentThread());
-            wait_objects.push_back(object);
+        // Add the thread to each of the objects' waiting threads.
+        for (int i = 0; i < objects.size(); ++i) {
```
Comment (lioncash) [inline src/core/hle/svc.cpp]: `size_t` (the usage can be casted).

File: src/core/hle/svc.cpp [hunk 7]
```diff
@@ -300,90 +301,113 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-        // If no handles were passed in, put the thread to sleep only when 'wait_all' is false
-        // NOTE: This should deadlock the current thread if no timeout was specified
-        if (!wait_all) {
-            wait_thread = true;
-        }
+    using ObjectPtr = Kernel::SharedPtr<Kernel::WaitObject>;
+
+    std::vector<ObjectPtr> objects(handle_count);
+
+    for (int i = 0; i < handle_count; ++i) {
```
Comment (lioncash) [inline src/core/hle/svc.cpp]: This can probably just be a function that returns a vector.

File: src/core/hle/svc.cpp [hunk 8]
```diff
@@ -249,27 +249,30 @@ static ResultCode WaitSynchronization1(Handle handle, s64 nano_seconds) {
...
     LOG_TRACE(Kernel_SVC, "called handle=0x%08X(%s:%s), nanoseconds=%lld", handle,
               object->GetTypeName().c_str(), object->GetName().c_str(), nano_seconds);
 
-    HLE::Reschedule(__func__);
-
-    // Check for next thread to schedule
     if (object->ShouldWait()) {
 
+        if (nano_seconds == 0)
+            return ResultCode(ErrorDescription::Timeout, ErrorModule::OS,
```
Comment (lioncash) [inline src/core/hle/svc.cpp]: Should probably brace this, since the body traverses multiple lines to prevent the potential for a dead if-statement if refactoring happens in the future.

**Comment by yuriks** [comment]
This does not fix #2091. That issue is not about the deadlock when creating a new game, it's about the savegame loading with the wrong player data.

**Comment by yuriks** [comment]
We'll, I'll be fucked. This actually *does* fix the savegame loading incorrectly in #2091.

File: src/core/hle/svc.cpp [hunk 9]
```diff
@@ -249,27 +249,30 @@ static ResultCode WaitSynchronization1(Handle handle, s64 nano_seconds) {
...
         object->AddWaitingThread(thread);
-        Kernel::WaitCurrentThread_WaitSynchronization({object}, false, false);
+        thread->status = THREADSTATUS_WAIT_SYNCH;
 
         // Create an event to wake the thread up after the specified nanosecond delay has passed
         thread->WakeAfterDelay(nano_seconds);
 
-        // NOTE: output of this SVC will be set later depending on how the thread resumes
-        return HLE::RESULT_INVALID;
+        // Note: The output of this SVC will be set to RESULT_SUCCESS if the thread resumes due to a signal in one of its wait objects.
```
Comment (wwylele) [inline src/core/hle/svc.cpp]: "one of its wait objects." should be just "its wait object"

**Comment by yuriks** [comment]
Tested on all my other games, no regressions. Apart from the ALBW fix, Pokemon OR does not lock up after exiting the truck after the intro anymore. I can play the game normally. Pokemon Y still freezes after the intro and Bravely Default still freezes if you change the audio language.

File: src/core/hle/svc.cpp (hunk 1 above)
Comment (wwylele) [inline src/core/hle/svc.cpp]: ^ This comment should go into the TODO, otherwise we will forget it is in `Kernel::Mutex::ShouldWait` later

File: src/core/hle/svc.cpp [hunk 10]
```diff
@@ -300,90 +301,113 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
+                          ErrorSummary::StatusChanged,
+                          ErrorLevel::Info);
+    } else {
+        bool all_available = std::all_of(objects.begin(), objects.end(), [](const ObjectPtr& object) {
+            return !object->ShouldWait();
+        });
+        if (all_available) {
+            // We can acquire all objects right now, do so.
+            for (auto object : objects)
+                object->Acquire();
```
Comment (wwylele) [inline src/core/hle/svc.cpp]: Probably a regression on https://github.com/citra-emu/citra/issues/1308 ?

File: src/core/hle/svc.cpp [hunk 11]
```diff
@@ -1148,6 +1172,7 @@ void CallSVC(u32 immediate) {
     if (info) {
         if (info->func) {
             info->func();
+            HLE::Reschedule(__func__);
```
Comment (wwylele) [inline src/core/hle/svc.cpp]: According to https://gist.github.com/Subv/02f29bd9f1e5deb7aceea1e8f019c8f4, not all `WaitSynchronization1` will cause Reschedule, no?

File: src/core/hle/kernel/thread.h [hunk 12]
```diff
@@ -154,16 +165,16 @@ class Thread final : public WaitObject {
 
     VAddr tls_address; ///< Virtual address of the Thread Local Storage of the thread
 
-    bool waitsynch_waited; ///< Set to true if the last svcWaitSynch call caused the thread to wait
-
     /// Mutexes currently held by this thread, which will be released when it exits.
     boost::container::flat_set<SharedPtr<Mutex>> held_mutexes;
 
     SharedPtr<Process> owner_process;                ///< Process that owns this thread
     std::vector<SharedPtr<WaitObject>> wait_objects; ///< Objects that the thread is waiting on
```
Comment (wwylele) [inline src/core/hle/kernel/thread.h]: Needs to document about the usage when `wait_all = false`. Also Needs a small function like `bool IsWaitingAll() { return !wait_objects.empty();}`. A single `wait_objects.empty()` floating around is really hard to read.

File: src/core/hle/svc.cpp (hunk 10 above)
Comment (Subv) [inline src/core/hle/svc.cpp]: No, the behavior here didnt Change much.

It will check ShouldWait for all objects first (And it will be true for all of the semaphores in that test during the last WaitSynchN call), then acquire them all in sequence

File: src/core/hle/svc.cpp (hunk 11 above)
Comment (Subv) [inline src/core/hle/svc.cpp]: Indeed, but that is a big change in itself, I'll add a TODO and fix the reschedule conditions in my next PR.

**Comment by Romsstar** [comment]
This fixed #2119 ,
thanks, much appreciated :)

**Comment by Subv** [comment]
There appears to be a bug in our thread priority boosting code, the priority of a thread will be reset to its nominal priority when it is scheduled back, however, this conflicts with manual calls to svcSetThreadPriority.

We should make a test to verify whether the thread priority is indeed reset after each schedule.
Are we sure we should be doing priority boosting?
Pinging @bunnei

File: src/core/hle/kernel/kernel.cpp [hunk 13]
```diff
@@ -31,13 +31,61 @@ void WaitObject::RemoveWaitingThread(Thread* thread) {
...
+    // Remove the threads that are ready or already running from our waitlist
+    waiting_threads.erase(std::remove_if(waiting_threads.begin(), waiting_threads.end(), [](const SharedPtr<Thread>& thread) -> bool {
+        return thread->status == THREADSTATUS_RUNNING || thread->status == THREADSTATUS_READY;
+    }), waiting_threads.end());
+
+    if (waiting_threads.empty())
+        return nullptr;
 
-    waiting_threads.clear();
+    auto candidate_threads = waiting_threads;
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.cpp]: This algorithm will cause frequent allocations, does a lot of unnecessary checks. The "manual" version is shorter, faster and imo easier to understand:

```
Thread* candidate = nullptr;
int candidate_priority = 0x40; // Do we have a MAX_PRIORITY constant?

for (Thread* t : waiting_threads) {
    if (t->current_priority > candidate_priority) {
        continue;
    }
    bool ready_to_run = std::none_of(t->wait_objects.begin(), t->wait_object.end(), [](const WaitObject* object) {
        return object->ShouldWait();
    };
    if (ready_to_run) {
        candidate = t;
        candidate_priority = t->current_priority;
    }
}

return candidate;
```

File: src/core/hle/kernel/kernel.cpp [hunk 14]
```diff
@@ -40,24 +40,23 @@ SharedPtr<Thread> WaitObject::GetHighestPriorityReadyThread() {
     if (waiting_threads.empty())
         return nullptr;
 
-    auto candidate_threads = waiting_threads;
+    SharedPtr<Thread> candidate = nullptr;
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.cpp]: It's fine to use a plain pointer here since I think you'd be holding the scheduler lock while in here, right? Saves on a bunch of refcount increment/decrements.

File: src/core/hle/kernel/thread.cpp [hunk 15]
```diff
@@ -619,14 +536,6 @@ void Reschedule() {
 
     HLE::DoneRescheduling();
 
-    // Don't bother switching to the same thread.
-    // But if the thread was waiting on objects, we still need to switch it
-    // to perform PC modification, change state to RUNNING, etc.
-    // This occurs in the case when an object the thread is waiting on immediately wakes up
-    // the current thread before Reschedule() is called.
-    if (next == cur && (next == nullptr || next->waitsynch_waited == false))
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Can `next == cur` never happen anymore, or why did you remove it? If it's impossible then add an assert.

File: src/core/hle/kernel/thread.h [hunk 16]
```diff
@@ -154,16 +174,20 @@ class Thread final : public WaitObject {
...
     boost::container::flat_set<SharedPtr<Mutex>> held_mutexes;
 
     SharedPtr<Process> owner_process;                ///< Process that owns this thread
-    std::vector<SharedPtr<WaitObject>> wait_objects; ///< Objects that the thread is waiting on
+
+    /// Objects that the thread is waiting on.
+    /// This is only populated when the thread should wait for all the objects to become ready.
+    std::vector<SharedPtr<WaitObject>> wait_objects;
+
+    std::unordered_map<int, s32> wait_objects_index; ///< Mapping of Object ids to their position in the last waitlist that this object waited on.
```
Comment (yuriks) [inline src/core/hle/kernel/thread.h]: flat_map probably a better choice

File: src/core/hle/svc.cpp [hunk 17]
```diff
@@ -249,27 +249,33 @@ static ResultCode WaitSynchronization1(Handle handle, s64 nano_seconds) {
...
 
     LOG_TRACE(Kernel_SVC, "called handle=0x%08X(%s:%s), nanoseconds=%lld", handle,
               object->GetTypeName().c_str(), object->GetName().c_str(), nano_seconds);
 
-    HLE::Reschedule(__func__);
-
-    // Check for next thread to schedule
     if (object->ShouldWait()) {
 
+        if (nano_seconds == 0) {
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Flip this to `nano_seconds != 0` so you don't need to duplicate the return.

File: src/core/hle/svc.cpp [hunk 18]
```diff
@@ -283,8 +289,6 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
     bool wait_thread = !wait_all;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: I think this is unused now

File: src/core/hle/svc.cpp [hunk 19]
```diff
@@ -283,8 +289,6 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
     int handle_index = 0;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Also unused

File: src/core/hle/svc.cpp [hunk 20]
```diff
@@ -300,90 +304,117 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-            }
-        }
-    } else {
-        // If no handles were passed in, put the thread to sleep only when 'wait_all' is false
-        // NOTE: This should deadlock the current thread if no timeout was specified
-        if (!wait_all) {
-            wait_thread = true;
-        }
+    using ObjectPtr = Kernel::SharedPtr<Kernel::WaitObject>;
+
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Unnecessary newline

File: src/core/hle/svc.cpp [hunk 21]
```diff
@@ -300,90 +304,117 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-        std::vector<SharedPtr<Kernel::WaitObject>> wait_objects;
-        wait_objects.reserve(handle_count);
+        // No objects were ready to be acquired, prepare to suspend the thread.
 
-        for (int i = 0; i < handle_count; ++i) {
-            auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
-            object->AddWaitingThread(Kernel::GetCurrentThread());
-            wait_objects.push_back(object);
+        // If a timeout value of 0 was provided, just return the Timeout error code instead of suspending the thread.
+        if (nano_seconds == 0) {
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Same deal, flip the condition to avoid duplicating the timeout.

File: src/core/hle/svc.cpp [hunk 22]
```diff
@@ -300,90 +304,117 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-        Kernel::WaitCurrentThread_WaitSynchronization(std::move(wait_objects), true, wait_all);
+        // Put the thread to sleep
+        thread->status = THREADSTATUS_WAIT_SYNCH;
+
+        // Clear the thread's waitlist, we won't use it for wait_all = false
+        thread->wait_objects.clear();
+
+        // Add the thread to each of the objects' waiting threads.
+        for (size_t i = 0; i < objects.size(); ++i) {
+            ObjectPtr object = objects[i];
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: This can be just a raw pointer

File: src/core/hle/svc.cpp [hunk 23]
```diff
@@ -300,90 +304,117 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-        HLE::Reschedule("WaitSynchronizationN");
-    }); // Reschedule after putting the threads to sleep.
+    // Clear the mapping of wait object indices.
+    // We don't want any lingering state in this map.
+    // It will be repopulated later in the wait_all = false case.
+    thread->wait_objects_index.clear();
 
-    // If thread should wait, then set its state to waiting
-    if (wait_thread) {
+    if (!wait_all) {
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Can you switch the two sides of the branch and remove the negation? They're both about the same size so I don't think there's any reason to keep the not.

File: src/core/hle/svc.cpp [hunk 24]
```diff
@@ -300,90 +304,117 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
-    // Acquire objects if we did not wait...
-    for (int i = 0; i < handle_count; ++i) {
-        auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
+        // Not all objects were available right now, prepare to suspend the thread.
 
-        // Acquire the object if it is not waiting...
-        if (!object->ShouldWait()) {
-            object->Acquire();
+        // If a timeout value of 0 was provided, just return the Timeout error code instead of suspending the thread.
+        if (nano_seconds == 0) {
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: You know the drill.

File: src/core/hle/svc.cpp [hunk 25]
```diff
@@ -300,90 +304,117 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
+
+        // Put the thread to sleep
+        thread->status = THREADSTATUS_WAIT_SYNCH;
 
-            // If this was the first non-waiting object and 'wait_all' is false, don't acquire
-            // any other objects
-            if (!wait_all)
-                break;
+        // Set the thread's waitlist to the list of objects passed to WaitSynchronizationN
+        thread->wait_objects = objects;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Move this to after the for loop and you can then std::move the vector

**Comment by emmauss** [comment]
This fixes #2028.

File: src/citra_qt/debugger/wait_tree.cpp [hunk 26]
```diff
@@ -230,7 +230,7 @@ std::vector<std::unique_ptr<WaitTreeItem>> WaitTreeThread::GetChildren() const {
         list.push_back(std::make_unique<WaitTreeMutexList>(thread.held_mutexes));
     }
     if (thread.status == THREADSTATUS_WAIT_SYNCH) {
-        list.push_back(std::make_unique<WaitTreeObjectList>(thread.wait_objects, thread.wait_all));
+        list.push_back(std::make_unique<WaitTreeObjectList>(thread.wait_objects, thread.IsWaitingAll()));
```
Comment (Subv) [inline src/citra_qt/debugger/wait_tree.cpp]: Any suggestions?

File: src/core/hle/kernel/thread.cpp (hunk 15 above)
Comment (Subv) [inline src/core/hle/kernel/thread.cpp]: It is not possible *right now*, but it will be when we make SendSyncRequest pause the running thread. we want to cause a context Switch in that case too.

File: src/core/hle/kernel/thread.h (hunk 16 above)
Comment (Subv) [inline src/core/hle/kernel/thread.h]: why?

File: src/core/hle/svc.cpp (hunk 22 above)
Comment (Subv) [inline src/core/hle/svc.cpp]: Done

**Comment by Dragios** [comment]
Fixes #2026 as well

File: src/citra_qt/debugger/wait_tree.cpp (hunk 26 above)
Comment (yuriks) [inline src/citra_qt/debugger/wait_tree.cpp]: "IsSleepingOnWaitAll"? I don't have any either. This is kind of a weird one because it doesn't even makes sense in all states either. For example, if the thread isn't sleeping on a WaitSynchN at all it mayb still return true if the list is non-empty.

File: src/core/hle/kernel/thread.cpp (hunk 15 above)
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: That still doesn't really answer why you removed it. If next == cur and you don't need to do the special wait synch setup then you can skip switching the context (this also avoids pointless null -> null reschedules.)

File: src/core/hle/kernel/thread.h (hunk 16 above)
Comment (yuriks) [inline src/core/hle/kernel/thread.h]: The map holds only small number of elements and the keys and values are very small

File: src/core/hle/svc.cpp (hunk 17 above)
Comment (yuriks) [inline src/core/hle/svc.cpp]: At least factor the error code out to a constant then, because it's repeated 4 times in this file.

File: src/core/hle/svc.cpp (hunk 22 above)
Comment (yuriks) [inline src/core/hle/svc.cpp]: ...locally?

File: src/core/hle/svc.cpp [hunk 27]
```diff
@@ -300,90 +302,116 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
 
-        for (int i = 0; i < handle_count; ++i) {
-            auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
-            object->AddWaitingThread(Kernel::GetCurrentThread());
-            wait_objects.push_back(object);
+        // Put the thread to sleep
+        thread->status = THREADSTATUS_WAIT_SYNCH;
+
+        // Add the thread to each of the objects' waiting threads.
+        for (auto object : objects) {
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: auto& (otherwise you're making a copy of the SharedPtr on every iteration)

File: src/core/hle/kernel/thread.cpp (hunk 15 above)
Comment (Subv) [inline src/core/hle/kernel/thread.cpp]: When applying the changes outlined in #2125 (Which are more or less correct, and will be part of my next PR), not performing a context switch in the ```cur == next``` case where ```cur != nullptr && cur->status == THREADSTATUS_READY``` causes a SIGSEGV in ```PriorityBoostStarvedThreads``` because we don't re-add the thread to the ```ready_queue``` and it ends up being empty.

File: src/citra_qt/debugger/wait_tree.cpp (hunk 26 above)
Comment (Subv) [inline src/citra_qt/debugger/wait_tree.cpp]: I'll rename it to IsSleepingOnWaitAll for now, my next PR will add more thread statuses anyways, so we can check for  THREADSTATUS_WAITSYNCH && !wait.empty() inside this function.

File: src/core/hle/kernel/thread.cpp (hunk 15 above)
Comment (Subv) [inline src/core/hle/kernel/thread.cpp]: The case above can happen if the thread was put to sleep for a very short period of time, and awakened before another thread was made to run.

File: src/core/hle/svc.cpp [hunk 28]
```diff
@@ -320,100 +315,90 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
...
         });
-
-        if (itr != objects.end()) {
-            // We found a ready object, acquire it and set the result value
-            ObjectPtr object = *itr;
-            object->Acquire();
-            *out = std::distance(objects.begin(), itr);
+        if (all_available) {
+            // We can acquire all objects right now, do so.
+            for (auto object : objects)
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: oops, auto& here too

File: src/core/hle/svc.cpp (hunk 10 above)
Comment (wwylele) [inline src/core/hle/svc.cpp]: (Sorry for a late test) The test in #1308 ([this](https://github.com/wwylele/ctrhwtest/tree/master/semaphore_acquire_n/source)) hits the ASSERT
```
[   0.345067] Debug <Critical> core/hle/kernel/semaphore.cpp:operator():38: Assertion Failed!
object unavailable!
```

**Comment by wwylele** [comment]
I haven't got time to write and do tests, so I try to do some thought experiment with the code. However, the logic in some circumstances seems unclear (incorrect?) to me:

- say a thread calls `WaitSynchN` with `wait_all=true`, `thread->wait_objects` gets populate. Then it times out and the thread wakes up, with `wait_objects` not cleared (I can't find any code in this path clearing it?). After a while the thread calls `WaitSynch1` and goes into a waiting state again, with `wait_objects` still populated (`WaitSynch1` doesn't clear it either), now the thread is actually in a "waiting for all N objects" state

 - say a thread, A, is holding a mutex, and another two theads, B and C, call `WaitSynch1` on that mutex and go into waiting state. Now thread A releases the mutex, where the code path is: `ReleaseMutex` -> `Mutex::Release` -> `(mutex.cpp) ResumeWaitingThread` -> `WaitObject::WakeupAllWaitingThread` ->
{  `GetHighestPriorityReadyThread` -> returns thread B because of an empty `wait_objects`;  `Mutex::Acquire()`; B resumes; `GetHighestPriorityReadyThread` again -> returns thread C because of an empty `wait_objects`; `Mutex::Acquire()` again -> hits `ASSERT` because B is holding the mutex }

**Comment by Subv** [comment]
@wwylele Both issues should be fixed now with the latest commit.

**Comment by Subv** [comment]
A @yuriks LGTM means this thing is out of RFC state \o/

Now I'd love to get a @wwylele LGTM

File: src/core/hle/kernel/thread.h [hunk 29]
```diff
@@ -215,10 +240,9 @@ void WaitCurrentThread_Sleep();
  * @param wait_objects Kernel objects that we are waiting on
  * @param wait_set_output If true, set the output parameter on thread wakeup (for
  * WaitSynchronizationN only)
- * @param wait_all If true, wait on all objects before resuming (for WaitSynchronizationN only)
  */
 void WaitCurrentThread_WaitSynchronization(std::vector<SharedPtr<WaitObject>> wait_objects,
-                                           bool wait_set_output, bool wait_all);
+                                           bool wait_set_output);
```
Comment (wwylele) [inline src/core/hle/kernel/thread.h]: This function is actually not used any more. We can remove it

**Comment by yuriks** [comment]
You should fix the formatting errors in the build. (Are we testing this on BE for regressions for a while or just merging when it's ready?)

**Comment by wwylele** [comment]
Please testing this on BE for regressions for some days. Actually I have already received potential regression report.

**Comment by bunnei** [comment]
I don't think it hurts to let it marinate on BE for a few days...
