### PR TITLE
Fix svcWaitSynch to correctly acquire wait objects

### LINKED ISSUE #432: Thread scheduling bugs
@Normmatt wrote a threading demo (that of which I have not seen the sourcecode for) that tests scheduling, and ran it against Citra, 3dmoo, and hardware. The results are here -> https://gist.github.com/Normmatt/b0a0440c9f55d1b54664

At first glance Citra looks very wrong... But I'm not sure that is true. It looks like there is simply a bug with new threads being immediately switched to, instead of only being switched to on the next qualifying event. If I move the "begins" to happen first for the Citra log, you get:

<pre>Thread 1 begins
Thread 2 begins
Thread 3 begins
Thread 4 begins
Thread 1, count = 0
Thread 2, count = 0
Thread 1, count = 1
Thread 2, count = 1
Thread 1, count = 2
Thread 1 ends
Thread 3, count = 0
Thread 2, count = 2
Thread 2 ends
Thread 3, count = 1
Thread 4, count = 0
Thread 3, count = 2
Thread 3 ends
Thread 4, count = 1</pre>

Which is actually pretty darn close to hardware - so it's probably just a simple fix. I'm going to take the action to go through thread scheduling after @Subv makes his upcoming timing changes, and make it more identical to hardware.

### PR DESCRIPTION
**Pull request by bunnei**
This changes how we emulate svcWaitSynch to ensure that wait objects are always acquired by the right thread. My solution with this PR is to always call the SVC when a thread is awoken until conditions are satisfied for it to continue. A side-effect of this is that threads will often be scheduled that are not actually able to run, resulting in unnecessary context switches (this could result in a hopefully minor performance hit). This is because when a wait_object becomes available, all waiting threads will be awoken, so whichever don't acquire the resource will still be scheduled then rescheduled. However, this actually makes our code much simpler/cleaner, as we can get rid of all the state management cruft trying to "predict" the next best thread to run. This fixes #432. I suspect it will fix a lot of games, although I don't own enough games to verify this claim.

Mario Kart 7 now will go in game (NOTE: needs a few other patches that aren't mainline yet):

image

### CODE REVIEW

File: src/core/hle/kernel/thread.cpp [hunk 1]
```diff
@@ -193,8 +192,17 @@ static void SwitchContext(Thread* new_thread) {
...
+        // Cancel any outstanding wakeup events for this thread
+        CoreTiming::UnscheduleEvent(ThreadWakeupEventType, new_thread->callback_handle);
+
         current_thread = new_thread;
 
+        // If the thread was waited by a svcWaitSynch call, step back PC by one instruction to rerun
+        // the SVC when the thread wakes up. This is necessary to ensure that the thread can acquire
+        // the requested wait object(s) before continuing.
+        if (new_thread->waitsynch_waited)
+            new_thread->context.pc -= 4;
```
Comment (Subv) [inline src/core/hle/kernel/thread.cpp]: This troubles me, can SVCs be called from Thumb mode? and if not, could you add a comment clarifying that, please?

File: src/core/hle/kernel/semaphore.cpp [hunk 2]
```diff
@@ -48,13 +48,7 @@ ResultVal<s32> Semaphore::Release(s32 release_count) {
...
     available_count += release_count;
 
-    // Notify some of the threads that the semaphore has been released
-    // stop once the semaphore is full again or there are no more waiting threads
-    while (!ShouldWait() && WakeupNextThread() != nullptr) {
-        Acquire();
-    }
-
-    HLE::Reschedule(__func__);
+    WakeupAllWaitingThreads();
```
Comment (Subv) [inline src/core/hle/kernel/semaphore.cpp]: Note to self, take a closer look to this tomorrow.(@Subv)

File: src/core/hle/kernel/thread.cpp (hunk 1 above)
Comment (Normmatt) [inline src/core/hle/kernel/thread.cpp]: Yes they can and this doesn't take that into account.

**Comment by MoochMcGee** [comment]
360 noscope instamerge

File: src/core/hle/kernel/semaphore.cpp (hunk 2 above)
Comment (Subv) [inline src/core/hle/kernel/semaphore.cpp]: Done, this is OK

File: src/core/hle/kernel/thread.cpp [hunk 3]
```diff
@@ -193,8 +192,18 @@ static void SwitchContext(Thread* new_thread) {
...
+        CoreTiming::UnscheduleEvent(ThreadWakeupEventType, new_thread->callback_handle);
+
         current_thread = new_thread;
 
+        // If the thread was waited by a svcWaitSynch call, step back PC by one instruction to rerun
+        // the SVC when the thread wakes up. This is necessary to ensure that the thread can acquire
+        // the requested wait object(s) before continuing.
+        if (new_thread->waitsynch_waited)
+            // CPSR flag indicates CPU mode: SVC instruction is 2 bytes for THUMB, 4 bytes for ARM.
+            new_thread->context.pc -= ((new_thread->context.cpsr & (1 << 5)) != 0) ? 2 : 4;
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Wouldn't kill you to add a separate `bool thumb_mode` variable and would make it much more instantly readable.

File: src/core/hle/kernel/kernel.cpp [hunk 4]
```diff
@@ -26,33 +26,19 @@ void WaitObject::AddWaitingThread(SharedPtr<Thread> thread) {
         waiting_threads.push_back(std::move(thread));
 }
 
-void WaitObject::RemoveWaitingThread(Thread* thread) {
+void WaitObject::RemoveWaitingThread(SharedPtr<Thread> thread) {
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.cpp]: What's up with this change? Pointers to kernel objects can be trivially converted to a SharedPtr, so I usually reserved them to places that actually held ownership.

File: src/core/hle/kernel/thread.cpp [hunk 5]
```diff
@@ -163,8 +163,7 @@ static void PriorityBoostStarvedThreads() {
         u64 delta = current_ticks - thread->last_running_ticks;
 
         if (thread->status == THREADSTATUS_READY && delta > boost_timeout) {
-            const s32 priority = std::max(ready_queue.get_first()->current_priority - 1, 0);
-            thread->BoostPriority(priority);
+            thread->BoostPriority(THREADPRIO_USERLAND_MAX);
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Rationale?

File: src/core/hle/result.h [hunk 6]
```diff
@@ -222,6 +222,9 @@ inline bool operator!=(const ResultCode& a, const ResultCode& b) {
 /// The default success `ResultCode`.
 const ResultCode RESULT_SUCCESS(0);
 
+/// An invalid result code that is meant to be overwritten when a thread resumes from waiting
+const ResultCode RESULT_INVALID(0xDEADC0DE);
```
Comment (yuriks) [inline src/core/hle/result.h]: We'd discussed this in the PR this was introduced, and I still think it doesn't belong here and should go in one of the kernel-related headers instead.

**Comment by bunnei** [comment]
Suggestion then? (Since I now use it in function_wrapper.h)

File: src/core/hle/kernel/thread.cpp (hunk 3 above)
Comment (lioncash) [inline src/core/hle/kernel/thread.cpp]: there's also a TBITvariable in armdefs.h that represents `(1 << 5)`

File: src/core/hle/result.h (hunk 6 above)
Comment (yuriks) [inline src/core/hle/result.h]: I think I'd put it in function_wrappers.h, which is where you're using it anyway.

File: src/core/hle/function_wrappers.h [hunk 7]
```diff
@@ -9,11 +9,15 @@
...
 #include "core/memory.h"
 #include "core/hle/hle.h"
+#include "core/hle/result.h"
 
 namespace HLE {
 
 #define PARAM(n)    Core::g_app_core->GetReg(n)
 
+/// An invalid result code that is meant to be overwritten when a thread resumes from waiting
+const ResultCode RESULT_INVALID(0xDEADC0DE);
```
Comment (lioncash) [inline src/core/hle/function_wrappers.h]: Shouldn't this be static?

File: src/core/hle/kernel/thread.cpp [hunk 8]
```diff
@@ -193,8 +194,22 @@ static void SwitchContext(Thread* new_thread) {
...
 
+        // Cancel any outstanding wakeup events for this thread
+        CoreTiming::UnscheduleEvent(ThreadWakeupEventType, new_thread->callback_handle);
+
         current_thread = new_thread;
 
+        // If the thread was waited by a svcWaitSynch call, step back PC by one instruction to rerun
+        // the SVC when the thread wakes up. This is necessary to ensure that the thread can acquire
+        // the requested wait object(s) before continuing.
+		if (new_thread->waitsynch_waited) {
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABS!

File: src/core/hle/svc.cpp [hunk 9]
```diff
@@ -241,7 +249,7 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
         Kernel::GetCurrentThread()->WakeAfterDelay(nano_seconds);
 
         // NOTE: output of this SVC will be set later depending on how the thread resumes
-        return RESULT_INVALID;
+		return HLE::RESULT_INVALID;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABS!

File: src/core/hle/svc.cpp [hunk 10]
```diff
@@ -261,7 +269,7 @@ static ResultCode WaitSynchronizationN(s32* out, Handle* handles, s32 handle_cou
 
     // TODO(bunnei): If 'wait_all' is true, this is probably wrong. However, real hardware does
     // not seem to set it to any meaningful value.
-    *out = wait_all ? 0 : handle_index;
+    *out = handle_count != 0 ? (wait_all ? -1 : handle_index) : 0;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: If handle_count is 0 it sets the index to 0 (aka, an out of bounds index)? Is that right?

**Comment by yuriks** [comment]
LGTM. I think that moving the wait-satisfied checks into the scheduler would be a more flexible and efficient solution, but this is fine for a first implementation which fixes some glaring issues.

File: src/core/hle/svc.cpp (hunk 10 above)
Comment (bunnei) [inline src/core/hle/svc.cpp]: Yes, we in fact have a test for this: https://github.com/citra-emu/hwtests/blob/master/source/tests/kernel/waitsynch.cpp#L371

**Comment by bunnei** [comment]
<Subv> alright, LGTM
<Subv> instamergepls
