### PR TITLE
audio_core\lle\lle.cpp: Add 16 bit and 32 bit read/write callbacks

### LINKED ISSUE #5967: LLE audio is completely broken
Since Canary 2063 when you run any games in LLE audio Citra will crash. HLE audio is unaffected.

### PR DESCRIPTION
**Pull request by SachinVin**
Add 16 bit and 32 bit read/write callbacks, fixes crashing with latest teakra API. Closes #5967

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5968)

### CODE REVIEW

File: src/audio_core/lle/lle.cpp [hunk 1]
```diff
@@ -482,6 +482,18 @@ DspLle::DspLle(Memory::MemorySystem& memory, bool multithread)
     ahbm.write8 = [&memory](u32 address, u8 value) {
         *memory.GetFCRAMPointer(address - Memory::FCRAM_PADDR) = value;
     };
+    ahbm.read16 = [&memory](u32 address) -> u16 {
+        return *memory.GetFCRAMPointer(address - Memory::FCRAM_PADDR);
```
Comment (wwylele) [inline src/audio_core/lle/lle.cpp:486]: this is not right. GetFCRAMPointer returns u8*, and this just extends a single byte to u16

**Review by wwylele — CHANGES_REQUESTED** [review]

File: src/audio_core/lle/lle.cpp (hunk 1 above)
Comment (SachinVin) [reply src/audio_core/lle/lle.cpp]: fixed

**Review by wwylele — APPROVED** [review]
