### PR TITLE
Minor frontend fixes to savestates

### LINKED ISSUE #5373: Save state to oldest slot in fullscreen always overwrite the same slot
I use custom hotkey to _save state to oldest slot_, when play in **fullscreen mode**, it always save state to **the same one slot**, until I exit fullscreen.
For example, I save state at 10:00, 10:01, 10:02, then i exit fullscreen, it should be:
slot 1, (earlier)
slot 2, 10:00
slot 3, 10:01
slot 4, 10:02
but in fact, it is:
slot 1, (earlier)
slot 2, 10:02

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
Please refer to commit descriptions. The second commit aims to 'phase out' the issue that, if still image camera and 'prompt before load' are selected, loading a state would bring up a file selection dialog.

Fixes #5373.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5430)

### CODE REVIEW

File: src/citra_qt/main.cpp [hunk 1]
```diff
@@ -412,10 +412,14 @@ void GMainWindow::InitializeSaveStateMenuActions() {
         ui.menu_Save_State->addAction(actions_save_state[i]);
     }
 
-    connect(ui.action_Load_from_Newest_Slot, &QAction::triggered,
-            [this] { actions_load_state[newest_slot - 1]->trigger(); });
-    connect(ui.action_Save_to_Oldest_Slot, &QAction::triggered,
-            [this] { actions_save_state[oldest_slot - 1]->trigger(); });
+    connect(ui.action_Load_from_Newest_Slot, &QAction::triggered, [this] {
+        UpdateSaveStates();
+        actions_load_state[newest_slot - 1]->trigger();
```
Comment (xperia64) [inline src/citra_qt/main.cpp:417]:
```suggestion
        if (newest_slot != 0 && actions_load_state[newest_slot - 1]->isEnabled())
            actions_load_state[newest_slot - 1]->trigger();
```

**Review by FearlessTobi — APPROVED** [review]
