### PR TITLE
Fix WaitSynchronization

### LINKED ISSUE #469: WaitSynchronizationN
This svc function is completely broken, it will not set the "out" return value properly if the function caused a reschedule, and it will add the calling thread to all the specified objects' waiting_threads member, potentially causing problems with awaking threads multiple times from multiple objects.

This is currently blocking quite a few games

### PR DESCRIPTION
**Pull request by bunnei**
Complete rewrite of WaitSynchronization1/WaitSynchronizationN. Basically, with our previous implementation, WaitSynchronizationN was entirely broken (this PR fixes #469). This required some pretty massive refactoring, which actually greatly simplified a lot of code. This is a very large change, so I would appreciate a pretty in-depth code review (especially for silly C++ mistakes), as well as extensive testing. However, my usual test suite of homebrew and retail works fine. I also wrote a quite extensive addition to hwtests to validate my implementation (that of which now passes), and as such I'm fairly confident that the implementations of these functions are now pretty sufficiently correct (PR for hwtests to follow once I clean it up). Please let me know if you have any interesting ideas for test cases that might break this implementation :) A quick overview of changes:
* Created a WaitObject type for Kernel objects that can wait the current thread via WaitSynchronization, and changed relevant Kernel objects to inherit from it
* Got rid of WaitType's (legacy code from PPSSPP that made no sense here)
* Split up object's WaitSynchronization method into Wait and Aquire methods
* Implemented WaitSynchronizationN with wait_all=true
* Implemented WaitSynchronizationN with wait_all=false (i.e. "select")
* Implemented timeouts with WaitSynchronizationN
* Fixed output values for WaitSynchronizationN if the current thread waited
* Fixed a bug in Mutex
* Fixed several bugs in Event
* ...I'm sure many more things

EDIT: Please don't review commit by commit, some design decisions changed over time :( And sorry, I'm very likely not going to redo the commit history just for this.

### CODE REVIEW

File: src/core/hle/kernel/thread.cpp [hunk 1]
```diff
@@ -247,6 +238,9 @@ static void ThreadWakeupCallback(u64 parameter, int cycles_late) {
         return;
     }
 
+    thread->SetReturnValue(ResultCode(ErrorDescription::Timeout, ErrorModule::OS,
```
Comment (Subv) [inline src/core/hle/kernel/thread.cpp]: I don't think we should be overriding R1 in WaitSynchronization1

File: src/core/hle/kernel/thread.h [hunk 2]
```diff
@@ -95,11 +98,9 @@ class Thread : public Kernel::Object {
 
     s32 processor_id;
 
-    WaitType wait_type;
-    Object* wait_object;
+    std::vector<SharedPtr<WaitObject>> wait_objects;
     VAddr wait_address;
-
-    std::vector<SharedPtr<Thread>> waiting_threads;
+    bool wait_all;
```
Comment (Subv) [inline src/core/hle/kernel/thread.h]: Some comment about this would be nice

**Comment by bunnei** [comment]
@Subv please comment on 20ca956, as this is a change to a fix that you originally proposed (fixes Nintendo Zone and other system titles).

**Comment by Subv** [comment]
Yeah that commit looks good

File: src/core/hle/kernel/kernel.cpp [hunk 3]
```diff
@@ -18,6 +18,42 @@ SharedPtr<Thread> g_main_thread = nullptr;
...
+
+Thread* WaitObject::ReleaseNextThread() {
+    if (waiting_threads.empty())
+        return nullptr;
+
+    auto next_thread = waiting_threads.front();
+    waiting_threads.erase(waiting_threads.begin());
+
+    next_thread->ReleaseWaitObject(this);
+
```
Comment (neobrain) [inline src/core/hle/kernel/kernel.cpp]: redundant empty lines

File: src/core/hle/kernel/kernel.h [hunk 4]
```diff
@@ -58,17 +60,26 @@ class Object : NonCopyable {
...
-        return UnimplementedFunction(ErrorModule::Kernel);
+    bool IsWaitable() const {
+        switch (GetHandleType()) {
+        case HandleType::Session:
+        case HandleType::Event:
+        case HandleType::Mutex:
+        case HandleType::Thread:
+        case HandleType::Semaphore:
+        case HandleType::Timer:
+            return true;
```
Comment (neobrain) [inline src/core/hle/kernel/kernel.h]: a default case should be used here to prevent compiler warnings due to unhandled switch cases.

File: src/core/hle/kernel/thread.cpp [hunk 5]
```diff
@@ -88,19 +83,18 @@ static void ChangeReadyState(Thread* t, bool ready) {
...
-static bool CheckWaitType(const Thread* thread, WaitType type) {
-    return (type == thread->wait_type) && (thread->IsWaiting());
-}
-
-/// Check if a thread is blocking on a specified wait type with a specified handle
-static bool CheckWaitType(const Thread* thread, WaitType type, Object* wait_object) {
-    return CheckWaitType(thread, type) && wait_object == thread->wait_object;
+/// Check if a thread is waiting on a the specified wait object
+static bool CheckWait_WaitObject(const Thread* thread, WaitObject* wait_object) {
+    for (auto itr = thread->wait_objects.begin(); itr != thread->wait_objects.end(); ++itr) {
```
Comment (neobrain) [inline src/core/hle/kernel/thread.cpp]: Why not std::find?

File: src/core/hle/kernel/thread.cpp [hunk 6]
```diff
@@ -261,14 +255,58 @@ void WakeThreadAfterDelay(Thread* thread, s64 nanoseconds) {
...
+    }
+
+    // Remove this thread from the waiting object's thread list
+    wait_object->RemoveWaitingThread(this);
+
+    unsigned index = 0;
+    bool wait_all_failed = false; // Will be set to true if any object is unavailable
+
+    // Iterate through all waiting objects to check availability...
+    for (auto itr = wait_objects.begin(); itr != wait_objects.end(); ++itr) {
```
Comment (neobrain) [inline src/core/hle/kernel/thread.cpp]: And this is why we have `for (auto wait_object : wait_objects | boost::adaptors::indexed)` :P

File: src/core/hle/svc.cpp [hunk 7]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
-            unlock_all = false;
+static Result WaitSynchronizationN(s32* out, Handle* handles, s32 handle_count, bool wait_all, s64 nano_seconds) {
+    bool wait_thread = !wait_all;
+    int handle_index = 0;
+
+    // Check if 'handles' is invalid
+    if (handles == nullptr)
+        return ResultCode(ErrorDescription::InvalidPointer, ErrorModule::Kernel, ErrorSummary::InvalidArgument, ErrorLevel::Permanent).raw;
+
+    // NOTE: on real hardware, there is no nullptr check for 'out' (tested with firmware 4.4). If
```
Comment (neobrain) [inline src/core/hle/svc.cpp]: Probably shouldn't speak about "real hardware" when it's actually about the firmware.

File: src/core/hle/svc.cpp [hunk 8]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
-    if (wait_all && unlock_all) {
-        *out = handle_count;
-        return RESULT_SUCCESS.raw;
-    }
+    // If thread should wait, then set its state to waiting and then reschedule...
+    if (wait_thread) {
 
-    // Check for next thread to schedule
-    HLE::Reschedule(__func__);
+        // Actually wait the current thread on each object if we did end up waiting...
```
Comment (neobrain) [inline src/core/hle/svc.cpp]: Call me stupid, but I find this way of using "wait" extremely confusing, since I don't think "wait" can be used as an active verb.

Also, this whole sentence sounds odd. "Actually wait [..] if we did end up waiting" ?

File: src/core/hle/svc.cpp [hunk 9]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+
+        // Create an event to wake the thread up after the specified nanosecond delay has passed
+        Kernel::WakeThreadAfterDelay(Kernel::GetCurrentThread(), nano_seconds);
+
+        HLE::Reschedule(__func__);
+
+        // NOTE: output of this SVC will be set later depending on how the thread resumes
+    } else {
+        // Acquire objects if we did not end up waiting...
+        for (int i = 0; i < handle_count; i++) {
```
Comment (neobrain) [inline src/core/hle/svc.cpp]: `for (auto& handle : handles)` ?

**Comment by neobrain** [comment]
Mostly LGTM other than a few nitpicks I made. Also feel free to ignore the boost suggestions.

File: src/core/hle/kernel/kernel.h (hunk 4 above)
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: Or rather, the remaining cases should be added explicitly so that it stops complaining (and starts again when we add more items to the enum.)

File: src/core/hle/kernel/address_arbiter.cpp [hunk 10]
```diff
@@ -31,33 +31,37 @@ class AddressArbiter : public Object {
 /// Arbitrate an address
 ResultCode ArbitrateAddress(Handle handle, ArbitrationType type, u32 address, s32 value, u64 nanoseconds) {
     Object* object = Kernel::g_handle_table.GetGeneric(handle).get();
+
     if (object == nullptr)
         return InvalidHandle(ErrorModule::Kernel);
 
+    if (object->GetHandleType() != HandleType::AddressArbiter)
+        return ResultCode(-1); // TODO(bunnei): Check for the real error code on hardware
```
Comment (yuriks) [inline src/core/hle/kernel/address_arbiter.cpp]: This test can be rolled into L33 by using `Get<AddressArbiter>` instead.

File: src/core/hle/kernel/address_arbiter.cpp [hunk 11]
```diff
@@ -31,33 +31,37 @@ class AddressArbiter : public Object {
 /// Arbitrate an address
```
Comment (yuriks) [inline src/core/hle/kernel/address_arbiter.cpp]: I think I got rid of this (completely useless) comment in my own branch, but since you've been looking at this stuff, can you elaborate on what the purpose of the function is?

File: src/core/hle/kernel/event.cpp [hunk 12]
```diff
@@ -25,99 +25,52 @@ class Event : public Object {
...
-        // not block. Not sure if this is correct behavior, but it seems to work.
-        event_caught = true;
-    }
-    evt->waiting_threads.clear();
+    if (evt == nullptr)
+        return InvalidHandle(ErrorModule::Kernel);
+
+    evt->signaled = true;
+
+    bool thread_awoken = evt->ReleaseAllWaitingThreads();
```
Comment (yuriks) [inline src/core/hle/kernel/event.cpp]: This variable seems to be unused.

File: src/core/hle/kernel/event.cpp [hunk 13]
```diff
@@ -25,99 +25,52 @@ class Event : public Object {
...
- * @param handle Handle to event to clear
- * @return Result of operation, 0 on success, otherwise error code
- */
 ResultCode ClearEvent(Handle handle) {
     Event* evt = g_handle_table.Get<Event>(handle).get();
-    if (evt == nullptr) return InvalidHandle(ErrorModule::Kernel);
+    if (evt == nullptr)
+        return InvalidHandle(ErrorModule::Kernel);
+
+    evt->signaled = false;
```
Comment (yuriks) [inline src/core/hle/kernel/event.cpp]: Can't `SignalEvent` and `ClearEvent` be implemented in terms of `SetEventSignalled`?

File: src/core/hle/kernel/event.cpp [hunk 14]
```diff
@@ -25,99 +25,52 @@ class Event : public Object {
...
-/**
- * Changes whether an event is locked or not
- * @param handle Handle to event to change
- * @param locked Boolean locked value to set event
- * @return Result of operation, 0 on success, otherwise error code
- */
-ResultCode SetEventLocked(const Handle handle, const bool locked) {
-    Event* evt = g_handle_table.Get<Event>(handle).get();
-    if (evt == nullptr) return InvalidHandle(ErrorModule::Kernel);
+    evt->signaled = signaled;
```
Comment (yuriks) [inline src/core/hle/kernel/event.cpp]: This doesn't release waiting threads if `signaled` is true. Should it?

File: src/core/hle/kernel/kernel.cpp [hunk 15]
```diff
@@ -18,6 +18,42 @@ SharedPtr<Thread> g_main_thread = nullptr;
 HandleTable g_handle_table;
 u64 g_program_id = 0;
 
+void WaitObject::AddWaitingThread(Thread* thread) {
+    auto itr = std::find(waiting_threads.begin(), waiting_threads.end(), thread);
+    if (itr == waiting_threads.end())
+        waiting_threads.push_back(thread);
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.cpp]: Is a thread waiting twice on the same object a valid thing to happen in a non-bug scenario? If it's already waiting then it supposedly can't really *do* anything that would cause it to wait on the same thing again, could it? If that's the case then maybe this should be converted into some kind of invariant-checking assert. (Nevermind our asserts are completely broken.)

File: src/core/hle/kernel/kernel.cpp [hunk 16]
```diff
@@ -18,6 +18,42 @@ SharedPtr<Thread> g_main_thread = nullptr;
...
+
+    next_thread->ReleaseWaitObject(this);
+    
+
+    return next_thread;
+}
+
+bool WaitObject::ReleaseAllWaitingThreads() {
+    bool res = false;
+    auto waiting_threads_copy = waiting_threads;
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.cpp]: What's the purpose of this duplicate? (I suspect, but explain in a comment.)

File: src/core/hle/kernel/kernel.h [hunk 17]
```diff
@@ -146,14 +207,14 @@ class HandleTable final : NonCopyable {
 
     /**
      * Looks up a handle.
-     * @returns Pointer to the looked-up object, or `nullptr` if the handle is not valid.
+     * @return Pointer to the looked-up object, or `nullptr` if the handle is not valid.
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: Both are recognized by doxygen, and I think `@returns` reads better. But I don't really care.

File: src/core/hle/kernel/kernel.h [hunk 18]
```diff
@@ -92,6 +103,56 @@ inline void intrusive_ptr_release(Object* object) {
...
+    Thread* ReleaseNextThread();
+
+    /**
+     * Releases all threads waiting on this object
+     * @return True if any threads were resumed, otherwise false
+     */
+    bool ReleaseAllWaitingThreads();
+
+private:
+    std::vector<Thread*> waiting_threads; ///< Threads waiting on this object
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: "Waiting for this object to become available" or something more explicit.

File: src/core/hle/kernel/kernel.h [hunk 19]
```diff
@@ -92,6 +103,56 @@ inline void intrusive_ptr_release(Object* object) {
...
+     * Removes a thread from waiting on this object (e.g. if it was resumed already)
+     * @param thread Pointer to thread to remove
+     */
+    void RemoveWaitingThread(Thread* thead);
+
+    /**
+     * Releases (and removes) the next thread waiting on this object
+     * @return Pointer to the thread that was resumed, nullptr if no threads are waiting
+     */
+    Thread* ReleaseNextThread();
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: What's the meaning of "releasing" here? I think "waking up" might be a clearer term. (If that's what it meant.)

File: src/core/hle/kernel/mutex.cpp [hunk 20]
```diff
@@ -24,10 +24,11 @@ class Mutex : public Object {
     bool initial_locked;                        ///< Initial lock state when mutex was created
     bool locked;                                ///< Current locked state
     Handle lock_thread;                         ///< Handle to thread that currently has mutex
-    std::vector<Handle> waiting_threads;        ///< Threads that are waiting for the mutex
     std::string name;                           ///< Name of mutex (optional)
+    SharedPtr<Thread> current_thread;           ///< Thread that has acquired the mutex
```
Comment (yuriks) [inline src/core/hle/kernel/mutex.cpp]: I think `lock_thread` should be changed to `SharedPtr` too, since it's quite incoherent to have them mixed like this.

File: src/core/hle/kernel/kernel.h [hunk 21]
```diff
@@ -92,6 +103,56 @@ inline void intrusive_ptr_release(Object* object) {
...
+     * Check if this object is available
+     * @return True if the current thread should wait due to this object being unavailable
+     */
+    virtual ResultVal<bool> Wait() {
+        LOG_ERROR(Kernel, "(UNIMPLEMENTED)");
+        return UnimplementedFunction(ErrorModule::Kernel);
+    }
+
+    /**
+     * Acquire/lock the this object if it is available
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: "the this"

File: src/core/hle/kernel/mutex.cpp [hunk 22]
```diff
@@ -172,17 +159,20 @@ Handle CreateMutex(bool initial_locked, const std::string& name) {
...
 }
 
-ResultVal<bool> Mutex::WaitSynchronization() {
-    bool wait = locked;
-    if (locked) {
-        waiting_threads.push_back(GetCurrentThread()->GetHandle());
-        Kernel::WaitCurrentThread(WAITTYPE_MUTEX, this);
-    } else {
+ResultVal<bool> Mutex::Wait() {
+    return MakeResult<bool>(locked && (current_thread != GetCurrentThread()));
```
Comment (yuriks) [inline src/core/hle/kernel/mutex.cpp]: I think the parenthesis around the comparison just exacerbate the )))))) problem while not really making things any clearer to me.

File: src/core/hle/kernel/kernel.h (hunk 18 above)
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: FYI, it's not really safe for this to be a vector of raw pointers, since said threads could theoretically disappear at any moment. (I don't know if they actually can in practice, I'm unsure if there's any SVC call in the CTR kernel that allows forceful termination of a thread.) The solutions for this are:
  1. This should be a vector of `SharedPtr`, and threads should have a flag/state specifying that they're dead. They'll then be reaped (removed from the list) if encountered while popping from this list.
  2. Threads need to know what `WaitObject`s they're waiting on and remove themselves from all those when terminated. This is probably the cleaner solution but I'm undecided.

A possible "3. Use `weak_ptr`" was my original motivation for exploring using `std::shared_ptr` instead of intrusive pointers, but I'm now convinced that's not worth it or a good idea.

File: src/core/hle/kernel/kernel.h [hunk 23]
```diff
@@ -92,6 +103,56 @@ inline void intrusive_ptr_release(Object* object) {
...
 
+/// Class that represents a Kernel object that a thread can be waiting on
+class WaitObject : public Object {
+public:
+
+    /**
+     * Check if this object is available
+     * @return True if the current thread should wait due to this object being unavailable
+     */
+    virtual ResultVal<bool> Wait() {
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: These should just be pure-virtual functions.

Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: Considering what this thing actually does I think it should be named "IsAvailable" instead, or at the very least "ShouldWait" or similar.

File: src/core/hle/kernel/mutex.cpp (hunk 22 above)
Comment (yuriks) [inline src/core/hle/kernel/mutex.cpp]: Is this self-wait protection verified against the CTR kernel? (Not because I think it'll break anything, but rather because it allows simplification of this code if it doesn't exist.)

File: src/core/hle/kernel/session.h [hunk 24]
```diff
@@ -53,6 +53,12 @@ class Session : public Object {
      * aren't supported yet.
      */
     virtual ResultVal<bool> SyncRequest() = 0;
+
+    ResultVal<bool> Wait() override {
+        // TODO(bunnei): This function exists to satisfy a hardware test with a Session object
+        // passed into WaitSynchronization. Not sure if it's possible for this to ever be false?
```
Comment (yuriks) [inline src/core/hle/kernel/session.h]: Change TODO to mention more explicitly that these semantics need to be figured out. It sounds quite confused at the moment.

File: src/core/hle/kernel/thread.h [hunk 25]
```diff
@@ -78,9 +67,23 @@ class Thread : public Kernel::Object {
     u32 GetThreadId() const { return thread_id; }
 
     void Stop(const char* reason);
-    /// Resumes a thread from waiting by marking it as "ready".
+    
+    /**
+     * Release a wait object from the thread's wait list
+     * @param wait_object WaitObject to release from the thread's wait list
+     */
+    void ReleaseWaitObject(WaitObject* wait_object);
```
Comment (yuriks) [inline src/core/hle/kernel/thread.h]: Similar comment about "Release"

File: src/core/hle/svc.cpp [hunk 26]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
-    SharedPtr<Kernel::Object> object = Kernel::g_handle_table.GetGeneric(handle);
+    auto object = Kernel::g_handle_table.GetWaitObject(handle);
     if (object == nullptr)
         return InvalidHandle(ErrorModule::Kernel).raw;
 
     LOG_TRACE(Kernel_SVC, "called handle=0x%08X(%s:%s), nanoseconds=%lld", handle,
             object->GetTypeName().c_str(), object->GetName().c_str(), nano_seconds);
 
-    ResultVal<bool> wait = object->WaitSynchronization();
+    ResultVal<bool> wait = object->Wait();
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Shouldn't the error be checked right after this? Currently, if this errors out, the object will be acquired anyway. (Are there even situation where waiting will fail? If not then it should just return a plain bool.

File: src/core/hle/svc.cpp [hunk 27]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+
+        object->AddWaitingThread(Kernel::GetCurrentThread());
+        Kernel::WaitCurrentThread_WaitSynchronization(object);
+
         // Create an event to wake the thread up after the specified nanosecond delay has passed
         Kernel::WakeThreadAfterDelay(Kernel::GetCurrentThread(), nano_seconds);
+
         HLE::Reschedule(__func__);
+    } else {
+        object->Acquire();
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: The result code of the acquire isn't being propagated. In fact, the return value isn't being used at all.

File: src/core/hle/svc.cpp [hunk 28]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
             object->GetTypeName().c_str(), object->GetName().c_str(), nano_seconds);
 
-    ResultVal<bool> wait = object->WaitSynchronization();
+    ResultVal<bool> wait = object->Wait();
 
     // Check for next thread to schedule
     if (wait.Succeeded() && *wait) {
+
+        object->AddWaitingThread(Kernel::GetCurrentThread());
+        Kernel::WaitCurrentThread_WaitSynchronization(object);
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: As I understand it, after this call the return code of this function doesn't matter? I think you should add and explicit return here of some dummy code and a comment saying so.

File: src/core/hle/kernel/kernel.h [hunk 29]
```diff
@@ -92,6 +103,56 @@ inline void intrusive_ptr_release(Object* object) {
...
+        LOG_ERROR(Kernel, "(UNIMPLEMENTED)");
+        return UnimplementedFunction(ErrorModule::Kernel);
+    }
+
+    /**
+     * Acquire/lock the this object if it is available
+     * @return True if we were able to acquire this object, otherwise false
```
Comment (yuriks) [inline src/core/hle/kernel/kernel.h]: It seems to me that failure to acquire the object when calling this would be an error itself, so this should just return a `ResultCode`.

File: src/core/hle/kernel/thread.cpp [hunk 30]
```diff
@@ -88,19 +83,18 @@ static void ChangeReadyState(Thread* t, bool ready) {
...
+        if (*itr == wait_object)
+            return (thread->IsWaiting());
+    }
+    return false;
 }
 
-/// Check if a thread is blocking on a specified wait type with a specified handle and address
-static bool CheckWaitType(const Thread* thread, WaitType type, Object* wait_object, VAddr wait_address) {
-    return CheckWaitType(thread, type, wait_object) && (wait_address == thread->wait_address);
+/// Check if a thread is waiting on a the specified address arbiter
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Which specified address arbiter? :)

File: src/core/hle/kernel/thread.cpp [hunk 31]
```diff
@@ -129,22 +118,16 @@ static void ChangeThreadState(Thread* t, ThreadStatus new_status) {
...
     Thread* highest_priority_thread = nullptr;
     s32 priority = THREADPRIO_LOWEST;
 
     // Iterate through threads, find highest priority thread that is waiting to be arbitrated...
     for (auto& thread : thread_list) {
-        if (!CheckWaitType(thread.get(), WAITTYPE_ARB, arbiter, address))
+        if (!CheckWait_AddressArbiter(thread.get(), address))
             continue;
 
         if (thread == nullptr)
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Can you get rid of the below comment for me? It doesn't apply anymore.

File: src/core/hle/kernel/thread.cpp [hunk 32]
```diff
@@ -165,21 +148,18 @@ Thread* ArbitrateHighestPriorityThread(Object* arbiter, u32 address) {
...
 /// Arbitrate all threads currently waiting
-void ArbitrateAllThreads(Object* arbiter, u32 address) {
+void ArbitrateAllThreads(u32 address) {
 
     // Iterate through threads, find highest priority thread that is waiting to be arbitrated...
     for (auto& thread : thread_list) {
-        if (CheckWaitType(thread.get(), WAITTYPE_ARB, arbiter, address))
-            thread->ResumeFromWait();
+        if (CheckWait_AddressArbiter(thread.get(), address))
+            thread->ResumeFromWait();;
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Trailing extra semicolon;;

File: src/core/hle/kernel/thread.cpp (hunk 30 above)
Comment (kevinhartman) [inline src/core/hle/kernel/thread.cpp]: "a the"

File: src/core/hle/kernel/thread.cpp [hunk 33]
```diff
@@ -223,16 +202,28 @@ static Thread* NextThread() {
     return next;
 }
 
-void WaitCurrentThread(WaitType wait_type, Object* wait_object) {
+void WaitCurrentThread_Sleep() {
+    Thread* thread = GetCurrentThread();
+    thread->wait_all = false;
+    thread->wait_address = 0;
+    thread->wait_objects.clear();
```
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: Shouldn't these resets be done when the thread wakes up? The feel out of place.

Comment (kevinhartman) [inline src/core/hle/kernel/thread.cpp]: It seems to me like WaitType made more sense than clearing this stuff. Depending on WaitType, you could interpret these parameters (or not) accordingly. When a WaitType uses these kinds of fields, then it can set them.

File: src/core/hle/kernel/thread.cpp (hunk 1 above)
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: It *shouldn't* matter per the ARM calling convention standard since r0-r3 are scratch regs (get blasted after a function call), but yeah, *if* the CTR kernel doesn't trash it then we shouldn't either.

File: src/core/hle/service/srv.cpp [hunk 34]
```diff
@@ -24,7 +24,7 @@ static void GetProcSemaphore(Service::Interface* self) {
 
     // TODO(bunnei): Change to a semaphore once these have been implemented
     g_event_handle = Kernel::CreateEvent(RESETTYPE_ONESHOT, "SRV:Event");
-    Kernel::SetEventLocked(g_event_handle, false);
+    Kernel::SetEventSignaled(g_event_handle, false);
```
Comment (yuriks) [inline src/core/hle/service/srv.cpp]: You didn't flip the intial state here. Intentional?

File: src/core/hle/svc.cpp [hunk 35]
```diff
@@ -103,12 +103,7 @@ static Result SendSyncRequest(Handle handle) {
 
     LOG_TRACE(Kernel_SVC, "called handle=0x%08X(%s)", handle, session->GetName().c_str());
 
-    ResultVal<bool> wait = session->SyncRequest();
-    if (wait.Succeeded() && *wait) {
-        Kernel::WaitCurrentThread(WAITTYPE_SYNCH); // TODO(bunnei): Is this correct?
-    }
-
-    return wait.Code().raw;
+    return session->SyncRequest().Code().raw;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: What happened to the "`AddTicks` on service calls" hack? Is it not actually necessary with these improvements?

File: src/core/hle/svc.cpp [hunk 36]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+static Result WaitSynchronizationN(s32* out, Handle* handles, s32 handle_count, bool wait_all, s64 nano_seconds) {
+    bool wait_thread = !wait_all;
+    int handle_index = 0;
+
+    // Check if 'handles' is invalid
+    if (handles == nullptr)
+        return ResultCode(ErrorDescription::InvalidPointer, ErrorModule::Kernel, ErrorSummary::InvalidArgument, ErrorLevel::Permanent).raw;
+
+    // NOTE: on real hardware, there is no nullptr check for 'out' (tested with firmware 4.4). If
+    // this happens, the running application will crash.
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Which means Citra should also hard crash? Don't think so, no. You should log an error and return an error. (And in the future we should halt emulation here when we have that infrastructure, so leave a todo.)

File: src/core/hle/svc.cpp [hunk 37]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+
+    // Check if 'handle_count' is invalid
+    if (handle_count < 0)
+        return ResultCode(ErrorDescription::OutOfRange, ErrorModule::OS, ErrorSummary::InvalidArgument, ErrorLevel::Usage).raw;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Are these error conditions hwtested?

File: src/core/hle/svc.cpp [hunk 38]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+                if (!wait_all && !selected) {
+                    // Do not wait the thread
+                    wait_thread = false;
+                    handle_index = i;
+                    selected = true;
+                }
+            }
+        }
+    } else {
+        // If no handles were passed in, put the thread to sleep only when 'wait_all' is false
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: What's up with the random behavior? Why does it only wait in one mode?

File: src/core/hle/svc.cpp (hunk 8 above)
Comment (yuriks) [inline src/core/hle/svc.cpp]: I don't think it's confusing, it's merely jargon. That said, the comment is a bit strangely worded, it sound too tautological, even if I get what it's trying to say. Maybe try "if we decided to wait" instead.

File: src/core/hle/svc.cpp [hunk 39]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+        }
+
+        // Create an event to wake the thread up after the specified nanosecond delay has passed
+        Kernel::WakeThreadAfterDelay(Kernel::GetCurrentThread(), nano_seconds);
+
+        HLE::Reschedule(__func__);
+
+        // NOTE: output of this SVC will be set later depending on how the thread resumes
+    } else {
+        // Acquire objects if we did not end up waiting...
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: "if we did not wait."

File: src/core/hle/svc.cpp [hunk 40]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+        for (int i = 0; i < handle_count; i++) {
+            auto object = Kernel::g_handle_table.GetWaitObject(handles[i]);
+
+            // Check if the object is not waiting...
+            ResultVal<bool> wait = object->Wait();
+
+            // Acquire the object if it is not waiting...
+            if (!*wait) {
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: You're not checking `wait` for success before using the value. (But see my comment about this probably not needing to be a `ResultVal` first.)

File: src/core/hle/svc.cpp [hunk 41]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
-        ResultVal<bool> wait_result = object->WaitSynchronization();
-        bool wait = wait_result.Succeeded() && *wait_result;
-
-        if (!wait && !wait_all) {
-            *out = i;
-            return RESULT_SUCCESS.raw;
-        } else {
-            unlock_all = false;
+static Result WaitSynchronizationN(s32* out, Handle* handles, s32 handle_count, bool wait_all, s64 nano_seconds) {
+    bool wait_thread = !wait_all;
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: The naming of this variable isn't very good. I think a more semantically meaningful name like "resources_available" would make the logic easier to understand.

File: src/core/hle/svc.cpp [hunk 42]
```diff
@@ -120,64 +115,124 @@ static Result CloseHandle(Handle handle) {
...
+
+                // If this was the first non-waiting object and 'wait_all' is false, don't acquire
+                // any other objects
+                if (!wait_all)
+                    break;
+            }
+        }
+
+        // TODO(bunnei): If 'wait_all' is true, this is probably wrong. However, real hardware does
+        // not seem to set it to any meaningful value.
```
Comment (yuriks) [inline src/core/hle/svc.cpp]: Wasn't @Subv saying it's set to `handle_count`? (I might be confusing this with something else.)

File: src/core/hle/kernel/thread.cpp (hunk 33 above)
Comment (yuriks) [inline src/core/hle/kernel/thread.cpp]: We had way more wait types than necessary though. There are basically only 3 types of waits: Sleep, Object, AddressArbiter (which is the same as Object but with an additional address.) and if I remember correctly we had one wait type for each syncrhonization primitive in the kernel. If we had decent ADTs in C++ then I'd use one for this too, but as it stands I think their use is fine. What I have an issue with is where these variables are set. They seem to arbitrarily reset or maintain values.

File: src/core/hle/svc.cpp (hunk 42 above)
Comment (bunnei) [inline src/core/hle/svc.cpp]: @Subv said that, which I believe was based on the old code. Which was based on 3dmoo. I've yet to reproduce this on HW.

File: src/core/hle/svc.cpp (hunk 38 above)
Comment (bunnei) [inline src/core/hle/svc.cpp]: That's just what I observed in my tests. I'll push these soon.

File: src/core/hle/svc.cpp (hunk 37 above)
Comment (bunnei) [inline src/core/hle/svc.cpp]: yes

File: src/core/hle/svc.cpp (hunk 36 above)
Comment (bunnei) [inline src/core/hle/svc.cpp]: I'll put a TODO in. We don't really have a means to halt the emulator yet.

Comment (yuriks) [inline src/core/hle/svc.cpp]: assert at least then? I think it's stupid to leave a silent bug/crash like this which we'll likely waste time looking at in the future when we could just check it.

File: src/core/hle/kernel/address_arbiter.cpp (hunk 11 above)
Comment (bunnei) [inline src/core/hle/kernel/address_arbiter.cpp]: I'm not really sure what you're asking, are you looking for an explanation of svcArbitrateAddress? (becuase that's what this function is)

File: src/core/hle/kernel/kernel.cpp (hunk 15 above)
Comment (bunnei) [inline src/core/hle/kernel/kernel.cpp]: The only way it makes sense for a thread to wait on the same object is for WaitSynchN to be passed in with multiple handles to the same object. I already handle this correctly (with both the case where it's the same handle multiple times, or different handles via svcDuplicateHandle)

File: src/core/hle/kernel/mutex.cpp (hunk 22 above)
Comment (bunnei) [inline src/core/hle/kernel/mutex.cpp]: Yes, I verified this behavior on hw

File: src/core/hle/kernel/address_arbiter.cpp (hunk 11 above)
Comment (yuriks) [inline src/core/hle/kernel/address_arbiter.cpp]: Pretty much, yeah, I guess.

File: src/core/hle/svc.cpp (hunk 42 above)
Comment (yuriks) [inline src/core/hle/svc.cpp]: Ah, ok.

File: src/core/hle/service/srv.cpp (hunk 34 above)
Comment (bunnei) [inline src/core/hle/service/srv.cpp]: Yes

Comment (yuriks) [inline src/core/hle/service/srv.cpp]: Ok

File: src/core/hle/svc.cpp (hunk 35 above)
Comment (bunnei) [inline src/core/hle/svc.cpp]: Resolved on IRC, this was just a misunderstanding of the purpose of said hack.

File: src/core/hle/service/srv.cpp (hunk 34 above)
Comment (bunnei) [inline src/core/hle/service/srv.cpp]: Yes

File: src/core/hle/kernel/mutex.cpp [hunk 43]
```diff
@@ -23,11 +23,11 @@ class Mutex : public Object {
 
     bool initial_locked;                        ///< Initial lock state when mutex was created
     bool locked;                                ///< Current locked state
-    Handle lock_thread;                         ///< Handle to thread that currently has mutex
-    std::vector<Handle> waiting_threads;        ///< Threads that are waiting for the mutex
     std::string name;                           ///< Name of mutex (optional)
+    SharedPtr<Thread> lock_thread;              ///< Thread that has acquired the mutex
```
Comment (yuriks) [inline src/core/hle/kernel/mutex.cpp]: Bad name (though the comment is good), rename to `holding_thread`. ("Holding a mutex" is the usual terminology for a thread that has acquired one, but if you think that's confusing for you then `locking_thread` works too.)

File: src/core/hle/kernel/mutex.cpp [hunk 44]
```diff
@@ -38,57 +38,29 @@ static MutexMap g_mutex_held_locks;
 /**
  * Acquires the specified mutex for the specified thread
  * @param mutex Mutex that is to be acquired
- * @param thread Thread that will acquired
+ * @param thread Thread that will acquire the mutex
  */
-void MutexAcquireLock(Mutex* mutex, Handle thread = GetCurrentThread()->GetHandle()) {
-    g_mutex_held_locks.insert(std::make_pair(thread, mutex->GetHandle()));
+void MutexAcquireLock(Mutex* mutex, Thread* thread) {
+    g_mutex_held_locks.insert(std::make_pair(thread->GetHandle(), mutex->GetHandle()));
```
Comment (yuriks) [inline src/core/hle/kernel/mutex.cpp]: Any reason not to change the data structure while at it?

File: src/core/hle/result.h [hunk 45]
```diff
@@ -221,6 +221,9 @@ inline bool operator!=(const ResultCode a, const ResultCode b) {
 /// The default success `ResultCode`.
 const ResultCode RESULT_SUCCESS(0);
 
+/// A dummy result code that is meant to be overwritten (e.g. when a thread resumes)
+const ResultCode RESULT_DUMMY(0xDEADC0DE);
```
Comment (yuriks) [inline src/core/hle/result.h]: I don't think this really belong in result.h since it's existence is pretty specific to the use in the waits...

**Comment by yuriks** [comment]
Mostly looks good except for the comments above.
