### PR TITLE
configure_input: fix modifier scale saving

### LINKED ISSUE #5705: Input modifier scales revert back to default upon restart of Citra
The input modifier scales as seen in the attached figure revert to default values upon citra's restart. You can mod them while citra is running and they stay, but any modifications made to the modifier scale are reset upon citra's restart. I was able to change the default value manually in qt-config.ini (Nightly 1678)

mod scales

`profiles\1\circle_pad="down:axis$01$1direction$0+$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$00.5,engine:analog_from_button,left:axis$00$1direction$0-$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$0-0.5,modifier:button$011$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00,modifier_scale:0.890000,right:axis$00$1direction$0+$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$00.5,up:axis$01$1direction$0-$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$0-0.5"
profiles\1\c_stick\default=false
profiles\1\c_stick="down:axis$01$1direction$0+$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$00.5,engine:analog_from_button,left:axis$00$1direction$0-$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$0-0.5,modifier_scale:0.070000,right:axis$00$1direction$0+$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$00.5,up:axis$01$1direction$0-$1engine$0sdl$1guid$0030000004c050000e60c000000000000$1port$00$1threshold$0-0.5"
`

This is important because the default modifier value of 50% is too slow to dexnav for Pokemon in caves in Pokemon Omega Ruby and Alpha Sapphire. It is inconvenient to have to change the modifier to 89% every time, which is the fastest that the character can move before the Pokemon runs away

### PR DESCRIPTION
**Pull request by vitor-k**
Should fix #5705

Actually apply and save the configurations when the modifier scale or deadzone is modified.

Also change the Restore Defaults to affect the modifier scale.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5707)

### CODE REVIEW

File: src/citra_qt/configuration/configure_input.cpp [hunk 1]
```diff
@@ -373,6 +375,9 @@ void ConfigureInput::RestoreDefaults() {
                 Config::default_analogs[analog_id][sub_button_id])};
             SetAnalogButton(params, analogs_param[analog_id], analog_sub_buttons[sub_button_id]);
         }
+        if (analogs_param[analog_id].Get("modifier_scale", 0.5f) != 0.5f) {
+            analogs_param[analog_id].Set("modifier_scale", 0.5f);
```
Comment (adityaruplaha) [inline src/citra_qt/configuration/configure_input.cpp:379]: This might be stupid question... If it's not 0.5f, why are we resetting it to 0.5f?

Comment (vitor-k) [reply src/citra_qt/configuration/configure_input.cpp:379]: This is in `RestoreDefaults`, so we want to reset it to the default value (0.5f)

Comment (adityaruplaha) [reply src/citra_qt/configuration/configure_input.cpp:379]: Oh I'm an idiot.

Comment (BreadFish64) [reply src/citra_qt/configuration/configure_input.cpp:379]: Is there a reason it can't just be set unconditionally?

Comment (vitor-k) [reply src/citra_qt/configuration/configure_input.cpp:379]: modifier_scale is not present when it's an actual analog axis... though in that case there's the deadzone that I forgot to address. 
So this should probably be an `if(analogs_param[analog_id].Get("engine", "") == "sdl")` set deadzone, `else` set modifier_scale.
I'll fix it in a bit.

Comment (vitor-k) [reply src/citra_qt/configuration/configure_input.cpp:379]: Or no, actually. There'd be no need to set deadzone because it'd revert to defaults which is keyboard.
Unconditional sounds good then.

**Review by zhaowenlan1779 — APPROVED** [review]
