### PR TITLE
Kernel: Implemented shared memory.

### LINKED ISSUE #1318: Family Kart 3D - not load anymore (shared_font.bin bug)
Tested on latest commit https://github.com/citra-https://github.com/citra-emu/citra/commit/82087672b7eba5a42e081c29b8e7b79cb4f77a25

* additional merged https://github.com/citra-emu/citra/pull/1302

This game is not showing anything now...

https://www.youtube.com/watch?v=e-pr1VA3GAU

LOG: http://pastebin.com/FegwAebg

### LINKED ISSUE #1497: 7th Dragon III Code: VFD - Japanese text invisible
Using https://github.com/citra-emu/citra/commit/c6cf075b5169ec40103b59ae170d0a7e369ed09d

This already happens in the menu:
(Compare to japanese near bottom of top screen: https://youtu.be/ardlHbCKrIk?t=33s)

Broken font

Here is the same thing with hacked checkerboard texture:

Checkerboard test font

Seeing how the draw calls get through this is probably related to a missing texture.
The japanese text seems to come from a 128 x 32 A4 texture. The texture seems to be fully transparent in my installation of citra.
I believe this is due to a missing japanese font texture. It might be part of what is dumped as shared_font.bin on japanese systems so that should be tested.

~~Probably also affects "Digimon World ReDigtize Decode" ( #1129 ). I'll rename this issue if this affects nearly all japanese games.~~

[Full log](https://cdn.rawgit.com/JayFoxRox/629de0916c9730d30a5c/raw/f0daac5b8150ef661a4038daf0a5bfce1ca14564/index.html)

### LINKED ISSUE #1547: Mario Golf World Tour / Mario Tennis Open - won't boot
**All of these doesn't show anything and spams with**

```
[  12.373419] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!
[  12.478593] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::SignalInterrupt:324: cannot synchronize until GSP event has been created!
```

**also:**
`[  34.961312] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function 'GetStartupArgument': port=APT:U, cmd_buff[1]=0x2, cmd_buff[2]=0x1`

**Mario Golf World Tour**

[LOG](http://pastebin.com/fDNrHEGf)

**Mario Tennis Open**

[LOG](http://pastebin.com/f8d3yRPt)

### LINKED ISSUE #1591: Rodea The Sky Soldier - Won't boot anymore
It's an pretty old regression.Working build was made more than half year ago.Ingame [video](https://www.youtube.com/watch?v=LBP0AaYtxJM)

[LOG](http://pasted.co/63759dd0)

### LINKED ISSUE #1596: Power Rangers: Megaforce - Won't boot
Only spams with:

```
[   0.490392] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!
[   0.540474] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!
[   0.541876] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!
[   0.543445] Kernel.SVC <Error> core\hle\kernel\shared_memory.cpp:Kernel::SharedMemory::GetPointer:102: memory block id=33 not mapped!
```

[LOG](http://pasted.co/249b2c78)

### LINKED ISSUE #1603: Kid Icarus Uprising - Won't boot
`[   2.056845] Service <Error> core\hle\service\service.cpp:Service::Interface::SyncRequest:68: unknown / unimplemented function '0x00010082': port=boss:U, cmd_buff[1]=0x0, cmd_buff[2]=0x0, cmd_buff[3]=0x20, cmd_buff[4]=0x0`

[LOG](http://pasted.co/f084e732)

### PR DESCRIPTION
**Pull request by Subv**
This PR corrects the implementation of Shared Memory thorough the codebase.
SharedMemories created by HLE processes are backed by memory located in the BASE linear heap region (Unless stated otherwise by the call to Create), as per the real kernel.

With this we can get rid of some very nasty hacks, like the APT Shared Font being located at a fixed address. This PR implements a function to automatically relocate the dumped shared font from the 0x18000000 address to whatever address the allocator places it at. This fixes an issue where we were placing the shared font in the middle of the APPLICATION memory region (Possibly breaking games that use that part of the region).

All error codes were verified by reverse engineering unless otherwise stated.
There are some sanity checks that can not be performed unless we give each HLE service its own Process, but that's a discussion for another time.

Closes #1603
Closes #1547
Closes #1591
Closes #1318
Closes #1596
Closes #1497

### CODE REVIEW

**Comment by wwylele** [comment]
I am not sure if I did something wrong, but with this PR, all of my games can't boot and spam with:
`HW.Memory <Error> core\memory.cpp:Memory::Read:137: unmapped Read8 @ 0x10002001`

**Comment by mailwl** [comment]
Kid Icarus Uprising - Won't boot #1603, the real candidate for testing this PR throws error:
> [  21.386077] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:108: Fatal error!
> [  21.391196] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:116: PID: 0x00000000_0x00000000
> [  21.391607] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:117: REV: 44677
> [  21.391972] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:118: AID: 0x00000000_0x00000000
> [  21.392318] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:119: ADR: 0x00185C64
> [  21.392640] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:121: RSL: 0xE0E01BEE
> [  21.393029] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:122:   Level: 28
> [  21.393330] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:123:   Summary: 7
> [  21.393605] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:124:   Module: 6
> [  21.397221] Service.ERR <Critical> core\hle\service\err_f.cpp:ERR_F::ThrowFatalError:125:   Desc: 1006

**Comment by Subv** [comment]
There was an operator precedence error in the code, i've now updated it, could you please test again?

File: src/core/hle/kernel/shared_memory.h [hunk 1]
```diff
@@ -48,6 +48,12 @@ class SharedMemory final : public Object {
     HandleType GetHandleType() const override { return HANDLE_TYPE; }
 
     /**
+     * Converts the specified MemoryPermission into the equivalent VMAPermission.
+     * @param permission The MemoryPermission to convert.
+     */
+    static VMAPermission ConvertPermissions(MemoryPermission permission);
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.h]: This should just be a free local function in shared_memory.cpp

File: src/core/hle/kernel/shared_memory.cpp [hunk 2]
```diff
@@ -85,15 +109,29 @@ ResultCode SharedMemory::Map(SharedPtr<Process> target_process, VAddr address, M
...
 }
 
+VMAPermission SharedMemory::ConvertPermissions(MemoryPermission permission) {
+    u32 vma_permission = static_cast<u32>(VMAPermission::None);
+    if (static_cast<u32>(permission) & static_cast<u32>(MemoryPermission::Read))
+        vma_permission |= static_cast<u32>(VMAPermission::Read);
+    if (static_cast<u32>(permission) & static_cast<u32>(MemoryPermission::Write))
+        vma_permission |= static_cast<u32>(VMAPermission::Write);
+    if (static_cast<u32>(permission) & static_cast<u32>(MemoryPermission::Execute))
+        vma_permission |= static_cast<u32>(VMAPermission::Execute);
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: Except for DONT_CARE, VMAPermission purposefully matches the bits of SVC interface type, so you can just mask ensure there are no inappropriate bits set and cast.

File: src/core/hle/kernel/shared_memory.cpp [hunk 3]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
     shared_memory->permissions = permissions;
     shared_memory->other_permissions = other_permissions;
 
+    if (address == 0) {
+        // We need to allocate a block from the Linear Heap ourselves.
+        // We'll manually allocate some memory from the linear heap in the specified region.
+        MemoryRegionInfo* memory_region = GetMemoryRegion(region);
+        auto& linheap_memory = memory_region->linear_heap_memory;
+
+        ASSERT_MSG(linheap_memory->size() + size <= memory_region->size, "Not enough space in region to allocate shared memory!");
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: Shouldn't this return an error code instead?

File: src/core/hle/kernel/shared_memory.cpp [hunk 4]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
-    // HACK: Since there's no way to write to the memory block without mapping it onto the game
-    // process yet, at least initialize memory the first time it's mapped.
-    if (address != this->base_address) {
-        std::memset(Memory::GetPointer(address), 0, size);
-    }
+    // TODO(Subv): The same process that created a SharedMemory object
+    // can not map it in its own address space unless it was created with addr=0, result 0xD900182C.
 
-    this->base_address = address;
+    if (address) {
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: address != 0

File: src/core/hle/kernel/shared_memory.cpp [hunk 5]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
+        // We need to allocate a block from the Linear Heap ourselves.
+        // We'll manually allocate some memory from the linear heap in the specified region.
+        MemoryRegionInfo* memory_region = GetMemoryRegion(region);
+        auto& linheap_memory = memory_region->linear_heap_memory;
+
+        ASSERT_MSG(linheap_memory->size() + size <= memory_region->size, "Not enough space in region to allocate shared memory!");
+
+        shared_memory->backing_block = linheap_memory;
+        shared_memory->backing_block_offset = linheap_memory->size();
+        // Allocate some memory from the bottom of the linear heap for this region.
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: "from the end"* (less ambiguous)

File: src/core/hle/service/apt/apt.cpp [hunk 6]
```diff
@@ -71,26 +126,88 @@ void Initialize(Service::Interface* self) {
...
-        cmd_buff[3] = IPC::MoveHandleDesc();
-        cmd_buff[4] = Kernel::g_handle_table.Create(shared_font_mem).MoveFrom();
-    } else {
-        cmd_buff[0] = IPC::MakeHeader(0x44, 1, 0);
-        cmd_buff[1] = -1; // Generic error (not really possible to verify this on hardware)
-        LOG_ERROR(Kernel_SVC, "called, but %s has not been loaded!", SHARED_FONT);
-    }
+    // The shared font has to be relocated to the new address before being passed to the application.
+    VAddr target_address = Memory::PhysicalToVirtualAddress(shared_font_mem->linear_heap_phys_address);
+    // The shared font dumped by 3dsutils (https://github.com/citra-emu/3dsutils) uses this address as base,
```
Comment (yuriks) [inline src/core/hle/service/apt/apt.cpp]: This isn't true if you dump it on a n3DS. Is there a way to detect the address instead? (Ideally we should un-relocate while dumping, or you can use some pointer that's near the beginning of the file to guess the offset.)

File: src/core/hle/service/apt/apt.cpp [hunk 7]
```diff
@@ -433,14 +550,12 @@ void Init() {
...
     if (file.IsOpen()) {
-        // Read shared font data
-        shared_font = std::make_shared<std::vector<u8>>((size_t)file.GetSize());
-        file.ReadBytes(shared_font->data(), shared_font->size());
-
         // Create shared font memory object
         using Kernel::MemoryPermission;
-        shared_font_mem = Kernel::SharedMemory::Create(3 * 1024 * 1024, // 3MB
-                MemoryPermission::ReadWrite, MemoryPermission::Read, "APT_U:shared_font_mem");
+        shared_font_mem = Kernel::SharedMemory::Create(3272 * 1024, // 3272 KB
```
Comment (yuriks) [inline src/core/hle/service/apt/apt.cpp]: IMO just use 0x332000 here. Makes it more obvious that it's inherently 4k-aligned too (which isn't obvious like this)

File: src/core/hle/kernel/shared_memory.cpp [hunk 8]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
+        linheap_memory->insert(linheap_memory->end(), size, 0);
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: Needs this to avoid dangling pointers in the page table:
```
        if (Kernel::g_current_process != nullptr) {
            Kernel::g_current_process->vm_manager.RefreshMemoryBlockMappings(linheap_memory.get());
        }
```

File: src/core/hle/kernel/shared_memory.cpp [hunk 9]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
 SharedMemory::~SharedMemory() {}
 
 SharedPtr<SharedMemory> SharedMemory::Create(u32 size, MemoryPermission permissions,
-        MemoryPermission other_permissions, std::string name) {
+        MemoryPermission other_permissions, VAddr address, MemoryRegion region, std::string name) {
     SharedPtr<SharedMemory> shared_memory(new SharedMemory);
 
+    shared_memory->owner_process = Kernel::g_current_process;
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: This should be passed in as a parameter instead.

File: src/core/hle/kernel/shared_memory.cpp [hunk 10]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
+        shared_memory->backing_block = linheap_memory;
+        shared_memory->backing_block_offset = linheap_memory->size();
+        // Allocate some memory from the bottom of the linear heap for this region.
+        linheap_memory->insert(linheap_memory->end(), size, 0);
+        memory_region->used += size;
+
+        shared_memory->linear_heap_phys_address = Memory::FCRAM_PADDR + memory_region->base + shared_memory->backing_block_offset;
+    } else {
+        // The memory is already available and mapped in the owner process.
+        auto vma = shared_memory->owner_process->vm_manager.FindVMA(address)->second;
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: Make a reference to the vm_manager since it's used a bunch of times.

File: src/core/hle/kernel/shared_memory.cpp [hunk 11]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
+        // Reprotect the block with the new permissions
+        shared_memory->owner_process->vm_manager.ReprotectRange(address, size, ConvertPermissions(permissions));
+    }
+
+    shared_memory->base_address = address;
     return shared_memory;
 }
 
-ResultCode SharedMemory::Map(VAddr address, MemoryPermission permissions,
+ResultCode SharedMemory::Map(SharedPtr<Process> target_process, VAddr address, MemoryPermission permissions,
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: This isn't stored anywhere (aka, doesn't need to preserve lifetime) so it can just be a regular pointer

File: src/core/hle/kernel/shared_memory.cpp [hunk 12]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
+    auto result = target_process->vm_manager.MapMemoryBlock(target_address, backing_block, backing_block_offset, size, MemoryState::Shared);
+    if (result.Failed())
+        return result.Code();
 
-    base_address = 0;
+    return target_process->vm_manager.ReprotectRange(target_address, size, ConvertPermissions(permissions));
+}
 
-    return RESULT_SUCCESS;
+ResultCode SharedMemory::Unmap(SharedPtr<Process> target_process, VAddr address) {
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: Likewise, regular pointer

File: src/core/hle/kernel/shared_memory.cpp [hunk 13]
```diff
@@ -15,92 +16,124 @@ SharedMemory::SharedMemory() {}
...
+    return target_process->vm_manager.UnmapRange(address, size);
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.cpp]: Does the 3DS kernel check that it's indeed a shared memory that's mapped here? What happens if you try to unmap a random address? This isn't checked at all in the svc handler either.

File: src/core/hle/kernel/shared_memory.h [hunk 14]
```diff
@@ -66,10 +77,16 @@ class SharedMemory final : public Object {
     */
     u8* GetPointer(u32 offset = 0);
 
-    /// Address of shared memory block in the process.
+    /// Process that created this shared memory block.
+    SharedPtr<Process> owner_process;
+    /// Address of shared memory block in the owner process if specified.
     VAddr base_address;
```
Comment (yuriks) [inline src/core/hle/kernel/shared_memory.h]: This doesn't seem to be used anymore except for checking if it is equal to 0. Do you still need to keep this? (It also doesn't really make sense outside of the creating process.)

File: src/core/hle/service/apt/apt.cpp [hunk 15]
```diff
@@ -22,23 +22,78 @@
...
 namespace APT {
 
-// Address used for shared font (as observed on HW)
-// TODO(bunnei): This is the hard-coded address where we currently dump the shared font from via
-// https://github.com/citra-emu/3dsutils. This is technically a hack, and will not work at any
-// address other than 0x18000000 due to internal pointers in the shared font dump that would need to
-// be relocated. This might be fixed by dumping the shared font @ address 0x00000000 and then
-// correctly mapping it in Citra, however we still do not understand how the mapping is determined.
-static const VAddr SHARED_FONT_VADDR = 0x18000000;
+/// BCFNT Shared Font file structures
```
Comment (yuriks) [inline src/core/hle/service/apt/apt.cpp]: I think you should move this and the relocation to separate bcfnt file(s) in the apt subdir.

File: src/core/hle/service/apt/apt.cpp [hunk 16]
```diff
@@ -71,26 +126,88 @@ void Initialize(Service::Interface* self) {
...
+    VAddr target_address = Memory::PhysicalToVirtualAddress(shared_font_mem->linear_heap_phys_address);
+    // The shared font dumped by 3dsutils (https://github.com/citra-emu/3dsutils) uses this address as base,
+    // so we relocate it from there to our real address.
+    static const VAddr SHARED_FONT_VADDR = 0x18000000;
+    if (!shared_font_relocated)
+        RelocateSharedFont(SHARED_FONT_VADDR, target_address);
+    cmd_buff[0] = IPC::MakeHeader(0x44, 2, 2);
+    cmd_buff[1] = RESULT_SUCCESS.raw; // No error
+    // Since the SharedMemory interface doesn't provide the address at which the memory was allocated,
+    // the APT service calculates this address by scanning the entire address space (using svcQueryMemory)
```
Comment (yuriks) [inline src/core/hle/service/apt/apt.cpp]: "the *real* APT service", just to clarify

**Comment by wwylele** [comment]
Test with some random games, still some problems:
**Super Mario 3D Land** don't boot, and `ThrowFatelError`.
**Kirby Triple Deluxe** and **Pokemon Mystery Dungeon: Gate to Infinity** boot, but don't receive any input.
Some other games work fine.

**Comment by yuriks** [comment]
@wwylele You need to add these lines to fix a bug: https://github.com/citra-emu/citra/pull/1689#discussion_r60173069

**Comment by wwylele** [comment]
@yuriks Thanks. Kirby and Pokemon are OK now, but Mario still throws fatal error.

File: src/core/hle/kernel/shared_memory.h (hunk 14 above)
Comment (Subv) [inline src/core/hle/kernel/shared_memory.h]: For now it's basically acting as a linear_heap_allocation variable, but i consider it good to keep it around even if just for information's sake

**Comment by Subv** [comment]
Addressed some comments, also fixed the problem with Mario 3D Land (Logic error in CreateMemoryBlock) @wwylele

**Comment by wwylele** [comment]
@Subv sorry for late reply. Mario 3D Land works fine now and no more game broken.

**Comment by Subv** [comment]
Updated again and addressed most comments, some of the sanity checks (mostly edge cases) when freeing memory are not implemented because I don't currently have a way to verify their behavior.

File: src/core/hle/service/apt/apt.cpp [hunk 17]
```diff
@@ -71,26 +63,30 @@ void Initialize(Service::Interface* self) {
     LOG_DEBUG(Service_APT, "called app_id=0x%08X, flags=0x%08X", app_id, flags);
 }
 
+
+
```
Comment (jroweboy) [inline src/core/hle/service/apt/apt.cpp]: Minor style nitpick: extra blank spaces

File: src/core/hle/service/apt/apt.cpp (hunk 15 above)
Comment (JayFoxRox) [inline src/core/hle/service/apt/apt.cpp]: Agreed, I'm still hoping someone will make it possible to run without the font dump by creating a font file in memory at runtime (Rendered from ttf or something).

File: src/core/hle/service/apt/bcfnt/bcfnt.cpp [hunk 18]
```diff
@@ -0,0 +1,71 @@
...
+    CFNT cfnt;
+    memcpy(&cfnt, data, sizeof(cfnt));
+
+    // Advance past the header
+    data = shared_font->GetPointer(SharedFontStartOffset + cfnt.header_size);
+
+    for (unsigned block = 0; block < cfnt.num_blocks; ++block) {
+
+        u32 section_size = 0;
+        if (memcmp(data, "FINF", 4) == 0) {
```
Comment (JayFoxRox) [inline src/core/hle/service/apt/bcfnt/bcfnt.cpp]: I'm not an expert on char encoding, but can we assure that this will work on all machines?
I'd expect each symbol to use 2 bytes in some encodings and that could mean trouble.
Maybe create a const for the magic you are actually looking for?

**Comment by wwylele** [comment]
software keyboard and mii selector are broken. Super Mario 3D land for example when creating new file:
```
[  24.349965] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:69: unknown / unimplemented function 'ReplySleepQuery': port=APT:U, c
md_buff[1]=0x300, cmd_buff[2]=0x66630000
[  24.351432] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::A
ppletUtility:300: (STUBBED) called command=0x00000004, buffer1_size=0x00000001,
buffer2_size=0x00000001, buffer1_addr=0x0FFFFC9C, buffer2_addr=0x0FFFFC98
[  24.352993] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:69: unknown / unimplemented function 'ReplySleepQuery': port=APT:U, c
md_buff[1]=0x300, cmd_buff[2]=0x66630000
[  24.354790] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::G
etAppletInfo:393: (stubbed) called appid=1026
[  24.356181] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::A
ppletUtility:300: (STUBBED) called command=0x00000004, buffer1_size=0x00000001,
buffer2_size=0x00000001, buffer1_addr=0x0FFFFB0C, buffer2_addr=0x0FFFFB08
[  24.357373] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::I
sRegistered:150: (STUBBED) called app_id=0x00000402
[  24.358328] Service <Error> core\hle\service\service.cpp:Service::Interface::S
yncRequest:69: unknown / unimplemented function 'SaveVramSysArea': port=gsp::Gpu

[  24.359557] Service.GSP <Warning> core\hle\service\gsp_gpu.cpp:GSP_GPU::Import
DisplayCaptureInfo:630: called
[  24.360477] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::I
sRegistered:150: (STUBBED) called app_id=0x00000402
[  24.361445] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::S
endParameter:192: (STUBBED) called src_app_id=0x00000300, dst_app_id=0x00000402,
 signal_type=0x00000002,buffer_size=0x00000020, value=0x00000000, handle=0x00000
000, size=0x00080002, in_param_buffer_ptr=0x003F9400
[  24.363327] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::G
lanceParameter:238: called app_id=0x00000300, buffer_size=0x00001000
[  24.364313] Service.APT <Warning> core\hle\service\apt\apt.cpp:Service::APT::R
eceiveParameter:215: called app_id=0x00000300, buffer_size=0x00000000
```
(Till here is the same as it in master)
```
[ 113.753902] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Writ
e32 0xFE60FE60 @ 0x10004000
[ 113.962197] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Writ
e32 0xFE60FE60 @ 0x10004004
[ 114.169670] HW.Memory <Error> core\memory.cpp:Memory::Write:222: unmapped Writ
e32 0xFE60FE60 @ 0x10004008
...
```

File: src/core/hle/kernel/shared_memory.cpp [hunk 19]
```diff
@@ -7,100 +7,148 @@
...
+ResultCode SharedMemory::Map(Process* target_process, VAddr address, MemoryPermission permissions,
+        MemoryPermission other_permissions) {
 
-        // HACK(yuriks): This is only here to support the APT shared font mapping right now.
-        // Later, this should actually map the memory block onto the address space.
-        return RESULT_SUCCESS;
+    MemoryPermission own_other_permissions = target_process == owner_process ? this->permissions : this->other_permissions;
+
+    // Automatically allocated memory blocks can only be mapped with other_permissions = DontCare
+    if (base_address == 0 && other_permissions != MemoryPermission::DontCare) {
```
Comment (wwylele) [inline src/core/hle/kernel/shared_memory.cpp]: When Super Mario 3D Land calling mii selector, it wants to map the mii selector shared memory (`base_address=0`) with `other_permissions = MemoryPermission::ReadWrite`

Comment (Subv) [inline src/core/hle/kernel/shared_memory.cpp]: Interesting, i'll take another look at the kernel code later today

**Comment by Leo626** [comment]
Fixed the text in **Sadame**.
citra-qt_2016-05-01_20-02-44
citra-qt_2016-05-01_20-01-11

**Comment by JohnGodgames** [comment]
**With this PR:**
- Zoo Keeper 3D boots again
- Real Heroes Firefighter 3D boots again (show loading screen)

**Comment by Subv** [comment]
@wwylele I have a fix for the applet issue, I'll update this PR as soon as #1761 is merged

**Comment by Subv** [comment]
@wwylele Rebased and updated, the problem with applets should be fixed now.

**Comment by wwylele** [comment]
@Subv Nice, it works well at software keyboard and mii selector now. Didn't find anything broken more

File: src/core/hle/service/csnd_snd.cpp [hunk 20]
```diff
@@ -41,9 +42,9 @@ static Kernel::SharedPtr<Kernel::Mutex> mutex = nullptr;
 void Initialize(Service::Interface* self) {
     u32* cmd_buff = Kernel::GetCommandBuffer();
 
-    shared_memory = Kernel::SharedMemory::Create(cmd_buff[1],
-            Kernel::MemoryPermission::ReadWrite,
-            Kernel::MemoryPermission::ReadWrite, "CSNDSharedMem");
+    u32 size = Common::AlignUp(cmd_buff[1], Memory::PAGE_SIZE);
+    shared_memory = Kernel::SharedMemory::Create(nullptr, size,
```
Comment (tfarley) [inline src/core/hle/service/csnd_snd.cpp]: Text wrap like gsp_gpu.cpp/hid.cpp/ir.cpp

File: src/core/hle/function_wrappers.h [hunk 21]
```diff
@@ -170,7 +170,7 @@ template<ResultCode func(s64*, u32, s32)> void Wrap() {
 
 template<ResultCode func(u32*, u32, u32, u32, u32)> void Wrap() {
     u32 param_1 = 0;
-    u32 retval = func(&param_1, PARAM(1), PARAM(2), PARAM(3), PARAM(4)).raw;
+    u32 retval = func(&param_1, PARAM(1), PARAM(2), PARAM(3), PARAM(0)).raw;
```
Comment (JayFoxRox) [inline src/core/hle/function_wrappers.h]: This feels weird, there should be a comment why this has to be like that or at least a comment that this is intentional.

Comment (Subv) [inline src/core/hle/function_wrappers.h]: This file is pretty much a "write and forget" thing, it's awful and full of little things that may break without anyone noticing (Like this function). /endrant

The reason why the arguments are ordered like that is not known, that's just what Nintendo's Kernel Calling Convention looks like (It's pretty inconsistent). I don't really see the value of placing a comment here.

Comment (hrydgard) [inline src/core/hle/function_wrappers.h]: Since it's rather unexpected and looks like a typo if you're not aware, I would agree with JayFoxRox that it does merit a (short) comment.

Comment (Subv) [inline src/core/hle/function_wrappers.h]: I've added a comment about this in the code.

**Comment by Subv** [comment]
Squashed, this one is good to go.

**Comment by bunnei** [comment]
LGTM

**Comment by KillzXGaming** [comment]
Seems this caused regression and broke Animal Crossing New Leaf. Can anyone else confirm this? I get these errors once booting and black screen. 
  21.516452] HW.Memory <Error> core\memory.cpp:Memory::Read:181: unmapped Read8 @ 0x10000001

**Comment by JohnGodgames** [comment]
My Animal Crossing New Leaf (US) works fine.
