### PR TITLE
Services/AM: Implement GetPatchTitleInfos, Misc Cleanup

### LINKED ISSUE #2980: Flipnote Studio 3D US: Crash on boot
Log: https://hastebin.com/icugikuyoy.xml
Commit: 30fabc4
Reproduction Steps: Run the application, see a crash.

### PR DESCRIPTION
**Pull request by shinyquagsire23**
Fixes #2980 (thanks to @mailwl for finding the actual issue there)

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3048)

### CODE REVIEW

File: src/core/hle/service/am/am.cpp [hunk 1]
```diff
@@ -341,6 +346,12 @@ void GetDataTitleInfos(Service::Interface* self) {
     LOG_WARNING(Service_AM, "(STUBBED) called");
 }
 
+void GetPatchTitleInfos(Service::Interface* self) {
+    GetProgramInfos(self);
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: You can't just call GetProgramInfos, the command headers are different. If needed, factor out the body of GetProgramInfos and call that from both functions after extracting the input parameters

Comment (Subv) [reply src/core/hle/service/am/am.cpp]: On that note, GetProgramInfos has ` IPC::RequestParser rp(Kernel::GetCommandBuffer(), 3, 2, 2); // 0x00030084` which is wrong, it should be ` IPC::RequestParser rp(Kernel::GetCommandBuffer(), 3, 2, 4); // 0x00030084`

Comment (Subv) [reply src/core/hle/service/am/am.cpp]: According to RE, GetPatchTitleInfos has 4 translate parameters that you're not sending in the response.

Comment (Subv) [reply src/core/hle/service/am/am.cpp]: The only difference between the GetPatchTitleInfos and GetProgramInfos implementation is that GetPatchTitleInfos will first iterate over the input title ids and return 0xE0E0803C if any of them satisfies `high >> 14 != 16 || high & 0xFFFF == 14`

Comment (shinyquagsire23) [reply src/core/hle/service/am/am.cpp]: Ah, yeah you're right, on hardware I'm seeing a 0x100D0044 in the [0] spot for the response. Looks like it's just spitting out the same buffers passed in, at least judging by the sizes. Weird.

Comment (shinyquagsire23) [reply src/core/hle/service/am/am.cpp]: Actually, shouldn't it be high & 0xFFFF != 0xE? Since the TID high should always be 0x0004000E.

Comment (Subv) [reply src/core/hle/service/am/am.cpp]: > Ah, yeah you're right, on hardware I'm seeing a 0x100D0044 in the [0] spot for the response. Looks like it's just spitting out the same buffers passed in, at least judging by the sizes. Weird.

Yeah that's precisely what it's doing, it is indeed weird but 🤷‍♂️ 

> Actually, shouldn't it be high & 0xFFFF != 0xE? Since the TID high should always be 0x0004000E.

Yeah you're right, sorry, i misread the condition.

File: src/core/hle/service/am/am.cpp [hunk 2]
```diff
@@ -326,23 +320,84 @@ void GetProgramInfos(Service::Interface* self) {
...
+
+    ResultCode result = RESULT_SUCCESS;
+
+    // Validate that update TIDs were passed in
+    std::vector<u64> title_id_list(title_count);
+    Memory::ReadBlock(title_id_list_pointer, title_id_list.data(), title_count * sizeof(u64));
+    for (u32 i = 0; i < title_count; i++) {
+        u32 tid_high = static_cast<u32>(title_id_list[i] >> 32);
+        if (tid_high >> 14 != 0x10 || tid_high & 0xFFFF != 0xE) {
+            result = ResultCode(ErrCodes::InvalidTIDInList, ErrorModule::AM,
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: break

File: src/core/hle/service/am/am.cpp [hunk 3]
```diff
@@ -326,23 +320,84 @@ void GetProgramInfos(Service::Interface* self) {
...
+
+    if (result.IsSuccess()) {
+        result =
+            GetTitleInfoFromList(title_count, media_type, title_id_list_pointer, title_info_out);
+    }
 
-    LOG_WARNING(Service_AM, "(STUBBED) called");
+    IPC::RequestBuilder rb = rp.MakeBuilder(1, 4);
+    rb.Push(result);
+    rb.PushMappedBuffer(title_id_list_pointer, title_id_list_size, title_id_list_perms);
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: GetProgramInfos also pushes these buffers, i am unaware of whether GetDataTitleInfos does as well, but it should be checked

File: src/core/hle/service/am/am.cpp [hunk 4]
```diff
@@ -326,23 +320,84 @@ void GetProgramInfos(Service::Interface* self) {
...
+    VAddr title_info_out = rp.PopMappedBuffer(&title_info_size, &title_info_perms);
+
+    ResultCode result = RESULT_SUCCESS;
+
+    // Validate that update TIDs were passed in
+    std::vector<u64> title_id_list(title_count);
+    Memory::ReadBlock(title_id_list_pointer, title_id_list.data(), title_count * sizeof(u64));
+    for (u32 i = 0; i < title_count; i++) {
+        u32 tid_high = static_cast<u32>(title_id_list[i] >> 32);
+        if (tid_high >> 14 != 0x10 || tid_high & 0xFFFF != 0xE) {
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: add some parentheses to this expression, operator precedence will screw you over otherwise.

File: src/core/hle/service/am/am.cpp (hunk 3 above)
Comment (shinyquagsire23) [reply src/core/hle/service/am/am.cpp]: Just checked, it does seem to be the case so I might be able to merge things a bit nicer then.

File: src/core/hle/service/am/am.cpp [hunk 5]
```diff
@@ -302,11 +302,39 @@ void GetProgramList(Service::Interface* self) {
...
+    ResultCode result = RESULT_SUCCESS;
+
     std::vector<u64> title_id_list(title_count);
     Memory::ReadBlock(title_id_list_pointer, title_id_list.data(), title_count * sizeof(u64));
 
+    // Validate that update TIDs were passed in
+    if (must_be_patch) {
+        for (u32 i = 0; i < title_count; i++) {
+            u32 tid_high = static_cast<u32>(title_id_list[i] >> 32);
+            if ((tid_high >> 14 != 0x10) || (tid_high & 0xFFFF != 0xE)) {
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: that's not what i meant, this still has incorrect behavior due to operator precedence, use
`if ((tid_high >> 14) != 0x10 || (tid_high & 0xFFFF) != 0xE)`

Comment (shinyquagsire23) [reply src/core/hle/service/am/am.cpp]: Derp, fixed

**Comment by Subv** [comment]
I know this is pretty much the definition of scope creep, but GetDataTitleInfos also checks that every tid meets  `(high >> 14) == 16 && (high & 0xFFFF) == 0x8C`, if any of them doesn't meet that check, then error 0xE0E0803C is returned

File: src/core/hle/service/am/am.cpp [hunk 6]
```diff
@@ -302,40 +302,9 @@ void GetProgramList(Service::Interface* self) {
...
-        if (result.IsError()) {
-            IPC::RequestBuilder rb = rp.MakeBuilder(1, 4);
-            rb.Push(result);
-            rb.PushMappedBuffer(title_id_list_pointer, title_id_list_size, title_id_list_perms);
-            rb.PushMappedBuffer(title_info_out, title_info_size, title_info_perms);
-        }
-    }
-
-    for (u32 i = 0; i < title_count; i++) {
+ResultCode GetTitleInfoFromList(std::vector<u64>& title_id_list, Service::FS::MediaType media_type,
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: make the title id list const

**Comment by Subv** [comment]
Make the std::vector parameter a const reference and squash, LGTM

File: src/core/hle/service/am/am.cpp [hunk 7]
```diff
@@ -326,23 +317,113 @@ void GetProgramInfos(Service::Interface* self) {
...
+
+    std::vector<u64> title_id_list(title_count);
+    Memory::ReadBlock(title_id_list_pointer, title_id_list.data(), title_count * sizeof(u64));
+
+    ResultCode result = RESULT_SUCCESS;
+
+    // Validate that DLC TIDs were passed in
+    for (u32 i = 0; i < title_count; i++) {
+        u32 tid_high = static_cast<u32>(title_id_list[i] >> 32);
+        if ((tid_high >> 14) != 0x10 || (tid_high & 0xFFFF) != 0x8C) {
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: If this is checking for the high tid to be some specific value, define that value as an inline static constexpr variable and compare it to that instead of doing this bit fiddling

File: src/core/hle/service/am/am.cpp [hunk 8]
```diff
@@ -326,23 +317,113 @@ void GetProgramInfos(Service::Interface* self) {
...
+
+    std::vector<u64> title_id_list(title_count);
+    Memory::ReadBlock(title_id_list_pointer, title_id_list.data(), title_count * sizeof(u64));
+
+    ResultCode result = RESULT_SUCCESS;
+
+    // Validate that update TIDs were passed in
+    for (u32 i = 0; i < title_count; i++) {
+        u32 tid_high = static_cast<u32>(title_id_list[i] >> 32);
+        if ((tid_high >> 14) != 0x10 || (tid_high & 0xFFFF) != 0xE) {
```
Comment (Subv) [inline src/core/hle/service/am/am.cpp]: same here
