### PR TITLE
Rasterizer: Corrected the stencil implementation.

### LINKED ISSUE #1039: Super Mario 3D Land DEMO - Graphics glitches / missing textures
Spamming error:
HW.GPU <Error> video_core\debug_utils\debug_utils.cpp:Pica::DebugUtils::LookupTexture:592: Unknown texture format: 6

sm3dl 1

sm3dl 2

CITRACE LOG: https://goo.gl/5auSyA

### PR DESCRIPTION
**Pull request by Subv**
And implemented stencil in the hw renderer.
Implemented more stencil functions.

This was verified using hw tests, some of which can be found [here](https://gist.github.com/Subv/692aaf09d4593018bbcc).

I'll update the information on 3dbrew later.

Fixes #1039 and _maybe_ some of the problems with #1041

hwtests: https://github.com/Subv/3ds-homebrew/tree/master/gpu_stencil_tests

There's currently a bug related to changing the stencil buffer with the OpenGL renderer, it seems to only happen on Intel and is apparently a driver bug, a report has been filed [here](https://communities.intel.com/message/324464)

### CODE REVIEW

**Comment by neobrain** [comment]
Please change the hwtest to a readily compilable project.

**Comment by neobrain** [comment]
Please divide the hw renderer implementation and the fix into separate commits. There's no reason to have them in a single patch.

File: src/video_core/pica.h [hunk 1]
```diff
@@ -441,8 +441,12 @@ struct Regs {
     };
 
     enum class StencilAction : u32 {
-        Keep = 0,
-        Xor  = 5,
+        Keep      = 0,
+
+        Replace   = 2,
+        Incr      = 3,
```
Comment (neobrain) [inline src/video_core/pica.h]: ..ement

File: src/video_core/pica.h [hunk 2]
```diff
@@ -506,7 +510,7 @@ struct Regs {
 
                 // Action to perform when both stencil and depth testing pass
                 BitField< 8, 3, StencilAction> action_depth_pass;
-            };
+            } op;
```
Comment (neobrain) [inline src/video_core/pica.h]: these names aren't really needed.

File: src/video_core/pica.h [hunk 3]
```diff
@@ -487,15 +491,15 @@ struct Regs {
...
+                // Mask used to control writing to the stencil buffer
+                BitField< 8, 8, u32> write_mask;
 
                 // Value to compare against for stencil testing
                 BitField<16, 8, u32> reference_value;
 
                 // Mask to apply on stencil test inputs
                 BitField<24, 8, u32> mask;
-            };
+            } func;
```
Comment (neobrain) [inline src/video_core/pica.h]: name not needed

File: src/video_core/pica.h [hunk 4]
```diff
@@ -487,15 +491,15 @@ struct Regs {
...
-                // Value to calculate the new stencil value from
-                BitField< 8, 8, u32> replacement_value;
+                // Mask used to control writing to the stencil buffer
+                BitField< 8, 8, u32> write_mask;
 
                 // Value to compare against for stencil testing
                 BitField<16, 8, u32> reference_value;
 
                 // Mask to apply on stencil test inputs
                 BitField<24, 8, u32> mask;
```
Comment (neobrain) [inline src/video_core/pica.h]: Rename this to "input_mask"?

File: src/video_core/pica.h (hunk 2 above)
Comment (Subv) [inline src/video_core/pica.h]: But they are, unless we start performing arithmetic on the NotifyPicaRegisterChanged switch (which I'm not sure is even allowed).

Comment (Subv) [inline src/video_core/pica.h]: ... Can't edit on mobile. 

We need to listen for writes in the two words that compose this register, the most sensible way to do that was to name the inner structures and switch on their pica reg index

Comment (neobrain) [inline src/video_core/pica.h]: I see.

Would adding a "u32 raw" member have worked too, though? If so, I think that would be preferable because it allows for cleaner usage of these fields in all other places. Having to look up whether `action_*` is stored in `op` or `func` all the time can be pretty annoying.

Comment (Subv) [inline src/video_core/pica.h]: That doesn't solve the issue, there are two registers here.

Comment (neobrain) [inline src/video_core/pica.h]: You can add the "raw" field for both op and func though.

**Comment by Subv** [comment]
Addressed all comments, i'll upload the tests to my repo later.

File: src/video_core/rasterizer.cpp [hunk 5]
```diff
@@ -215,14 +215,25 @@ static void SetStencil(int x, int y, u8 value) {
     }
 }
 
-// TODO: Should the stencil mask be applied to the "dest" or "ref" operands? Most likely not!
-static u8 PerformStencilAction(Regs::StencilAction action, u8 dest, u8 ref) {
+// TODO: Should the stencil mask be applied to the "old_stencil" or "ref" operands? Most likely not!
```
Comment (yuriks) [inline src/video_core/rasterizer.cpp]: Does this comment still apply?

Comment (Subv) [inline src/video_core/rasterizer.cpp]: I actually did not test that in the hwtests, I assumed it was correct.

Comment (yuriks) [inline src/video_core/rasterizer.cpp]: Is it easy to test? Just might as well get rid of the todo while at it.

**Comment by yuriks** [comment]
LGTM

File: src/video_core/rasterizer.cpp [hunk 6]
```diff
@@ -780,10 +791,16 @@ static void ProcessTriangleInternal(const Shader::OutputVertex& v0,
             }
 
             u8 old_stencil = 0;
+
+            auto UpdateStencil = [&stencil_test, &x, &y, &old_stencil](Pica::Regs::StencilAction action) {
```
Comment (yuriks) [inline src/video_core/rasterizer.cpp]: You can capture `stencil_test`, `x` and `y` by value.

File: src/video_core/rasterizer.cpp (hunk 5 above)
Comment (Subv) [inline src/video_core/rasterizer.cpp]: I suppose, I'll get rid of another Todo while at it.

Comment (bunnei) [inline src/video_core/rasterizer.cpp]: This PR has my blessing after you get rid of that TODO

**Comment by Subv** [comment]
Removed the two stencil-related TODOs in the code. I'll upload the hwtests after i clean them up.

**Comment by Subv** [comment]
Uploaded the hwtests here: https://github.com/Subv/3ds-homebrew/tree/master/gpu_stencil_tests
I'm still working on this PR, please don't merge it yet.

**Comment by Subv** [comment]
There's currently a bug with the hardware renderer.
It's apparently not clearing the stencil buffer when the guest application zeroes it out. The sw renderer doesn't show this problem. See the "stencil write mask" test for a test case.

**Comment by Subv** [comment]
After some research, the bug happens because the glTexSubImage2D call in ReloadDepthBuffer isn't changing the stencil buffer (In this particular case it should be writing 0 to it), only the depth buffer.
Changing glTexSubImage2D to glTexImage2D fixes the issue. 
nVidia drivers don't show this problem however they crash with heap corruption when trying to load a new game.

**Comment by Subv** [comment]
A bug report has been made to Intel (https://communities.intel.com/message/324464) so i guess this is good for another review pass.

**Comment by yuriks** [comment]
@Subv: In the meantime, this issue can be worked around by checking if the texture type is GL_DEPTH_STENCIL and if so using `glTexImage2D` instead of `glTexSubImage2D`.

File: src/video_core/renderer_opengl/gl_rasterizer.cpp [hunk 7]
```diff
@@ -860,10 +869,15 @@ void RasterizerOpenGL::ReloadDepthBuffer() {
...
-    state.texture_units[0].texture_2d = 0;
+    if (fb_depth_texture.format == Pica::Regs::DepthFormat::D24S8) {
+        // TODO(Subv): There is a bug with Intel Windows drivers that makes glTexSubImage2D not change the stencil buffer.
+        // The bug has been reported to Intel (https://communities.intel.com/message/324464)
+        glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH24_STENCIL8, fb_depth_texture.width, fb_depth_texture.height, 0,
+            GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, temp_fb_depth_buffer.get());
+    } else {
+        glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, fb_depth_texture.width, fb_depth_texture.height,
+            fb_depth_texture.gl_format, fb_depth_texture.gl_type, temp_fb_depth_buffer.get());
+    }    state.texture_units[0].texture_2d = 0;
```
Comment (yuriks) [inline src/video_core/renderer_opengl/gl_rasterizer.cpp]: You ate a newline here

**Comment by Subv** [comment]
Updated

**Comment by yuriks** [comment]
LGTM

File: src/video_core/rasterizer.cpp [hunk 8]
```diff
@@ -780,10 +799,16 @@ static void ProcessTriangleInternal(const Shader::OutputVertex& v0,
             }
 
             u8 old_stencil = 0;
+
+            auto UpdateStencil = [stencil_test, x, y, &old_stencil](Pica::Regs::StencilAction action) {
```
Comment (neobrain) [inline src/video_core/rasterizer.cpp]: There is no apparent difference between "UpdateStencil" and "SetStencil". Suggestion: "ComputeAndSetNewStencil"

Comment (Subv) [inline src/video_core/rasterizer.cpp]: I disagree, SetStencil does a bunch of other stuff related to the format and swizzling, id prefer if this code remains separate

Comment (neobrain) [inline src/video_core/rasterizer.cpp]: Hm? I'm just suggestion a rename of this lambda.

Comment (yuriks) [inline src/video_core/rasterizer.cpp]: "UpdateStencil" sounds like a fine enough name to me, fwiw. (Maybe something like "MergeStencil" if you think "Update" isn't explicit enough? But for me there's a clear distinction between what "set" (set value, disregard what was there) and "update" (refresh or merge information) mean.)

Comment (neobrain) [inline src/video_core/rasterizer.cpp]: MergeStencil sounds like a good alternative.

**Comment by bunnei** [comment]
LGTM. I'm OK with the aforementioned change of "UpdateStencil" -> "MergeStencil".
