### PR TITLE
Service/AM: Fix crash when scanning titles with installed titles with invalid title IDs

### LINKED ISSUE #3332: Citra crashes after loading a game with a folder in nand\00000000000000000000000000000000\title with dddd in the name
example: 000400dbdddd
crash:
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoull

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

### PR DESCRIPTION
**Pull request by valentinvanelslande**
Fixes #3332

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3542)

### CODE REVIEW

File: src/core/hle/service/am/am.cpp [hunk 1]
```diff
@@ -456,11 +456,14 @@ void Module::ScanForTitles(Service::FS::MediaType media_type) {
     for (const FileUtil::FSTEntry& tid_high : entries.children) {
         for (const FileUtil::FSTEntry& tid_low : tid_high.children) {
             std::string tid_string = tid_high.virtualName + tid_low.virtualName;
-            u64 tid = std::stoull(tid_string.c_str(), nullptr, 16);
 
-            FileSys::NCCHContainer container(GetTitleContentPath(media_type, tid));
-            if (container.Load() == Loader::ResultStatus::Success)
-                am_title_list[static_cast<u32>(media_type)].push_back(tid);
+            if (tid_string.length() == 16) {
```
Comment (lioncash) [inline src/core/hle/service/am/am.cpp]: This should be a named constant instead of a magic number. i.e. something like `TITLE_ID_VALID_LENGTH` or something.

File: src/core/hle/service/am/am.cpp [hunk 2]
```diff
@@ -456,11 +456,14 @@ void Module::ScanForTitles(Service::FS::MediaType media_type) {
     for (const FileUtil::FSTEntry& tid_high : entries.children) {
         for (const FileUtil::FSTEntry& tid_low : tid_high.children) {
             std::string tid_string = tid_high.virtualName + tid_low.virtualName;
-            u64 tid = std::stoull(tid_string.c_str(), nullptr, 16);
 
-            FileSys::NCCHContainer container(GetTitleContentPath(media_type, tid));
-            if (container.Load() == Loader::ResultStatus::Success)
-                am_title_list[static_cast<u32>(media_type)].push_back(tid);
+            if (tid_string.length() == TITLE_ID_VALID_LENGTH) {
+                u64 tid = std::stoull(tid_string.c_str(), nullptr, 16);
```
Comment (baka0815) [inline src/core/hle/service/am/am.cpp]: I know you didn't change this line, but can't the same constant (``TITLE_ID_VALID_LENGTH``) be used here?
``u64 tid = std::stoull(tid_string.c_str(), nullptr, TITLE_ID_VALID_LENGTH);``

File: src/core/hle/service/am/am.h [hunk 3]
```diff
@@ -52,7 +52,9 @@ enum class InstallStatus : u32 {
     ErrorEncrypted,
 };
 
-// Progress callback for InstallCIA, recieves bytes written and total bytes
+constexpr size_t TITLE_ID_VALID_LENGTH = 16;
```
Comment (baka0815) [inline src/core/hle/service/am/am.h]: Please add a comment here what that constant is used for.

File: src/core/hle/service/am/am.cpp (hunk 2 above)
Comment (wwylele) [reply src/core/hle/service/am/am.cpp]: @baka0815 it is not the same thing. 16 means hexadecimal here

Comment (baka0815) [reply src/core/hle/service/am/am.cpp]: Ah, sorry!
