### PR TITLE
citra-qt: Fix connect error on startup (#449)

### LINKED ISSUE #449: Qt errors on startup
```
QObject::connect: Cannot connect (null)::screenChanged(QScreen*) to GRenderWindow::OnFramebufferSizeChanged()
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferWidthChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:87
QObject::connect:  (receiver name: 'PicaFramebuffer')
QObject::connect: No such slot GraphicsFramebufferWidget::OnFramebufferHeightChanged(int) in ..\..\..\src\citra_qt\debugger\graphics_framebuffer.cpp:88 
QObject::connect:  (receiver name: 'PicaFramebuffer')
```
They've been happening for a while, I'm not sure when it started

### PR DESCRIPTION
**Pull request by Kloen**
Finished #671 
Fixes #449

### CODE REVIEW

File: src/citra_qt/bootmanager.cpp [hunk 1]
```diff
@@ -274,3 +271,12 @@ void GRenderWindow::OnEmulationStarting(EmuThread* emu_thread) {
 void GRenderWindow::OnEmulationStopping() {
     emu_thread = nullptr;
 }
+
+void GRenderWindow::showEvent(QShowEvent * event) {
+    QWidget::showEvent(event);
+
+    // windowHandle() is not initialized until the Window is shown, so we connect it here.
+    #if QT_VERSION >= QT_VERSION_CHECK(5, 0, 0)
+        connect(this->windowHandle(), SIGNAL(screenChanged(QScreen*)), this, SLOT(OnFramebufferSizeChanged()));
```
Comment (LittleWhite-tb) [inline src/citra_qt/bootmanager.cpp]: I think there is a risk that the connect will be done multiple times during the execution of citra. Mainly because in multiple wndow mode, we are showing/hiding the window.

Comment (mattvail) [inline src/citra_qt/bootmanager.cpp]: You can specify the type in this case: Qt::UniqueConnection

"If you pass the Qt::UniqueConnection type, the connection will only be made if it is not a duplicate. If there is already a duplicate (exact same signal to the exact same slot on the same objects), the connection will fail and connect will return false."

Comment (LittleWhite-tb) [inline src/citra_qt/bootmanager.cpp]: That would be a perfect solution :)

**Comment by Kloen** [comment]
Addressed

**Comment by yuriks** [comment]
LGTM

**Comment by bunnei** [comment]
LGTM
