### PR TITLE
GPU/DefaultAttributes: Let the attribute data from the loaders overwrite the default attribs.

### LINKED ISSUE #735: Graphics regression in 3DSCraft
Commit 0e5ca080a86a6e393eab1a11075561a62a2e01f9 ("Default vertex shader attributes") introduced a shading regression in 3dscraft:

3dscraft

This issue is **not** fixed by #726.

cc @Subv @bunnei @neobrain

### PR DESCRIPTION
**Pull request by Subv**
This fixes a regression in 3dscraft, and maybe other games.
The behavior is consistent with what happens on 3dscraft on hardware
closes #735

### CODE REVIEW

File: src/video_core/command_processor.cpp [hunk 1]
```diff
@@ -127,29 +127,31 @@ static inline void WritePicaReg(u32 id, u32 value, u32 mask) {
...
-                            LOG_TRACE(HW_GPU, "Loaded component %x of attribute %x for vertex %x (index %x) from 0x%08x + 0x%08lx + 0x%04lx: %f",
-                                      comp, i, vertex, index,
-                                      attribute_config.GetPhysicalBaseAddress(),
-                                      vertex_attribute_sources[i] - base_address,
-                                      vertex_attribute_strides[i] * vertex + comp * vertex_attribute_element_size[i],
-                                      input.attr[i][comp].ToFloat32());
-                        }
+                    }
+                    
+                    // Overwrite the default data with the loader data if there's any
```
Comment (neobrain) [inline src/video_core/command_processor.cpp]: Comments like this suggest that they describe the sole intended behavior of the following code block - which is confusing in this case. Instead, I suggest moving this comment in a slightly rephrased way to the load-default-attributes-block, and have some "Load per-vertex data" comment in this line, instead.

**Comment by JMC47** [comment]
Tested vvvvvv, Cave Story 3D, Super Mario 3D Land, Cubic Ninja, Kirby Triple Deluxe, Steel Diver, Shovel Knight, and Super Monkey Ball 3D.  Didn't note any regressions in the menus or graphics that I got to.

**Comment by Subv** [comment]
Updated the comment

**Comment by bunnei** [comment]
LGTM

**Comment by yuriks** [comment]
LGTM
