### PR TITLE
Shader JIT Part 2

### LINKED ISSUE #1293: JMP compilation in the Shader JIT is fundamentally broken
The implementation of the JMP family instructions in the vertex shader JIT is broken. For certain programs, the generated control flow will jump to a random branch point in the program, causing certain parts of shaders to be completely skipped.

This happens when a jmp instruction jump over another jmp which itself jumps to a label beyond the target of the original jmp, like so:

```
    jmp label_1
    nop
    jmp label_2
label_1:
    nop
label_2:
    end
```

The first JMP will emit a branch, then initiate a nested loop compiling instructions until label_1. However, when it tries to compile `jmp label_2`, that will initiate another nested loop compiling until `label_2`. When this loop eventually finishes, it will return to the outer jmp compilation loop, which will notice it has passed `label_1` already and set the jump target. The end result is that both jmp instructions will jump to `label_2`.

### LINKED ISSUE #1402: Super Pokemon Rumble graphic issues.
I think that a picture talks on his own...

image

image

image

image

Specs:
image
image

### PR DESCRIPTION
**Pull request by bunnei**
Specifically, this is a new and improved implementation of flow control for the shader JIT. Previously, the shader JIT inlined CALL and JMP instructions. This had several issues: 1) Inlining all subroutines resulted in bloated shaders being generated, and 2) JMP to arbitrary addresses (and nested jumps) couldn't be supported.

With these changes, any arbitrary CALL/JMP will now work. Furthermore, this results in pretty constant compiled shader sizes of around ~40kb, so I changed allocation to happen on the fly (preventing cache clearing and recompiling of previously compiled shaders).

The changes in this patch could also be leveraged to support arbitrary (read: wacky) IF and LOOP instructions... But I didn't feel like doing this, particularly because these instructions in the JIT are a bit finicky and are already well vetted, and also AFAIK no game uses IF/LOOP in a way that the JIT didn't already support (mainly: backwards)

Fixes #1293
Fixes #1402

### CODE REVIEW

File: src/video_core/shader/shader_jit_x64.h [hunk 1]
```diff
@@ -81,13 +85,33 @@ class JitCompiler : public Gen::XCodeBlock {
...
+     */
+    void AnalyzeCalls();
+
+    /// Mapping of Pica VS instructions to pointers in the emitted code
+    std::array<const u8*, 1024> code_ptr;
+
+    /// Offsets in code where a return needs to be inserted
+    std::set<unsigned> return_offsets;
+
+    unsigned last_program_counter;  ///< Offset of the most recent instruction decoded
```
Comment (lioncash) [inline src/video_core/shader/shader_jit_x64.h]: Should these be given default values of zero? Same as `program` below?

File: src/video_core/shader/shader_jit_x64.cpp [hunk 2]
```diff
@@ -755,9 +777,25 @@ void JitCompiler::Compile_NextInstr(unsigned* offset) {
     }
 }
 
-CompiledShader* JitCompiler::Compile() {
-    const u8* start = GetCodePtr();
-    unsigned offset = g_state.regs.vs.main_offset;
+void JitCompiler::AnalyzeCalls() {
+    return_offsets.clear();
+
+    for (unsigned offset = 0; offset < g_state.vs.program_code.size(); ++offset) {
```
Comment (lioncash) [inline src/video_core/shader/shader_jit_x64.cpp]: `offset` should be a size_t

File: src/video_core/shader/shader_jit_x64.cpp [hunk 3]
```diff
@@ -718,30 +727,43 @@ void JitCompiler::Compile_JMP(Instruction instr) {
...
+    auto search = return_offsets.find(program_counter);
+    if (search != return_offsets.end()) {
+        Compile_Return();
+    }
+
+    ASSERT_MSG(code_ptr[program_counter] == nullptr, "Compiled instruction already!");
+    code_ptr[program_counter] = GetCodePtr();
+
+    Instruction instr;
+    std::memcpy(&instr, &g_state.vs.program_code[program_counter++], sizeof(Instruction));
```
Comment (lioncash) [inline src/video_core/shader/shader_jit_x64.cpp]: Perhaps this can be extracted to its own function, `GetVertexShaderInstruction` which can be something like:

```cpp
Instruction GetVertexShaderInstruction(size_t offset)
{
    Instruction instruction;
    std::memcpy(&instruction, &g_state.vs.program_code[offset], sizeof(Instruction));
    return instruction;
}
```

since a similar piece of code is used in AnalyzeCalls as well.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 4]
```diff
@@ -780,21 +818,36 @@ CompiledShader* JitCompiler::Compile() {
...
+    Compile_Block(static_cast<unsigned>(g_state.vs.program_code.size()));
 
-JitCompiler::JitCompiler() {
-    AllocCodeSpace(jit_cache_size);
+    // Set the target for any incomplete branches now that the entire shader program has been emitted
+    for (const auto& branch : fixup_branches) {
+        SetJumpTarget(branch.first, code_ptr[branch.second]);
+    }
+
+    uintptr_t size = reinterpret_cast<uintptr_t>(GetCodePtr()) - reinterpret_cast<uintptr_t>(program);
```
Comment (archshift) [inline src/video_core/shader/shader_jit_x64.cpp]: `ptrdiff_t size`?

File: src/video_core/shader/shader_jit_x64.cpp [hunk 5]
```diff
@@ -755,9 +777,25 @@ void JitCompiler::Compile_NextInstr(unsigned* offset) {
...
+        case OpCode::Id::CALLC:
+        case OpCode::Id::CALLU:
+            return_offsets.insert(instr.flow_control.dest_offset + instr.flow_control.num_instructions);
+            break;
+        }
+    }
+}
+
+void JitCompiler::Compile() {
+    program = reinterpret_cast<CompiledShader*>(GetCodePtr());
```
Comment (archshift) [inline src/video_core/shader/shader_jit_x64.cpp]: `reinterpret_cast<const CompiledShader*>`

Don't want to cast away that `const`!

File: src/video_core/shader/shader_jit_x64.cpp [hunk 6]
```diff
@@ -755,9 +787,24 @@ void JitCompiler::Compile_NextInstr(unsigned* offset) {
     }
 }
 
-CompiledShader* JitCompiler::Compile() {
-    const u8* start = GetCodePtr();
-    unsigned offset = g_state.regs.vs.main_offset;
+void JitCompiler::AnalyzeCalls() {
```
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: I'd prefer something like "CollectReturnOffsets" or something.
"AnalyzeCalls" sounds too generic to me (It even sounds like something performance related to me).

(Also if "IF" or "LOOP" are added later we'd have to rename this)

File: src/video_core/shader/shader_jit_x64.cpp [hunk 7]
```diff
@@ -718,30 +738,42 @@ void JitCompiler::Compile_JMP(Instruction instr) {
 
     bool inverted_condition = (instr.opcode.Value() == OpCode::Id::JMPU) &&
         (instr.flow_control.num_instructions & 1);
-    FixupBranch b = J_CC(inverted_condition ? CC_Z : CC_NZ, true);
-
-    Compile_Block(instr.flow_control.dest_offset);
 
-    SetJumpTarget(b);
+    fixup_branches.push_back({ J_CC(inverted_condition ? CC_Z : CC_NZ, true), instr.flow_control.dest_offset });
```
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: I'd prefer if the emitter call would be seperated from the push_back (create a variable) so it's more obvious that this line emits code.
Or maybe something like Compile_Branch(condition, destination) ?

File: src/video_core/shader/shader_jit_x64.cpp [hunk 8]
```diff
@@ -564,10 +575,22 @@ void JitCompiler::Compile_END(Instruction instr) {
...
+
+    // Push return address - not using CALL because we also want to push the offset of the return before jumping
+    MOV(64, R(RAX), ImmPtr(GetCodePtr() + SKIP));
+    PUSH(RAX);
+
+    // Push offset of the return
+    PUSH(32, Imm32(instr.flow_control.dest_offset + instr.flow_control.num_instructions));
+
+    // Jump
+    fixup_branches.push_back({ J(true), instr.flow_control.dest_offset });
```
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: Same as below. (Make it more obvious that this emits code).

File: src/video_core/shader/shader_jit_x64.cpp [hunk 9]
```diff
@@ -780,21 +827,36 @@ CompiledShader* JitCompiler::Compile() {
...
+    program_counter = 0;
     looping = false;
+    code_ptr.fill(nullptr);
+    fixup_branches.clear();
 
-    while (offset < g_state.vs.program_code.size()) {
-        Compile_NextInstr(&offset);
+    // Jump to start of the shader program
+    if (g_state.regs.vs.main_offset != 0) {
+        fixup_branches.push_back({ J(true),  g_state.regs.vs.main_offset });
```
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: Can't we use code_ptr to pass the main_offset to the shader at runtime?

Some games have ubershaders (and most games I've seen only have around 4-10 shaders anyway) but the entry point will control which shader to run.
I believe VS and GS are sometimes sharing code too.
So we could probably reduce a lot of compilations by having a dynamic entry point (and code_ptr seems to make it possible?!)

**Comment by bunnei** [comment]
Addressed all comments.

File: src/video_core/shader/shader_jit_x64.h [hunk 10]
```diff
@@ -19,12 +22,10 @@ namespace Pica {
...
 
-/// Memory needed to be available to compile the next shader (otherwise, clear the cache)
-constexpr size_t jit_shader_size = 1024 * 512;
-/// Memory allocated for the JIT code space cache
-constexpr size_t jit_cache_size = 1024 * 1024 * 8;
+/// Memory allocated for each compiled shader (64Kb)
+constexpr size_t MAX_SHADER_SIZE = 1024 * 64;
 
-using CompiledShader = void(void* registers);
+using CompiledShader = void(void* registers, const u8* start_addr);
```
Comment (MerryMage) [inline src/video_core/shader/shader_jit_x64.h]: `CompiledShader` is now internal to `JitCompiler`, maybe bring it into the class. [minor]

**Comment by MerryMage** [comment]
LGTM. Skimmed the logic a bit as I'm not 100% on it.

File: src/video_core/shader/shader.cpp [hunk 11]
```diff
@@ -29,36 +29,24 @@ namespace Pica {
...
-static void ClearCache() {
-    shader_map.clear();
-    jit.Clear();
-    LOG_INFO(HW_GPU, "Shader JIT cache cleared");
-}
+static std::unordered_map<u64, std::unique_ptr<JitCompiler>> shader_map;
+static const JitCompiler* jit_shader;
 #endif // ARCHITECTURE_x86_64
 
 void Setup(UnitState<false>& state) {
```
Comment (JayFoxRox) [inline src/video_core/shader/shader.cpp]: `state` isn't used anymore here. Parameter can be removed.

File: src/video_core/shader/shader_jit_x64.h (hunk 10 above)
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.h]: Agreed. Bring `CompiledShader` into JitCompiler.

**Comment by JayFoxRox** [comment]
(Thanks for waiting for my review and for putting so much effort into Citra in general)

I merged this with GS and tested:

* The Legend Of Korra: works
* WWE All Stars: works (only works with interpreter in current master)
* Ecco The Dolphin 3D: works
* Alien on the run: works
* Return to PopoCrolois: works (had glitches with interpreter in current master)

I've run some other games too but nothing weird happened.

---

Me and bunnei discussed replacing the compile time asserts by ABI function calls where the called function would `LOG_ERROR`. This sounds safer because the new approach might process dead code  which could trigger assertions otherwise.
In particular it was [this assert](https://github.com/citra-emu/citra/pull/1546/files#diff-57ec0b2a1b7ff70f4fd20bb37399827bR672).

So if that issue is addressed + what I recently diff-commented this LGTM.

File: src/common/x64/emitter.h [hunk 12]
```diff
@@ -430,7 +430,7 @@ class XEmitter
     FixupBranch J_CC(CCFlags conditionCode, bool force5bytes = false);
     void J_CC(CCFlags conditionCode, const u8* addr, bool force5Bytes = false);
 
-    void SetJumpTarget(const FixupBranch& branch);
+    void SetJumpTarget(const FixupBranch& branch, const u8* target = nullptr);
```
Comment (yuriks) [inline src/common/x64/emitter.h]: I'd drop the default param and add a small inline overload instead. This gets rid of the if, and then you can set jumps to null to your heart's content too!

File: src/video_core/shader/shader.cpp [hunk 13]
```diff
@@ -29,36 +29,24 @@ namespace Pica {
...
-static std::unordered_map<u64, CompiledShader*> shader_map;
-static JitCompiler jit;
-static CompiledShader* jit_shader;
-
-static void ClearCache() {
-    shader_map.clear();
-    jit.Clear();
-    LOG_INFO(HW_GPU, "Shader JIT cache cleared");
-}
+static std::unordered_map<u64, std::unique_ptr<JitCompiler>> shader_map;
```
Comment (yuriks) [inline src/video_core/shader/shader.cpp]: ~~Stuff about thes being confusing and separating the essential members into a non-compiler struct~~

File: src/video_core/shader/shader_jit_x64.cpp [hunk 14]
```diff
@@ -138,6 +138,27 @@ static const u8 NO_SRC_REG_SWIZZLE = 0x1b;
...
+    return instruction;
+}
+
+static void LogCritical(const char* msg) {
+    LOG_CRITICAL(HW_GPU, msg);
+}
+
+void JitCompiler::RuntimeAssert(bool condition, const char* msg) {
+    if (!condition) {
+        ABI_CallFunctionP(LogCritical, (void*)(msg));
```
Comment (lioncash) [inline src/video_core/shader/shader_jit_x64.cpp]: const_cast

File: src/video_core/shader/shader_jit_x64.h [hunk 15]
```diff
@@ -81,13 +83,40 @@ class JitCompiler : public Gen::XCodeBlock {
...
+
     BitSet32 PersistentCallerSavedRegs();
 
-    /// Pointer to the variable that stores the current Pica code offset. Used to handle nested code blocks.
-    unsigned* offset_ptr = nullptr;
+    /**
+     * Assertion evaluated at compile-time, but only triggered if executed at runtime.
+     * @param msg Message to be logged if the assertion fails.
+     */
+    void RuntimeAssert(bool condition, char* msg);
```
Comment (lioncash) [inline src/video_core/shader/shader_jit_x64.h]: Missing const? (the implementation specifies it)

File: src/video_core/shader/shader_jit_x64.cpp (hunk 14 above)
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: This is more of a reinterpret_cast

File: src/video_core/shader/shader_jit_x64.cpp [hunk 16]
```diff
@@ -138,6 +138,27 @@ static const u8 NO_SRC_REG_SWIZZLE = 0x1b;
 static const u8 NO_DEST_REG_MASK = 0xf;
 
 /**
+ * Get the vertex shader instruction for a given offset in the current shader program
+ * @param offset Offset in the current shader program of the instruction
+ * @return Instruction at the specified offset
+ */
+static Instruction GetVertexShaderInstruction(size_t offset) {
+    Instruction instruction;
+    std::memcpy(&instruction, &g_state.vs.program_code[offset], sizeof(Instruction));
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: You can just do `Instruct instruction{ &g_state.vs.program_code[offset] };`

File: src/video_core/shader/shader_jit_x64.cpp (hunk 14 above)
Comment (lioncash) [inline src/video_core/shader/shader_jit_x64.cpp]: Nope. This is a const_cast. It's well-defined.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 17]
```diff
@@ -157,7 +178,7 @@ void JitCompiler::Compile_SwizzleSrc(Instruction instr, unsigned src_num, Source
     }
 
     int src_offset_disp = (int)src_offset;
-    ASSERT_MSG(src_offset == src_offset_disp, "Source register offset too large for int type");
+    RuntimeAssert(src_offset == src_offset_disp, "Source register offset too large for int type");
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: What is this assert even checking against? It's kinda unclear, but I think this would be fine as a regular assert.

File: src/video_core/shader/shader_jit_x64.h (hunk 15 above)
Comment (bunnei) [inline src/video_core/shader/shader_jit_x64.h]: addressed

**Comment by JohnGodgames** [comment]
Ok so **Pokémon Rumble Blast** seems to pretty stable with this PR [video](https://www.youtube.com/watch?v=SstTsFoFnvo)

**Next tests:**
- Final Fantasy Explorers seems to stable too - played up to first quest

File: src/video_core/shader/shader_jit_x64.cpp (hunk 17 above)
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: True, this shouldn't be a runtime assert. Actually it shouldn't even be possible to happen at all (because the offset is based on the struct size which is known at compile time and all members should be reachable or we have a huge problem anyway).
I'd remove this assert altogether.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 18]
```diff
@@ -242,7 +252,7 @@ void JitCompiler::Compile_DestEnable(Instruction instr,X64Reg src) {
     SwizzlePattern swiz = { g_state.vs.swizzle_data[operand_desc_id] };
 
     int dest_offset_disp = (int)UnitState<false>::OutputOffset(dest);
-    ASSERT_MSG(dest_offset_disp == UnitState<false>::OutputOffset(dest), "Destinaton offset too large for int type");
+    RuntimeAssert(dest_offset_disp == UnitState<false>::OutputOffset(dest), "Destinaton offset too large for int type");
```
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: dito (can't happen and if it happens we have a different problem). Maybe we should static assert the size of the accessable data in UnitState?

File: src/video_core/shader/shader_jit_x64.cpp [hunk 19]
```diff
@@ -564,10 +583,23 @@ void JitCompiler::Compile_END(Instruction instr) {
 }
 
 void JitCompiler::Compile_CALL(Instruction instr) {
-    unsigned offset = instr.flow_control.dest_offset;
-    while (offset < (instr.flow_control.dest_offset + instr.flow_control.num_instructions)) {
-        Compile_NextInstr(&offset);
-    }
+    // Need to advance the return address past the proceeding instructions, this is the number of bytes to skip
+    constexpr unsigned SKIP = 21;
+    const ptrdiff_t start = reinterpret_cast<ptrdiff_t>(GetCodePtr());
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: I you want `uintptr_t` (or maybe `intptr_t`? I never used this one) instead here. Since the computation doesn't actually underflow uintptr_t is probably fine.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 20]
```diff
@@ -564,10 +583,23 @@ void JitCompiler::Compile_END(Instruction instr) {
...
+
+    // Push return address - not using CALL because we also want to push the offset of the return before jumping
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: Mismatching CALL/RET by replacing with JMP/RET is a bad idea since it messes with the return predictor. See [this blog post](https://blogs.msdn.microsoft.com/oldnewthing/20041216-00/?p=36973) and section 3.15 of [Agner's manual](http://www.agner.org/optimize/microarchitecture.pdf). Try to either use a matching CALL/RET pair or two JMPs.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 21]
```diff
@@ -718,30 +745,43 @@ void JitCompiler::Compile_JMP(Instruction instr) {
...
+    auto search = return_offsets.find(program_counter);
+    if (search != return_offsets.end()) {
+        Compile_Return();
+    }
 
-    // Restore current offset pointer
-    offset_ptr = prev_offset_ptr;
-    *offset_ptr = offset;
-}
+    ASSERT_MSG(code_ptr[program_counter] == nullptr, "Compiled instruction already!");
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: "Tried to compile already compiled shader location" or something to that effect.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 22]
```diff
@@ -718,30 +745,43 @@ void JitCompiler::Compile_JMP(Instruction instr) {
...
-void JitCompiler::Compile_Block(unsigned end) {
-    // Save current offset pointer
-    unsigned* prev_offset_ptr = offset_ptr;
-    unsigned offset = *prev_offset_ptr;
+void JitCompiler::Compile_NextInstr() {
+    last_program_counter = program_counter;
 
-    while (offset < end)
-        Compile_NextInstr(&offset);
+    auto search = return_offsets.find(program_counter);
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: To appease my O(n*m) concerns a bit: what's the maximum size this vector reaches usually? You could use sort it once after finding all addresses and then use std::binary_search, or maybe use a std::bitset.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 23]
```diff
@@ -718,30 +745,43 @@ void JitCompiler::Compile_JMP(Instruction instr) {
...
-    Compile_Block(instr.flow_control.dest_offset);
+void JitCompiler::Compile_Block(unsigned end) {
+    while (program_counter < end) {
+        Compile_NextInstr();
+    }
+}
+
+void JitCompiler::Compile_Return() {
+    // Pop return offset off the stack and check if we're at that offset
+    POP(RAX);
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: The POP, check, PUSH sequence is a bit weird. Should just check against the value in memory directly using SP-relative addressing.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 24]
```diff
@@ -780,21 +835,34 @@ CompiledShader* JitCompiler::Compile() {
...
 
+    // Find all `CALL` instructions and identify return locations
+    FindReturnOffsets();
+
+    // Reset flow control state
+    last_program_counter = 0;
+    program_counter = 0;
     looping = false;
+    code_ptr.fill(nullptr);
+    fixup_branches.clear();
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: You should do all this initialization before any code generation. I find it somewhat confusing/arbitrary to interleave it with other JIT (deferred) instructions.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 25]
```diff
@@ -780,21 +835,34 @@ CompiledShader* JitCompiler::Compile() {
...
+
+    // Set the target for any incomplete branches now that the entire shader program has been emitted
+    for (const auto& branch : fixup_branches) {
+        SetJumpTarget(branch.first, code_ptr[branch.second]);
     }
 
-    return (CompiledShader*)start;
+    ptrdiff_t size = reinterpret_cast<ptrdiff_t>(GetCodePtr()) - reinterpret_cast<ptrdiff_t>(program);
+    ASSERT(size <= MAX_SHADER_SIZE);
+    LOG_INFO(HW_GPU, "Compiled shader size=%d", size);
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: Is this really important enough to be INFO?

File: src/video_core/shader/shader_jit_x64.cpp [hunk 26]
```diff
@@ -780,21 +835,34 @@ CompiledShader* JitCompiler::Compile() {
...
+    Compile_Block(static_cast<unsigned>(g_state.vs.program_code.size()));
+
+    // Set the target for any incomplete branches now that the entire shader program has been emitted
+    for (const auto& branch : fixup_branches) {
+        SetJumpTarget(branch.first, code_ptr[branch.second]);
     }
 
-    return (CompiledShader*)start;
+    ptrdiff_t size = reinterpret_cast<ptrdiff_t>(GetCodePtr()) - reinterpret_cast<ptrdiff_t>(program);
+    ASSERT(size <= MAX_SHADER_SIZE);
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: Could be an ASSERT_MSG

File: src/video_core/shader/shader_jit_x64.h [hunk 27]
```diff
@@ -81,13 +83,40 @@ class JitCompiler : public Gen::XCodeBlock {
...
+     */
+    void FindReturnOffsets();
+
+    /// Mapping of Pica VS instructions to pointers in the emitted code
+    std::array<const u8*, 1024> code_ptr;
+
+    /// Offsets in code where a return needs to be inserted
+    std::set<unsigned> return_offsets;
+
+    unsigned last_program_counter = 0;  ///< Offset of the most recent instruction decoded
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.h]: It's unclear why you introduced this variable. Is there any specific reason?

File: src/video_core/shader/shader_jit_x64.cpp (hunk 22 above)
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: Oops, didn't realize this was a std::map. In any case, I think a sorted vector or a bitset as I mentioned above are better options.

**Comment by yuriks** [comment]
Review pass done.

File: src/video_core/shader/shader_jit_x64.cpp (hunk 22 above)
Comment (bunnei) [inline src/video_core/shader/shader_jit_x64.cpp]: Does this really matter..? Seems to me that using the map here is concise and fine.

**Comment by bunnei** [comment]
All comments addressed. Ready for another review pass.

File: src/video_core/shader/shader.cpp (hunk 13 above)
Comment (JayFoxRox) [inline src/video_core/shader/shader.cpp]: @yuriks that's true, but it should be a seperate issue.
My GS branch is based on this PR and it would suck to refactor any of them again before a merge to fix this general design issue.
This PR certainly improves what's contained in master and what you are saying is not really related to this PR.

File: src/common/x64/emitter.h [hunk 28]
```diff
@@ -425,12 +425,14 @@ class XEmitter
...
 #endif
     void CALL(const void* fnptr);
+    FixupBranch CALL();
     void CALLptr(OpArg arg);
 
     FixupBranch J_CC(CCFlags conditionCode, bool force5bytes = false);
     void J_CC(CCFlags conditionCode, const u8* addr, bool force5Bytes = false);
 
     void SetJumpTarget(const FixupBranch& branch);
+    void SetJumpTarget(const FixupBranch& branch, const u8* target);
```
Comment (JayFoxRox) [inline src/common/x64/emitter.h]: Might be worth another (nit) issue: why does this take a `const u8*` called `target` while it's called `addr` for `J_CC`?
And worse: why is it a `const void*` called `fnptr` for `CALL`?
I think the argument for this should be called `addr` and `CALL` should also be updated with the new name at some point.
\- I don't have any type preference.

File: src/video_core/shader/shader_jit_x64.cpp [hunk 29]
```diff
@@ -138,6 +138,25 @@ static const u8 NO_SRC_REG_SWIZZLE = 0x1b;
...
+ */
+static Instruction GetVertexShaderInstruction(size_t offset) {
+    return { g_state.vs.program_code[offset] };
+}
+
+static void LogCritical(const char* msg) {
+    LOG_CRITICAL(HW_GPU, msg);
+}
+
+void JitCompiler::RuntimeAssert(bool condition, const char* msg) {
```
Comment (JayFoxRox) [inline src/video_core/shader/shader_jit_x64.cpp]: Maybe call this: "Compile_Assert" or something?
It should be clear that this actually generates code imho.

(Also a comment wouldn't hurt maybe)

**Comment by JayFoxRox** [comment]
Aside from what I mentioned LGTM.
Still works fine with my GS branch.

I think next time you change something you should squash some changes together, the list of fixups is pretty long by now (also git thought you force pushed some of them when I rebased so I had to remove them to avoid duplicates?!)

File: src/video_core/shader/shader_jit_x64.cpp [hunk 30]
```diff
@@ -583,23 +583,15 @@ void JitCompiler::Compile_END(Instruction instr) {
...
-    // Need to advance the return address past the proceeding instructions, this is the number of bytes to skip
-    constexpr unsigned SKIP = 21;
-    const uintptr_t start = reinterpret_cast<uintptr_t>(GetCodePtr());
-
-    // Push return address - not using CALL because we also want to push the offset of the return before jumping
-    MOV(64, R(RAX), ImmPtr(GetCodePtr() + SKIP));
-    PUSH(RAX);
-
     // Push offset of the return
     PUSH(32, Imm32(instr.flow_control.dest_offset + instr.flow_control.num_instructions));
```
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: This is actually a 64-bit PUSH, but the bits param is ignored by our emitter (and then the 32-bit immediate is sign-extended in 64-bit mode). Would be better to make it match just to make it less confusing.

File: src/common/x64/emitter.h (hunk 28 above)
Comment (yuriks) [inline src/common/x64/emitter.h]: IMO `target` is a much, much clearer name, it's even in the function name. They're all pretty obvious in context but I don't see any reason for making the name worse for consistency when the other functions aren't even consistent in the first place.

File: src/video_core/shader/shader.cpp (hunk 13 above)
Comment (yuriks) [inline src/video_core/shader/shader.cpp]: These are all things that changed in this PR in the first place. I don't really understand what you're saying, but maybe you misunderstood what I was referring to.

Comment (yuriks) [inline src/video_core/shader/shader.cpp]: After investigating a bit, I don't think we can actually split the compilation from the memory management of the block with the code as-is, so I'm willing to concede this since it becomes out of scope. You can either make the emitter be able to decouple from the codeblock and return it, so we can transfer it to a new object, or create a dedicated holder for the block and then call emitter functions on it, but those are both large-ish changes.

However, you can still make sure to clear and shrink-to-fit any data structures that aren't used after compilation so we leave less garbage hanging off the object.

**Comment by bunnei** [comment]
Second pass of comments addressed. Ready for final review.

File: src/video_core/shader/shader_jit_x64.cpp (hunk 22 above)
Comment (yuriks) [inline src/video_core/shader/shader_jit_x64.cpp]: In case anyone ever checks this again: (We already resolved this on IRC)
 - std::set does one separate allocation for each unsigned, which adds execution and memory overhead
 - std::unordered_set is the same
 - The std::vector solution is only one extra line of code

**Comment by yuriks** [comment]
I bestow upon thee the holy LGTM

File: src/video_core/shader/shader.cpp (hunk 13 above)
Comment (JayFoxRox) [inline src/video_core/shader/shader.cpp]: Considering this is mostly a bugfix PR (+ tiny new features) I'm against this change.
I like the general idea though. But please split it into a seperate issue / PR.

File: src/common/x64/emitter.cpp [hunk 31]
```diff
@@ -531,6 +543,22 @@ void XEmitter::SetJumpTarget(const FixupBranch& branch)
...
+    {
+        s64 distance = (s64)(target - branch.ptr);
+        ASSERT_MSG(distance >= -0x80 && distance < 0x80, "Jump target too far away, needs force5Bytes = true");
+        branch.ptr[-1] = (u8)(s8)distance;
+    }
+    else if (branch.type == 1)
+    {
+        s64 distance = (s64)(target - branch.ptr);
+        ASSERT_MSG(distance >= -0x80000000LL && distance < 0x80000000LL, "Jump target too far away, needs indirect register");
+        ((s32*)branch.ptr)[-1] = (s32)distance;
```
Comment (lioncash) [inline src/common/x64/emitter.cpp]: memcpy

Comment (bunnei) [inline src/common/x64/emitter.cpp]: this is just a copy-pasta of code prevalent throughout the rest of the emitter. I think it makes sense to just clean up the emitter in a subsequent PR.
