### PR TITLE
gl_rasterizer_cache: exit FillTextureCube when address is invalid

### LINKED ISSUE #3635: Fire Emblem Awakening (EUR) Crash on Specific Unit Attack Phase Animation
Crash occurs when enemy Archer attack phase begins. Crash circumvented by skipping enemy attack turn. Most likely a graphics glitch. Crash was recreated several times. Crash did not occur in Canary|HEAD-eb8c415
System Information
    Operating System: Windows 7
    CPU: i7-7700K
    GPU: Nvidia GTX1080
    Citra Version: Nightly|HEAD-39fce60
    Game: Fire Emblem Awakening (EUR)
    Screenshot of Issue:
fea crash
Graphics: 
graphics

[log.txt](https://github.com/citra-emu/citra/files/1885782/log.txt)
Save file: [Chapter1.zip](https://github.com/citra-emu/citra/files/1885796/Chapter1.zip)

To recreate the glitch have an archer attack Chrom with Lissa Support. Just moving him to trees in the Archer's range will be enough to get it to attack him. Placing other units above and to his right will neutralize other attacks.

### PR DESCRIPTION
**Pull request by wwylele**
Game can feed the texture address register an invalid value and doesn't use the texture in the rendering pipeline. In this case we should just ignore the invalid texture. We already do this for normal texture units, and it should also be done fore the texture cube.

The texture cube is also changed such that it is not bound to the texture unit from the rasterizer initialization, but only bound when in use, just in the same way as normal textures. It will not be bound when texture cube is not used or when the address is invalid.

Aim to fix #3635.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/3639)

### CODE REVIEW

File: src/video_core/renderer_opengl/gl_rasterizer.cpp [hunk 1]
```diff
@@ -391,14 +390,19 @@ void RasterizerOpenGL::DrawTriangles() {
...
                     using CubeFace = Pica::TexturingRegs::CubeFace;
-                    res_cache.FillTextureCube(
-                        texture_cube.handle, texture,
-                        regs.texturing.GetCubePhysicalAddress(CubeFace::PositiveX),
-                        regs.texturing.GetCubePhysicalAddress(CubeFace::NegativeX),
-                        regs.texturing.GetCubePhysicalAddress(CubeFace::PositiveY),
-                        regs.texturing.GetCubePhysicalAddress(CubeFace::NegativeY),
-                        regs.texturing.GetCubePhysicalAddress(CubeFace::PositiveZ),
-                        regs.texturing.GetCubePhysicalAddress(CubeFace::NegativeZ));
+                    if (res_cache.FillTextureCube(
```
Comment (baka0815) [inline src/video_core/renderer_opengl/gl_rasterizer.cpp]: Wasn't it argued somewhere that the failure case should be first instead of the success case?

I personally would prefer this style (success first, failure per else).

Comment (wwylele) [reply src/video_core/renderer_opengl/gl_rasterizer.cpp]: That argument is valid when the success case is very long (e.g. you need to check more thing and more operation after this check). In this case the two are equally long, so I am fine with either style. Also, this follows the same style as the 2d texture handling below.

Comment (InusualZ) [reply src/video_core/renderer_opengl/gl_rasterizer.cpp]: I read some branch prediction article some time ago (No expert here), it said that you should put the most likely scenery first.

Comment (MerryMage) [reply src/video_core/renderer_opengl/gl_rasterizer.cpp]: That advice applies no longher applies for several reasons:

* It only applies when the branch predictor is cold.
* It applies to (generally speaking) older microarchitectures where there was a fixed prediction on a prediction miss.
* Assumes that the compiler emits branches in the order you expect.

In any case, readability matters far more.
