### PR TITLE
Request Camera Permission on MacOS

### LINKED ISSUE #5567: Citra camera crashing on macOS.
I'm playing Ultra Sun on citra-osx-20200919-a576eb6 under macOS Mojave 10.14.6; whenever I try to open the camera, citra crashes.
The crashlog shows the issue is a privacy violation (i.e. Citra doesn't have permission to use the Camera) and thus macOS terminates it.

```
Process:               citra-qt [5507]
Path:                  /Users/USER/Desktop/*/citra-qt.app/Contents/MacOS/citra-qt
Identifier:            com.citra-emu.citra
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           citra-qt [5507]
User ID:               501

Date/Time:             2020-09-30 23:57:10.758 -0300
OS Version:            Mac OS X 10.14.6 (18G6020)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        EA9784FA-1965-044C-73CA-79464B4271C5

Sleep/Wake UUID:       79140679-F370-4AE6-BAAD-00FBB9ECA444

Time Awake Since Boot: 110000 seconds
Time Since Wake:       25000 seconds

System Integrity Protection: disabled

Crashed Thread:        12  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace TCC, Code 0x0

Thread 12 Crashed:: Dispatch queue: com.apple.root.default-qos
0   libsystem_kernel.dylib        	0x00007fff715b5016 __abort_with_payload + 10
1   libsystem_kernel.dylib        	0x00007fff715b05d7 abort_with_payload_wrapper_internal + 82
2   libsystem_kernel.dylib        	0x00007fff715b0609 abort_with_payload + 9
3   com.apple.TCC                 	0x00007fff6bd8f091 __CRASHING_DUE_TO_PRIVACY_VIOLATION__ + 163
4   com.apple.TCC                 	0x00007fff6bd8efee __TCCAccessRequest_block_invoke.85 + 629
5   com.apple.TCC                 	0x00007fff6bd8d05d __tccd_send_message_block_invoke + 231
6   libxpc.dylib                  	0x00007fff71699e13 _xpc_connection_reply_callout + 36
7   libxpc.dylib                  	0x00007fff71699d9a _xpc_connection_call_reply_async + 86
8   libdispatch.dylib             	0x00007fff714156a7 _dispatch_client_callout3 + 8
9   libdispatch.dylib             	0x00007fff7142b977 _dispatch_mach_msg_async_reply_invoke + 311
10  libdispatch.dylib             	0x00007fff714240eb _dispatch_kevent_worker_thread + 1366
11  libsystem_pthread.dylib       	0x00007fff7165561b _pthread_wqthread + 431
12  libsystem_pthread.dylib       	0x00007fff716553fd start_wqthread + 13

```

This can probably be fixed by implementing a check for permissions along the lines of what's on here https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos

I'm currently trying to find some other method to manually grant Citra authorization but haven't been successful.

### PR DESCRIPTION
**Pull request by vitor-k**
An attempt to fix #5567.
If this works, supersedes #5568

Starting from macOS 10.14, users need to grant permissions for applications to use media capture (camera and microphone).

The application must provide a description in its Info.plist or it will be terminated due to privacy violation upon attempting to initialize camera/microphone. Applications should also request and check for permission from the user.

Apparently we need to trigger the permission request ourselves. This is done by calling the Objective-c function.
The request should pop up when the "qt" camera option is selected, or when the camera is started.

I have no machine that runs MacOS and thus no way to test this.

I haven't gotten to it yet but requesting for microphone usage should follow the same procedure.

Reference: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos?language=objc

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5786)

### CODE REVIEW

File: src/citra_qt/usage_authorization.mm [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+            case AVAuthorizationStatusAuthorized:
+                // The user has previously granted access to the camera.
+                authorized = true;
+                break;
+            case AVAuthorizationStatusNotDetermined:
+            {
+                // The app hasn't yet asked the user for camera access.
+                [AVCaptureDevice requestAccessForMediaType:media_type completionHandler:^(BOOL) {
+                    authorized = true;
+                }];
```
Comment (zhaowenlan1779) [inline src/citra_qt/usage_authorization.mm:41]:
```suggestion
                [AVCaptureDevice requestAccessForMediaType:media_type completionHandler:^(BOOL granted) {
                    authorized = granted;
                }];
```

Also, this doesn't seem right, as this method doesn't block, and therefore the first call of `CheckAuthorizationForCamera()` will always return false. You either need to make this block (probably with a `Common::Event`), or use some callback mechanic to inform the UI (QtMultimediaCamera) code of the authorization status. Either way, you won't need the static variable `authorized`.

File: src/citra_qt/usage_authorization.mm [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+                    LOG_INFO(Frontend, "Camera access requested.");
+                }
+                break;
+            }
+            case AVAuthorizationStatusDenied:
+            {
+                // The user has previously denied access.
+                authorized = false;
+                if(type == AuthMediaType::Camera) {
+                    LOG_WARNING(Frontend, "Camera access denied. To change this you may modify the macos system settings for Citra at 'System Preferences -> Security & Privacy -> Camera'");
```
Comment (zhaowenlan1779) [inline src/citra_qt/usage_authorization.mm:52]: This line is way too long, and this file doesn't really comply with our code style in general. I think we need to set up clang format for Objective-C++.

**Review by zhaowenlan1779 — CHANGES_REQUESTED** [review]

**Review by bunnei — APPROVED** [review]
