### PR TITLE
service/ldr_ro: Fix CRO loading when the buffer contained multiple VM areas

### LINKED ISSUE #4493: Mario Sports Superstars (Europe) fails to load tennis or golf
using the latest nightly and canary everytime you choose golf or tennis it just resets back to the citra menu 
the other 3 games work 
[citra_log.zip](https://github.com/citra-emu/citra/files/2659529/citra_log.zip)
log

### PR DESCRIPTION
**Pull request by zhaowenlan1779**
Fixes #4493

Fixed two bugs regarding adjacent memory areas with the same permission and state, but different backing pointers.

---

According to wwylele, the reason the bug in RO was made was that
 - on 3DS the ro module uses svcQueryProcessMemory to retrieve the vma info and do the same four checks as coded in VerifyBufferState
 - But later we found out that svcQueryProcessMemory would actually merge similar adjacent areas before reporting. 
https://github.com/citra-emu/citra/blob/7afcc0d658d3c0bcfd243613467e3fd31176db9c/src/core/hle/kernel/svc.cpp#L1092-L1104

so CRO code should contain the same merging logic or equivalent, or directly invoke the SVC implementation.

---
This change is [Reviewable](https://reviewable.io/reviews/citra-emu/citra/5125)

### CODE REVIEW

File: src/core/hle/kernel/vm_manager.cpp [hunk 1]
```diff
@@ -151,13 +151,16 @@ ResultCode VMManager::ChangeMemoryState(VAddr target, u32 size, MemoryState expe
     }
 
     CASCADE_RESULT(auto vma, CarveVMARange(target, size));
-    ASSERT(vma->second.size == size);
```
Comment (B3n30) [inline src/core/hle/kernel/vm_manager.cpp]: shouldn't there be still an assert for the overall size?

Comment (zhaowenlan1779) [reply src/core/hle/kernel/vm_manager.cpp]: I believe this is actually not necessary, as `CarveVMARange` will take care of this
